appveyor.yml

This reverts commit 1a349f38752d6da061e47e79c48ac22c3bd9d8f2.
Can't build Skyline/Bibliospec without Mascot Parser and Thermo MSFileReader.

Revert "* added Skyline testing to AppVeyor config"

---

pwiz_tools/Skyline/Controls/Graphs/GraphChromatogram.cs

This exception happens if you have only one color in your color scheme.

Fix IndexOutOfRangeException in DisplayAllIonsSumary

---

pwiz_tools/Shared/Common/Common.csproj
pwiz_tools/Shared/Common/Database/SqliteOperations.cs
pwiz_tools/Shared/ProteomeDb/API/ProteomeDb.cs
pwiz_tools/Skyline/CommonTest/CommonTest.csproj
pwiz_tools/Skyline/CommonTest/SqliteOperationsTest.cs
pwiz_tools/Skyline/Model/Lib/BiblioSpecLite.cs

We were spending much too long in "BiblioSpecLiteLibrary.AnnotationsForObservedMz" if the table "RefSpectraPeakAnnotations" did not exist.
I changed it so that we check that the table exists by querying the sqlite_master table, instead of catching an exception and it seems to be hundreds of times faster.
I added the utility class "SqliteOperations" with the method "TableExists" and I changed the other places where we were checking for table existence to use this new method.
I am currently running unit tests on my machine.

Speed up BiblioSpecLiteLibrary.AnnotationsForObservedMz

---

pwiz_tools/Skyline/Alerts/AlertDlg.cs

Hoping this may shed some light on the "Operation succeeded" failures

Skyline: include HRESULT info in Exception report dialog

---

pwiz_tools/Skyline/Controls/Graphs/AreaCVToolbar.cs
pwiz_tools/Skyline/Controls/GroupComparison/CreateMatchExpressionDlg.Designer.cs
pwiz_tools/Skyline/Controls/GroupComparison/CreateMatchExpressionDlg.cs
pwiz_tools/Skyline/Controls/GroupComparison/CreateMatchExpressionDlg.resx
pwiz_tools/Skyline/Controls/GroupComparison/FoldChangeVolcanoPlot.cs
pwiz_tools/Skyline/Model/GroupComparison/MatchExpression.cs
pwiz_tools/Skyline/TestFunctional/VolcanoPlotFormattingTest.cs

- fixed slow filtering (filtering is now done on background thread and
list of matching rows uses a data source)
- now allowing user to filter by protein name/accession/preferred/name/gene for peptides
- fixed nullreferenceexception in AreaCVToolbar (see exceptions 36514, 36515, 36883)

Skyline - volcano plot fixes

---

pwiz/analysis/spectrum_processing/SpectrumList_Filter.cpp
pwiz/analysis/spectrum_processing/SpectrumList_FilterTest.cpp

- changed ms level filter so that non-MS spectra (e.g. EMR spectra) are considered ms level 0, so they can be included/excluded by the filter the same way other levels can

Change ms level filter for non-MS spectra

---

pwiz_tools/Skyline/CommandArgs.cs
pwiz_tools/Skyline/CommandLine.cs
pwiz_tools/Skyline/Model/Import.cs
pwiz_tools/Skyline/Model/MultiFileLoader.cs
pwiz_tools/Skyline/TestA/CommandLineTest.cs
pwiz_tools/Skyline/Util/DataSourceUtil.cs

- Add support for NormalizedRetentionTime column in assay library import
- Force several and many threaded imports to use at least 2 threads
- Add new --import-all-files command-line argument that is not recursive

Skyline: Fixes for DIA Course

---

pwiz_tools/Skyline/CommandArgs.cs
pwiz_tools/Skyline/CommandLine.cs
pwiz_tools/Skyline/Model/SrmDocument.cs
pwiz_tools/Skyline/Properties/Resources.Designer.cs
pwiz_tools/Skyline/Properties/Resources.ja.resx
pwiz_tools/Skyline/Properties/Resources.resx
pwiz_tools/Skyline/Properties/Resources.zh-CHS.resx
pwiz_tools/Skyline/Skyline.csproj
pwiz_tools/Skyline/TestA/CommandLineTest.cs

- Allow --import-all and --import-replicate-name together for importing multiple files in a folder to a single replicate
- Try to keep Skyline changing settings from removing transitions from copy-pasted standard peptides (e.g. iRT standards with only precursor transitions into a fragment-only DIA document)

Skyline: Fixes for working with gas phase fractionated DIA data

---

pwiz_tools/Skyline/TestTutorial/TargetedMSMSTutorialTest.cs

Fixed TargetedMSMSTutorialTest when run as small molecules (88 vs 87 transitions failure; The document was converted to small molecules in between pages of the ImportPeptideSearchDlg, which didn't change the internal document copy maintained by the wizard)

Fixed TestTargetedMSMSTutorialAsSmallMolecules

---

pwiz_tools/Bumbershoot/quameter/quameter.cpp

- fixed quameter id-free error "No MS1 spectrum found before <first MS2>" because some files explicitly acquire some (presumably non-DDA) MS2s before the first MS1

Fix quameter id-free error "No MS1 spectrum found before <first MS2>"

---

Jamroot.jam
libraries/boost-build/src/tools/testing.jam

* set <preserve-test-targets>off for MSVC debug builds to save gigs of space taken up by successful test EXE/OBJ/PDBs

* set <preserve-test-targets>off for MSVC debug builds

---

pwiz_tools/Bumbershoot/quameter/quameter.cpp

* fixed Quameter to skip MS2s before the first MS1 instead of including them in metrics

* fixed Quameter to skip MS2s before the first MS1

---

pwiz/analysis/spectrum_processing/Jamfile.jam
pwiz/analysis/spectrum_processing/SpectrumList_IonMobility_Test.cpp
pwiz/data/vendor_readers/Waters/SpectrumList_Waters.cpp
pwiz_aux/msrc/utility/vendor_api/Waters/WatersRawFile.hpp
pwiz_tools/MSConvertGUI/MainForm.cs

* added `WaterRawFile::HasCcsCalibration()` 
- fixed `SpectrumList_Waters::canConvertIonMobilityAndCCS()` to only return true if `WaterRawFile::HasCcsCalibration()` does
* fixed some SpectrumList_IonMobility_Test tests not actually being enforced
* fixed typo in MSConvertGUI tooltip

Fix SpectrumList_IonMobility bugs

---

pwiz_tools/Skyline/Model/DocSettings/Prediction.cs
pwiz_tools/Skyline/Model/Results/IonMobilityFinder.cs
pwiz_tools/Skyline/SettingsUI/IonMobility/EditDriftTimePredictorDlg.cs
pwiz_tools/Skyline/Test/Results/MeasuredDriftValuesTest.cs
pwiz_tools/Skyline/TestFunctional/IonMobilityTest.cs
pwiz_tools/Topograph/TopographTestProject/ChromatogramGeneratorTest.cs

1. Fix InvalidOperationException when "apexRT" does not have a value (in "IonMobilityFinder.ProcessChromInfo").
2. When doing "use results" on "EditDriftTimePredictorDlg", pay attention to whether "Use high energy offset" is checked. If it's not checked, then always use 0 for the high energy offset.

Drift Time & CCS fixes

---

pwiz_tools/Skyline/TestRunnerLib/MiniDump.cs
pwiz_tools/Skyline/TestRunnerLib/RunTests.cs
pwiz_tools/Skyline/TestRunnerLib/TestRunnerLib.csproj

- Now creating a memory before and after certain tests run.
If the total memory difference does not exist a threshold that can be set
for each test that is tracked, the memory dumps are deleted
- Currently tracking TestDocumentSizeError and TestExistingExperimentsTutorial

Skyline - creating memory dumps during test runs

---

pwiz_tools/Skyline/TestRunnerLib/MiniDump.cs
pwiz_tools/Skyline/TestRunnerLib/RunTests.cs

- now mini dump names contain the test name, test number, pass, language and timestamp
- mini dumps are now stored in the same directory as the log file, that way they are not deleted after multiple nightly runs

Memory dump fixes

---

pwiz_tools/Skyline/Controls/Startup/ActionBoxControl.Designer.cs
pwiz_tools/Skyline/Controls/Startup/ActionBoxControl.cs

The RichTextBox on the ActionBoxes is preventing users from being able to click.
I am not sure why that is-- probably something to do with mousemove events hiding and showing controls, but I'm not sure.

Revert the code which shows a RichTextBox on the Action Boxes

---

pwiz_aux/msrc/utility/vendor_api/ABI/WiffFile2.ipp
pwiz_tools/Skyline/Util/DataSourceUtil.cs

- added workaround for "Can only get parent m/z for product scans" error when reading MS2s from WIFF2 files
- renamed some Skyline vendor file type strings to clarify which formats are supported

Fix "Can only get parent m/z for product scans" error

---

pwiz_tools/BiblioSpec/src/MaxQuantReader.cpp
pwiz_tools/BiblioSpec/src/MaxQuantReader.h

- made missing MaxQuant modifications an error rather than a warning and improved the error message a bit

Missing MaxQuant modifications error

---

pwiz_tools/Skyline/CommandLine.cs
pwiz_tools/Skyline/Model/MemoryDocumentContainer.cs

1. Register OptimizationDbManager with MemoryDocumentContainer
2. Catch and log exception while trying to list sample files in a WIFF file. This can happen if the file is still locked by the instrument software.

Fixes for bugs reported by Paul Auger with AutoQC Loader and Skyline 4.2

---

pwiz_aux/msrc/utility/vendor_api/ABI/WiffFile.cpp
pwiz_aux/msrc/utility/vendor_api/ABI/WiffFile2.ipp

- fixed errors when opening multiple WIFF2s at the same time
- addressed issue with WiffFile's MassSpectrometerSample not being disposed (unverified, no repro)

Fix WIFF issues (4.2)

---

pwiz_tools/Shared/Common/DataBinding/Controls/Editor/ManageViewsForm.resx
pwiz_tools/Shared/Common/DataBinding/Controls/Editor/ViewEditor.resx
pwiz_tools/Shared/Common/DataBinding/Controls/NavBar.resx
pwiz_tools/Shared/Common/Properties/Resources.Designer.cs
pwiz_tools/Shared/Common/Properties/Resources.resx
pwiz_tools/Skyline/TestTutorial/CustomReportsTutorialTest.cs

Rename "Views" dropdown on Document Grid to "Reports", and replace all occurrences of things like "Manage Views" to "Manage Reports", etc.

Rename "Views" dropdown on Document Grid to "Reports"

---

pwiz_tools/Skyline/TestA/PwizFileInfoTest.cs

Turns out I hadn't removed the old conditional from the release branch code, almost certainly due to an error I made resolving a conflict.

Fix stale WIFF2 logic from resolving conflict

---

pwiz_tools/Skyline/Skyline.csproj

I suspect side-by-side lookup for the VC DLLs will not work if the platform specific DLLs are not next to the VC DLLs

* moved Shimadzu DLLs to root directory

---

pwiz/analysis/spectrum_processing/SpectrumList_ChargeFromIsotope.cpp

This change (which only affects the functionality of msconvert's Turbocharger precursor charge algorithm) prevents a runtime error from being thrown in the event that there are greater than maxNumberPeaks (currently set to 40) in parent scan's isolation window. These changes simply use the 40 most intense peaks within the isolation window and discard the remaining peaks. 
This change was requested by Professor David Tabb several months ago as data from a SCIEX TripleTOF was frequently exceeding maxNumberPeaks. 
In case you're wondering, the reason we hard-coded this number is that Turbocharger simulates the total intensity and relative intensities for scoring and needs some place to store those simulated data for computing p values during analysis. The vector storing these simulated data …

Filter peaks in parent scan isolation window to bring total peak count below maxNumberPeaks

---

pwiz_tools/Skyline/Skyline.csproj

Here's the fix for the Skyline 4.2 installer.
It looks like timsdata.dll started being included in the 32 bit build on December 4, 2018.
Our unit tests did not catch this new dependency because timsdata.dll had been included in TestSettings_x86.testsettings ever since September, even though that file probably had no effect at the time.

Fix missing file timsdata.dll in Skyline 4.2 32 bit installer.

---

pwiz_tools/commandline/msconvert.cpp

* moved source file location stripping to right before writing output file so that SHA-1 calculator and filters can access the file location

Fix stripLocationFromSourceFiles

---

scripts/wix/pwiz-setup.py
scripts/wix/pwiz-setup.wxs.template

- fixed MSConvertGUI/SeeMS context menu shortcuts that were broken with the recent change to dual-scope installer
- fixed default install location for 64-bit: it will now go to %PROGRAMFILES% instead of %PROGRAMFILES(x86)%; also the version will again have the git hash suffix and only per-user installs will have the 64-bit/32-bit suffix

Installer fixes

---

pwiz/data/vendor_readers/Thermo/Reader_Thermo_Detail.cpp
pwiz/data/vendor_readers/Thermo/SpectrumList_Thermo.cpp
pwiz_aux/msrc/utility/vendor_api/thermo/RawFile.cpp
pwiz_aux/msrc/utility/vendor_api/thermo/RawFile.h

- added instrumentConfiguration for PDA spectra
* added support for preferOnlyMsLevel to SpectrumList_Thermo and made it exclude PDA spectra when non-zero
* moved Thermo mutex out of RawFile back into SpectrumList_Thermo: the reader is still stateful at the controller level, so asking for a PDA spectrum when MS controller is selected is an error
@nickshulman should fix the "Line" issue with 32-bit, and restores PDA enumeration in 64-bit, but at the same time lets Skyline exclude them with the preferOnlyMsLevel option (which I assumed is set for all formats, not just Bruker TDF, but I didn't check).

- fixed Thermo PDA spectra not being enumerated in 64-bit

---

pwiz/data/vendor_readers/Agilent/Reader_Agilent.cpp

now there must be an AcqData directory, and it must also have a MSPeak.bin or MSProfile.bin file inside the AcqData directory

- improved data type check for Agilent MassHunter data

---

pwiz/data/msdata/SpectrumWorkerThreads.cpp
pwiz_aux/msrc/utility/vendor_api/ABI/WiffFile.cpp
pwiz_aux/msrc/utility/vendor_api/ABI/WiffFile2.ipp

- changed Sciex peak picker to multiply Y (area) values by 100 to put them on a more similar scale to the profile peak heights
- removed useThreads message

Change Sciex peak picker to multiply Y (area) values by 100

---

pwiz/utility/bindings/CLI/analysis/spectrum_processing.cpp
pwiz/utility/bindings/CLI/analysis/spectrum_processing.hpp
pwiz_tools/MSConvertGUI/MainForm.cs
pwiz_tools/MSConvertGUI/MainLogic.cs

* added IterationListenerRegistry overloads for CLI bindings of SpectrumListFactory and enabled progress feedback for spectrum list filtering in MSConvertGUI
- fixed exceptions when typing filename into MSConvertGUI text box and fixed scan event and scan time filter syntax when only lower or upper bound is set

MSConvertGUI fixes

---

pwiz_tools/Shared/ProteowizardWrapper/MsDataFileImpl.cs
pwiz_tools/Skyline/TestData/PwizFileInfoTest.cs

* added MsDataFileImpl.SupportsMultipleSamples() and used it to ignore sampleIndex for non-WIFF files in PwizFileInfoTest

Fix PwizFileInfoTest "multiple runs not supported"

---

pwiz_tools/Skyline/TestRunnerLib/RunTests.cs

(console output is unchanged, still integer-truncated seconds)

Skyline: switched to milliseconds for reporting test duration to TeamCity

---

pwiz/data/msdata/SpectrumListBase.hpp
pwiz/data/msdata/SpectrumList_BTDX.cpp
pwiz/data/msdata/SpectrumList_MGF.cpp
pwiz/data/msdata/SpectrumList_MSn.cpp
pwiz/data/msdata/SpectrumList_mz5.cpp
pwiz/data/msdata/SpectrumList_mzML.cpp
pwiz/data/msdata/SpectrumList_mzXML.cpp
pwiz/data/vendor_readers/ABI/SpectrumList_ABI.cpp
pwiz/data/vendor_readers/Agilent/SpectrumList_Agilent.cpp
pwiz/data/vendor_readers/Bruker/SpectrumList_Bruker.cpp
pwiz/data/vendor_readers/Shimadzu/SpectrumList_Shimadzu.cpp
pwiz/data/vendor_readers/Thermo/SpectrumList_Thermo.cpp
pwiz/data/vendor_readers/UIMF/SpectrumList_UIMF.cpp
pwiz/data/vendor_readers/UNIFI/SpectrumList_UNIFI.cpp
pwiz/data/vendor_readers/Waters/SpectrumList_Waters.cpp
pwiz_tools/BiblioSpec/src/BlibUtils.cpp
pwiz_tools/BiblioSpec/src/BlibUtils.h
pwiz_tools/BiblioSpec/src/BuildParser.cpp
pwiz_tools/BiblioSpec/src/PwizReader.cpp

* added helpful warning when call to SpectrumList::find() fails because the SpectrumList format and query format do not match (e.g. "scan=123" vs. "function=1 process=0 scan=123")
This is particularly useful when trying to match mzIdentML ids to MSData ids.

Add SpectrumList::find() id mismatch warning message

---

pwiz/data/vendor_readers/Thermo/ChromatogramList_Thermo.cpp
pwiz_aux/msrc/utility/vendor_api/thermo/RawFile.h

- re-enabled Thermo PDA and UV chromatograms (disabled since upgrading to RawFileReader); added checks so that other chromatography traces (like pump pressure) are not interpreted as UV chromatograms

Re-enable Thermo PDA and UV chromatograms

---

appveyor.yml
pwiz/data/vendor_readers/ABI/ChromatogramList_ABI.cpp
pwiz/utility/misc/cpp_cli_utilities.hpp

- fixed error message about missing .scan file not being shown if error is triggered during chromatogram retrieval
* removed exception handling around Sciex BPC/TIC retrieval because it was only needed when ALL samples were being aggregated and some samples might cause errors

Fix error message when Sciex .wiff.scan file is missing

---

pwiz_tools/BiblioSpec/src/MzIdentMLReader.cpp

- fixed BiblioSpec reading buggy OpenMS/Percolator files with rank=0 and some SpectrumIdentificationItems not having PeptideEvidenceRefs

- fixed BiblioSpec reading buggy OpenMS/Percolator files

---

pwiz/data/vendor_readers/Thermo/ChromatogramList_Thermo.cpp
pwiz/data/vendor_readers/Thermo/ChromatogramList_Thermo.hpp
pwiz_aux/msrc/utility/vendor_api/thermo/RawFile.h

- added CAD chromatogram for Thermo (treating it as a kind of TIC)
* fixed enumeration of PDA chromatograms on 64-bit (really need a unit test file for this...)
* refactored repeated code out of ChromatogramList_Thermo::createIndex() into new private addChromatogram() function

Added CAD chromatogram for Thermo

---

pwiz/analysis/spectrum_processing/SpectrumListFactory.cpp
pwiz/analysis/spectrum_processing/SpectrumListFactory.hpp
pwiz/data/vendor_readers/Bruker/SpectrumList_Bruker.cpp
pwiz_tools/commandline/msconvert.cpp

- added "--help-filter" option to msconvert which will show detailed help for a single named filter (and if the user types a filter name wrong, it will list the available filters)
* added a reserve() call for Bruker scanList when creating list of merged PASEF scans

- added "--help-filter" option to msconvert

---

Jamroot.jam
pwiz_tools/BiblioSpec/tests/Jamfile.jam

preserve-test-targets=off was deleting the ExecuteBlib.obj file which is shared between all the tests (although I'm not quite sure why it's not renaming the .obj file based on each test's unique name; may want to revisit this later because the pdb files still take up a lot of space after running tests); <preserve-test-targets>off in Jamroot.jam will be moved to TC build commands (--remove-test-targets)

* fixed BiblioSpec tests building in parallel when debug-symbols=on

---

pwiz_tools/Skyline/Model/Results/ChromHeaderInfo.cs

Related email thread:
On 7/26/2019 12:08 PM, Matt Chambers wrote:
The data I were testing were Agilent MRM PerfTest data. I suspect this is the TIC of MS1 only or TIC of all MS levels issue that Brian noted earlier. These large MRM files do have over 100,000 points in their pwiz TIC chromatogram (which in this case it's just reading from the vendor API), which is what the CheckUShort is testing against. There's no precursor or peaks so there's nothing to filter down and interpolate on. In this case, there are also no MS1s. Even if I were able to filter down to just the MS1s (which I'm not able to do for all vendors without enumerating all spectra at InstantMetadata level), this code would assume that either:
1. The TIC is not included in the ChromGroupHeaderInfos
or
2. That all files will …

* changed CheckUShort to avoid choking on higher point counts from TICs

---

pwiz/data/vendor_readers/Thermo/SpectrumList_Thermo.cpp
pwiz_aux/msrc/utility/vendor_api/thermo/RawFile.cpp

(when written without centroid stream)
- fixed getPrecursorIntensity() crash with empty m/z array

- added fallback centroiding of Thermo FTMS data 

---

pwiz_tools/Skyline/TestUtil/ExtensionTestContext.cs

* removed WIFF2 DayOfYear timebomb (WIFF2 tests will be disabled for 32-bit or French-like language settings until new SDK is integrated)
@brendanx67 I assume you want this merged to release as well?

Disarm WIFF2 DayOfYear timebomb

---

pwiz_aux/msrc/utility/vendor_api/thermo/RawFile.cpp

- fixed issue with non-SPS spectra being treated as having multiple precursors, which disabled utilization of the monoisotopic m/z

Fixed issue with non-SPS spectra

---

pwiz_tools/Skyline/TestUtil/AbstractUnitTest.cs
scripts/misc/tc-perftests.bat

* added SKYLINE_DOWNLOAD_FROM_S3 logic to replace perftest and tutorial urls with S3 ones, which download extremely fast on AWS EC2 agents
* added script to run Skyline perf tests one at a time on TC

Add practical support for running perf and tutorial tests on TeamCity

---

pwiz/utility/misc/cpp_cli_utilities.hpp

to allow Skyline nightly tests to check whether that fixes the TestMs1Tutorial "leak"
@brendanx67 This seems to have changed the memory usage profile in my local testing, but I still don't think it was/is a real leak. PWIZ_MANAGED_PASSTHROUGH certainly changes how the core code uses managed memory instead of native for several of the vendor readers, so I can easily see it breaking the previously acceptable 300kb heuristic. But it is really WEIRD how non-deterministic it is. Makes it seem garbage-collection related. If this fixes the "leak", what then? I don't think I ever did a performance comparison with the passthrough vs without. I should do that in any case.

Disable PWIZ_MANAGED_PASSTHROUGH

---

pwiz_tools/Skyline/TestFunctional/AuditLogValidationTest.cs

https://skyline.ms/testresults/home/development/Nightly%20x64/showFailures.view?end=09/30/2019&failedTest=TestAuditLogValidation

ShowDialog timeout set to 3000 to avoid intermittent test failure.

---

pwiz_tools/BiblioSpec/src/MaxQuantModReader.cpp
pwiz_tools/BiblioSpec/src/PepXMLreader.cpp

BiblioSpec:
- disabled parsing spectrumNativeID attribute for iProphet pepXML
- added support for '2H' element in MaxQuant modifications.xml compositions

BiblioSpec: fix spectrumNativeID issue for iProphet and 2H element for MaxQuant

---

pwiz_tools/Skyline/SettingsUI/ViewLibraryDlg.cs

(reported by Tomas)
The RetentionTimes table in a Pecan library always has zero in the "BestSpectrum" column. Because of this, GetSpectra(...,best) always returns null.
We used to handle this gracefully, but recent changes caused this to be a NullReferenceException.

Fix exception viewing spectral library from Pecan.

---

pwiz_tools/Skyline/TestTutorial/Ms1FullScanFilteringTutorial.cs

The order of the items in SkylineWindow.GraphChromatograms changed because of recent "MRU chromatogram" change.

Fix TestMs1Tutorial.

---

pwiz/data/msdata/ChromatogramList_mz5.cpp
pwiz/data/msdata/mz5/Configuration_mz5.cpp
pwiz/data/msdata/mz5/Configuration_mz5.hpp
pwiz/data/msdata/mz5/ReferenceWrite_mz5.cpp

Reverts ProteoWizard/pwiz#643
The backward compatibility bit isn't enough. It causes an error in old files:
```
[10:15]   1.0   zzzNativeVsMz5_ThermoDdaVChromatogramPerformanceTest (en) HDF5-DIAG: Error detected in HDF5 (1.8.7) thread 10508:
#000: C:\pwiz.git\pwiz\libraries\hdf5-1.8.7\src\H5D.c line 334 in H5Dopen2(): not found
major: Dataset
minor: Object not found
#001: C:\pwiz.git\pwiz\libraries\hdf5-1.8.7\src\H5Gloc.c line 430 in H5G_loc_find(): can't find object
major: Symbol table
minor: Object not found
#002: C:\pwiz.git\pwiz\libraries\hdf5-1.8.7\src\H5Gtraverse.c line 905 in H5G_traverse(): internal path traversal failed
major: Symbol table
minor: Object not found
#003: C:\pwiz.git\pwiz\libraries\hdf5-1.8.7\src\H5Gtraverse.c line 688 in H5G_traverse_real(): traversal operator …
```

Revert "[mz5] fixed typo in data set ChromatogramTime"

---

pwiz/analysis/spectrum_processing/SpectrumListFactory.cpp
pwiz/analysis/spectrum_processing/SpectrumListFactoryTest.cpp
pwiz/analysis/spectrum_processing/SpectrumList_Filter.cpp
pwiz/analysis/spectrum_processing/SpectrumList_Filter.hpp
pwiz/analysis/spectrum_processing/ThresholdFilter.cpp
pwiz/utility/misc/Filesystem.cpp
pwiz/utility/misc/FilesystemTest.cpp
pwiz/utility/misc/SHA1.cpp
pwiz_aux/msrc/utility/vendor_api/Shimadzu/ShimadzuReader.cpp

- changed ScanTime filter to stop enumerating by default after the upper end of the time range is reached; new assumeSorted parameter can disable that optimization, but it's not yet accessible in msconvert(GUI)
- fixed excessive memory usage of 64-bit SHA1 calculation
- fixed abbreviate_byte_size not printing decimal dot (used by msbenchmark to report memory usage for example)
- optimized performance of thresholding filter for 3-array ion mobility data
- fixed Shimadzu reader for files with invalid date (apologies if you collected your data in the middle ages or after the year 10000)
@brendanx67 I expect this will be merged to master today or tomorrow. It's been sitting on my drive for weeks. Shouldn't affect Skyline.

Various pwiz core fixes

---

pwiz_tools/Skyline/Controls/Graphs/AllChromatogramsGraph.cs

I believe that this change will fix the intermittent failure in TestManageResults.
If two status updates come in at the same time for the same file, then we would create two FileProgress controls. Also, we would throw a "item with the same key already added" exception, and that would get displayed as an import failure error.
(This error was made possible between the work I did to make the AllChromatogramsGraph a little faster when importing thousands of files at once: the controls get added to flowFileStatus with one "AddRange" call instead of one at a time. The fact that I moved the adding to "_fileProgressControls" made it possible to create controls for the same URI more than once, but it could only happen if we were processing two statuses for the same URI in the same batch, which I …

Fix intermittent failure in TestManageResults

---

pwiz/data/msdata/SpectrumWorkerThreads.cpp
pwiz/utility/misc/Filesystem.cpp
pwiz/utility/misc/Filesystem.hpp
pwiz_tools/commandline/msconvert.cpp

- disabled multi-thread spectrum reading for msconvert on Wine
- added warning in msconvert about converting multiple files at a time on Wine
* created running_on_wine() function

Wine fixes

---

pwiz_tools/Skyline/Controls/SeqNode/PeptideFormatter.cs
pwiz_tools/Skyline/Model/DisplayModificationOption.cs
pwiz_tools/Skyline/Test/CreateTextSequencesTest.cs
pwiz_tools/Skyline/Test/Test.csproj

Neutral-loss-only modifications do not get displayed in the targets tree if the DisplayModificationOption is either "NOT_SHOWN" or "MASS_DELTA".
Amino acids that are both heavy and statically modified should be displayed with the heavy font color, and both bold and underlined.

Fix display of modifications in the Targets tree.

---

pwiz_tools/Skyline/Model/Lib/Midas/MidasBlibBuilder.cs
pwiz_tools/Skyline/Model/Results/IonMobilityFinder.cs
pwiz_tools/Skyline/Model/Results/SpectrumFilter.cs
pwiz_tools/Skyline/Model/SrmDocument.cs
pwiz_tools/Skyline/Model/TransitionGroupDocNode.cs
pwiz_tools/Skyline/TestFunctional/PrositSkylineIntegrationTest.cs

Fix looking up of ion mobilities in libraries when the precursor has heavy modifications.

Fix looking up of ion mobilities in libraries

---

pwiz_tools/Skyline/CommandLine.cs
pwiz_tools/Skyline/Properties/Resources.Designer.cs
pwiz_tools/Skyline/Properties/Resources.resx
pwiz_tools/Skyline/Skyline.cs
pwiz_tools/Skyline/Util/PanoramaUtil.cs

Display Skyline document import progress percent, if reported by Panorama server.  Reduce frequency of pipeline job status check requests to the server.

Display Skyline document import progress

---

libraries/expat.jam
pwiz_tools/BiblioSpec/src/BuildParser.cpp
pwiz_tools/BiblioSpec/src/Jamfile.jam
pwiz_tools/BiblioSpec/src/PepXMLreader.cpp
pwiz_tools/BiblioSpec/src/ProteinPilotReader.cpp
pwiz_tools/BiblioSpec/src/ProteinPilotReader.h
pwiz_tools/BiblioSpec/src/saxhandler.cpp
pwiz_tools/BiblioSpec/src/saxhandler.h

- fixed progress indication when reading large ProteinPilot group.xml files
* fixed saxhandler::getCurrentByteIndex() for large file sizes
* fixed some compile warnings in BiblioSpec

Fix BiblioSpec ProteinPilot group.xml progress indication

---

pwiz_tools/BiblioSpec/src/TSVReader.cpp
pwiz_tools/BiblioSpec/src/TSVReader.h

Tested in Skyline, looks good.

- fixed product m/z values for OpenSWATH assay input to BiblioSpec

---

pwiz/data/msdata/Serializer_MSn.cpp

- added nativeID field (as an 'I' entry) for ms1 and ms2 formats
- fixed ms1/ms2 format scan numbers defaulting to 0 instead of index for nativeID formats that can't translate to scan numbers

MSn format nativeID and scan number fix

---

pwiz/utility/misc/cpp_cli_utilities.hpp
pwiz_aux/msrc/utility/vendor_api/thermo/RawFile.cpp

- fixed crash in Thermo 64-bit reader when asking for centroids on an empty profile ITMS scan (the scan could have data points but they were all zero)
@brendanx67 This could theoretically affect Skyline, if anybody uses ITMS for quant in Skyline. :) Want it in 19.2?

Thermo centroiding of profile ITMS fix

---

pwiz_tools/Skyline/Model/SkypFile.cs
pwiz_tools/Skyline/TestFunctional/SkypTest.cs
pwiz_tools/Skyline/ToolsUI/ToolOptionsUI.cs

If the skyline document that a skyp file points to requires login on the Panorama server, and the server is not configured in Skyline, let the user add the Panorama server and try to download and open the file again.

Skyp: add Panorama server and open

---

pwiz_tools/Skyline/TestFunctional/AssayLibraryImportTest.cs

I think the test might be failing because AllowAllIonTypes was changing the document without updating the doc variable, so the next WaitForDocumentChange call always completed immediately? What do you think?

Fix AssayLibraryImportTest

---

pwiz_tools/Skyline/Model/Prosit/Models/PrositIntensityModel.cs
pwiz_tools/Skyline/TestConnected/PrositConnectionTest.cs
pwiz_tools/Skyline/TestFunctional/PrositSkylineIntegrationTest.cs

- Fix tests to use Models.First() instead of text literal names

Skyline: Change spectrum model to the one requested by Tobi S.

---

pwiz_tools/Skyline/SkylineNightly/Nightly.cs
pwiz_tools/Skyline/SkylineTester/CreateZipInstallerWindow.cs

* fixed error extracting SkylineTester.zip since adding Reader_Shimadzu_Test's file with Japanese characters in the filename; **tested manually with SkylineNightly (after some fiddling to make it use a local copy of the zip file)**
If you approve Brendan I'll cherry pick over to 19.2 as well.

* fixed error extracting SkylineTester.zip

---

pwiz/data/vendor_readers/Thermo/SpectrumList_Thermo.cpp
pwiz/utility/misc/Exception.hpp

- fixed stack overflow in Reader_Agilent_Test built under debug mode (caused by an assert in automation_vector destructor throwing in CrtReportHook which caused another assert, and so on)
* fixed a thread safety issue with Thermo precursorCache_
I found the Thermo thread safety issue while working on the FAIMS test failure but I doubt it fixes that failure because Skyline isn't using multi-threaded calls to a single SpectrumList.

- fixed stack overflow in Reader_Agilent_Test built under debug mode

---

pwiz/utility/bindings/CLI/common/ParamTypes.hpp
pwiz/utility/bindings/CLI/common/ParamTypesTest.cpp
pwiz/utility/bindings/CLI/common/unit.hpp

* added try/catch forwarding to UserParamValue casts to make its error handling as robust as CVParamValue's
* added UserParam and error handling tests in ParamTypesTest
* changed unit_assert_throws_what() to check for substring instead of exact string match

CLI binding UserParam improvements

---

pwiz/analysis/spectrum_processing/SpectrumList_ScanSummer.cpp
pwiz/analysis/spectrum_processing/SpectrumList_ScanSummerTest.cpp

- fixed scan summer filter to drop extra binary arrays with the same size as the default arrays (we assume that the extra array is supposed to have a one-to-one correspondence which would no longer be valid after summing)

- fixed scan summer filter to drop extra binary arrays

---

pwiz_tools/Skyline/TestPerf/PerfDecoysMatchTest.cs

When verifying that the decoy chromatograms are correct, skip over any peptides whose precursor m/z is greater than 900, since those peptides will no longer have any chromatograms since the spectra are now being treated as SIM scans.

Fix DecoysMatchTest.

---

pwiz_tools/Skyline/Skyline.csproj

This option was (presumably accidentally) turned off on 20180904.
Turning off optimization results in a .exe which is 790KB larger (5.4%) and a .pdb which is 2.1MB larger (12%).

Turn on optimization on Skyline-Daily.exe in Release.

---

pwiz_tools/Skyline/Jamfile.jam
pwiz_tools/Skyline/TestRunner/Program.cs

* added TestPass1Subset test in Skyline's Jamfile so pass1 gets some testing on TeamCity
* made TestInstrumentInfo, one of the TestPass1Subset tests, a ReportLeakEarly test so that code path gets tested on TeamCity
@brendanx67 Adding TestInstrumentInfo to the LeakCheckIterationsOverrideByTestName dictionary with ReportLeakEarly changes behavior a bit (if that test starts leaking), but I figure this is acceptable for the benefit of getting some pass1 testing on TeamCity?

* fixed logging crash in TestRunner from PR #900

---

pwiz/analysis/common/CwtPeakDetector.hpp
pwiz/analysis/common/LocalMaximumPeakDetector.hpp
pwiz/analysis/common/PeakDetector.hpp
pwiz/analysis/spectrum_processing/SpectrumListFactory.cpp
pwiz/analysis/spectrum_processing/SpectrumList_ChargeFromIsotope.cpp
pwiz/analysis/spectrum_processing/SpectrumList_PeakPicker.cpp
pwiz/analysis/spectrum_processing/SpectrumList_PeakPicker.hpp
pwiz/analysis/spectrum_processing/SpectrumList_ScanSummer.cpp
pwiz/analysis/spectrum_processing/SpectrumList_ScanSummer.hpp
pwiz/analysis/spectrum_processing/SpectrumList_ScanSummerTest.cpp
pwiz/data/msdata/Jamfile.jam
pwiz/data/msdata/SpectrumListBase.cpp
pwiz/data/msdata/SpectrumListBase.hpp
pwiz/data/vendor_readers/Agilent/ChromatogramList_Agilent.cpp
pwiz/utility/misc/BinaryDataTest.cpp
pwiz/utility/misc/Container.hpp
pwiz_aux/msrc/utility/vendor_api/Agilent/MassHunterData.cpp
pwiz_aux/msrc/utility/vendor_api/Agilent/MassHunterData.hpp
pwiz_aux/msrc/utility/vendor_api/Agilent/MidacData.cpp
pwiz_aux/msrc/utility/vendor_api/Agilent/MidacData.hpp
pwiz_aux/msrc/utility/vendor_api/Bruker/TimsData.cpp
pwiz_tools/MSConvertGUI/MainForm.Designer.cs
pwiz_tools/MSConvertGUI/MainForm.cs
pwiz_tools/MSConvertGUI/MainForm.resx

- added sumMs1 option to scanSumming filter, useful for getting Agilent and Waters data with combineIonMobilitySpectra back to the pre-3-array state (mobility array is dropped, near-identical m/z values at different mobilities have their intensities summed)
- added warning message when vendor centroiding requested but not available
* added PeakDetector::name() to allow implementations a descriptive string which SpectrumList_PeakPicker will now put in a UserParam
* fixed SpectrumListBase::warn_once() to be thread-safe
* refactored places still using automation_vector in Agilent readers to use BinaryData
* factored out TimsData::getCombinedSpectrumData()'s SortByOther to pwiz::util::sort_together(), also used by SpectrumList_ScanSummer (CONSIDER: an internal Spectrum property that tracks …

- added sumMs1 option to scanSumming filter

---

pwiz_tools/Skyline/SkylineNightly/LogFileMonitor.cs
pwiz_tools/Skyline/SkylineNightly/Nightly.cs
pwiz_tools/Skyline/SkylineNightly/SkylineNightly.csproj
pwiz_tools/Skyline/SkylineTester/SkylineTester.csproj
pwiz_tools/Skyline/SkylineTester/TabNightly.cs

If SkylineNightly detects a hang, it will change SkylineTester's end time to 12pm to allow extra time for someone to debug.

SkylineNightly: extend duration if hang detected

---

pwiz/analysis/common/ExtraZeroSamplesFilter.cpp
pwiz/analysis/common/ExtraZeroSamplesFilter.hpp
pwiz/data/vendor_readers/Bruker/SpectrumList_Bruker.cpp
pwiz_aux/msrc/utility/vendor_api/Bruker/Baf2Sql.cpp
pwiz_aux/msrc/utility/vendor_api/Bruker/Baf2Sql.hpp
pwiz_aux/msrc/utility/vendor_api/Bruker/CompassData.cpp
pwiz_aux/msrc/utility/vendor_api/Bruker/CompassData.hpp
pwiz_aux/msrc/utility/vendor_api/Bruker/TimsData.cpp
pwiz_aux/msrc/utility/vendor_api/Bruker/TimsData.hpp

- fixed Bruker BAF returning empty spectra when combineIonMobilitySpectra is on (the default mode in Skyline and SeeMS)
* added ExtraZeroSamplesFilter::count_non_zeros(); tried using it (along with remove_zeros()) for Bruker profile spectra when config_.ignoreZeroIntensityPoints is off, but it didn't help as much as I expected due to lack of baseline removal in Bruker profile spectra
* refactored Bruker reader to use BinaryData instead of automation_vector which will avoid an extra copy of the unmanaged arrays
Sorry about this dropping off the radar @nickshulman .
@brendanx67 This certainly needs to be cherry picked over to 20.1, I'll do that as soon as tests pass.

Fix Bruker BAF returning empty spectra

---

pwiz_tools/Skyline/Model/MemoryDocumentContainer.cs

This code succeeded in running command-line tests that hung usually within a few hundred test runs for over 2500 runs. The primary cause seemed to be overwriting a final multi-status with a non-final multi-status, leaving MemoryDocumentContainer.LastProgress with a different idea of the current status than ChromatogramManager.MultiFileLoader.Status.
Other improvements in getting to this solution included never waiting indefinitely to check whether the status was final and a re-ordering in UpdateProgress.

Skyline: Attempt to fix command-line deadlocks in MemoryDocumentContainer

---

pwiz_tools/Skyline/Controls/Graphs/AllChromatogramsGraph.cs
pwiz_tools/Skyline/Skyline.cs
pwiz_tools/Skyline/SkylineGraphs.cs

Sometimes we new ACG but never show it, which means no HWND ever gets created. In the prior code that lead to WaitOne() waiting forever and leaking the thread and the ACG.

Skyline: Attempt fix for ACG.RemoveAsync() causing leak in TestGroupedStudies1Tutorial

---

pwiz_tools/Skyline/Controls/Graphs/AllChromatogramsGraph.cs
pwiz_tools/Skyline/Model/Results/ChromDataProvider.cs
pwiz_tools/Skyline/Model/Results/SpectraChromDataProvider.cs
pwiz_tools/Skyline/Model/Results/SpectrumFilter.cs
pwiz_tools/Skyline/TestPerf/PerfTicAreaTest.cs
pwiz_tools/Skyline/TestPerf/TestPerf.csproj

Make it so that Skyline falls back to the old way of extracting the Total Ion Current chromatogram and calculating the TIC Area if the Tic Chromatogram that is present in the data file is not usable.
It might not be usable if:
1. The chromatogram contains MS2 scans. We don't know for sure whether it contains MS2 scans, but the heuristic is that if the point count in the TIC chromatogram is more than 1/2 (number chosen because of typical MSe data) as large as the total spectrum count, we don't use it.
2. The chromatogram has zero points in it. This can happen if all of the spectra in the .raw file were marked as SIM spectra.
The logic for this is in GlobalChromatogramExtractor.IsTicChromatogramUsable

Fix calculation of TIC Area 

---

pwiz_tools/Skyline/Model/Results/ChromDataProvider.cs

Make the threshold number of points at which we do not trust the TIC chromatogram half of the total number of scans.
This is because demultiplexing doubles the number of scans, so a chromatogram with half of the total scans in a demultiplexed file probably contains MS2 scans.

Fix PerfTicAreaTest.

---

pwiz_tools/Skyline/Model/Prosit/Models/PrositModel.cs
pwiz_tools/Skyline/SkylineGraphs.cs
pwiz_tools/Skyline/ToolsUI/ToolOptionsUI.cs

- Prosit integration made it available always, but switched back to only when document has libraries or Prosit is enabled

Skyline (20.1): Fix Library Match view visibility and availability for Prosit

---

pwiz_tools/Skyline/Controls/Graphs/GraphSpectrum.cs
pwiz_tools/Skyline/Controls/PrositUIHelpers.cs
pwiz_tools/Skyline/Model/Lib/Library.cs
pwiz_tools/Skyline/Model/Prosit/Models/PrositModel.cs
pwiz_tools/Skyline/ToolsUI/ToolOptionsUI.cs

- Failure to annotate fragment ions in heavy labeled Prosit predicted spectra
- Failure to match m/z values between heavy labeled library spectra and Prosit mirror plot spectra
- Mistake in parenting ToolOptionsUI when shown as a result of CheckPrositSettings
- Fix canceling of PrositPingRequest during closing of ToolOptionsUI

Skyline (20.1): Fixes to Prosit integration

---

pwiz_tools/Skyline/Controls/Graphs/GraphSpectrum.cs
pwiz_tools/Skyline/Controls/PrositUIHelpers.cs
pwiz_tools/Skyline/Model/Lib/Library.cs
pwiz_tools/Skyline/Model/Prosit/Models/PrositModel.cs
pwiz_tools/Skyline/ToolsUI/ToolOptionsUI.cs

- Failure to annotate fragment ions in heavy labeled Prosit predicted spectra
- Failure to match m/z values between heavy labeled library spectra and Prosit mirror plot spectra
- Mistake in parenting ToolOptionsUI when shown as a result of CheckPrositSettings
- Fix canceling of PrositPingRequest during closing of ToolOptionsUI

Skyline: Fixes to Prosit integration (#989)

---

pwiz_tools/Skyline/Controls/Graphs/AllChromatogramsGraph.Designer.cs
pwiz_tools/Skyline/Controls/Graphs/AllChromatogramsGraph.cs

Trying to track down intermittent failures "Dispose" cannot be called during "CreateHandle".

Add logging code to AllChromatogramsGraph.CreateHandle

---

pwiz_tools/Skyline/Controls/Graphs/AreaCVToolbar.cs
pwiz_tools/Skyline/SkylineGraphs.cs
pwiz_tools/Skyline/TestFunctional/AreaCVHistogramTest.cs

1. ArgumentNullException if trying to group on a property where some of the replicates have null values.
2. Unable to group on values that are not strings.
3. InvalidOperationException if document contains zero PeptideTransitionGroups.

Fix some bugs in AreaCVHistogram:

---

pwiz_tools/Skyline/TestFunctional/LibraryBuildTest.cs

- Make sure the library file exists before checking for completed library building

Skyline: Attempt to fix TestLibraryBuild failure on fast machine in nightly test runs

---

pwiz_tools/Skyline/SettingsUI/ViewLibraryDlg.Designer.cs
pwiz_tools/Skyline/SettingsUI/ViewLibraryDlg.resx

(A fix was made after visual freeze to the 20.1 branch to hide this checkbox programmatically. That fix never got ported over to master. This change removes the checkbox completely).

Remove "Prosit" checkbox from Spectral Library Viewer.

---

pwiz/data/msdata/SpectrumListBase.cpp
pwiz/data/msdata/SpectrumListBase.hpp
pwiz/data/vendor_readers/Thermo/Reader_Thermo.cpp
pwiz/data/vendor_readers/Thermo/SpectrumList_Thermo.cpp
pwiz/data/vendor_readers/Thermo/SpectrumList_Thermo.hpp
pwiz_aux/msrc/utility/vendor_api/thermo/RawFile.cpp

- fixed reading Thermo RAW from an unknown MS instrument model and a PDA detector (the PDA instrumentConfiguration was being picked as the default)
- fixed errors reading Thermo RAW when calling GetTrailerExtraValue on non-MS controllers
* changed warn_once to hash string contents instead of pointer
* moved MultiFill userParam from Precursor to Scan element

Fix reading Thermo RAW w/ PDA from an unknown MS instrument model 

---

pwiz_tools/Skyline/Alerts/ReportErrorDlg.cs
pwiz_tools/Skyline/Alerts/ReportShutdownDlg.cs
pwiz_tools/Skyline/Controls/Graphs/FileProgressControl.cs
pwiz_tools/Skyline/TestUtil/AssertEx.cs
pwiz_tools/Skyline/Util/Util.cs

It used to walk up the chain of InnerException objects, but would lose information for some exception types such as AggregateException.
(also, rename that method to "GetExceptionText")

Change ExceptionUtil.GetStackTraceText so that it just uses "exception.ToString()"

---

pwiz/data/vendor_readers/Thermo/SpectrumList_Thermo.cpp
pwiz_aux/msrc/utility/vendor_api/thermo/RawFile.cpp

- fixed Thermo reader to use isolation width from RawFile's precursor info (previously it was only using trailer extra value or default isolation width from instrument method)
- added support for capturing default isolation width from instrument method variable like "Isolation Window (m/z) = "

- fixed Thermo reader isolation width

---

pwiz_tools/BiblioSpec/src/MaxQuantReader.cpp

Fix bug where MaxQuantReader fails to parse file if it is missing both optional columns "Labeling State" and "Evidence ID".
(Reported by marie locard-paulet)
https://skyline.ms/announcements/home/support/thread.view?rowId=46588
The code was exiting the loop as soon as it found the first missing optional column, and so a column remained in the list whose position was "-1".

Fix MaxQuantReader bug 

---

pwiz_tools/Skyline/CommandArgs.cs
pwiz_tools/Skyline/CommandLine.cs
pwiz_tools/Skyline/Model/DocNode.cs
pwiz_tools/Skyline/Model/RefinementSettings.cs
pwiz_tools/Skyline/Properties/Resources.Designer.cs
pwiz_tools/Skyline/Properties/Resources.resx
pwiz_tools/Skyline/TestData/CommandLineRefineTest.cs
pwiz_tools/Skyline/TestData/CommandLineTest.cs

- CommandLine support for --decoys-discard
- CommandLine support for --refine-cv-remove-above-cutoff with decimal percent <1
- Remove based on CV cutoff removes empty peptides
- Refinement based on CV and GC can still remove proteins based on remaining peptide count

Skyline: Fixes motivated by issues found in May Institute webinars

---

pwiz_tools/Skyline/Model/DocSettings/AbsoluteQuantification/QuantificationResult.cs
pwiz_tools/Skyline/TestFunctional/SingleReplicateResponseCurveTest.cs

It was showing up as #N/A.
Reported by Brendan
Also fixed in 20.1 branch.

Fix implementation of QuantificationResult.ToString().

---

pwiz_tools/Skyline/Model/DocSettings/AbsoluteQuantification/QuantificationResult.cs
pwiz_tools/Skyline/TestFunctional/SingleReplicateResponseCurveTest.cs

It was showing up as "#N/A" even though the concentration had been calculated.
(Reported by Brendanx)

Fix display of "Quantification Result" column in Document Grid.

---

pwiz/data/vendor_readers/Shimadzu/ChromatogramList_Shimadzu.cpp
pwiz/data/vendor_readers/Shimadzu/Reader_Shimadzu_Test.data/10nmol_Negative_MS_ID_ON_055-centroid.mzML
pwiz/data/vendor_readers/Shimadzu/Reader_Shimadzu_Test.data/10nmol_Negative_MS_ID_ON_055.mzML
pwiz/data/vendor_readers/Thermo/Reader_Thermo.cpp
pwiz/utility/minimxml/SAXParser.cpp
pwiz_aux/msrc/utility/vendor_api/Shimadzu/ShimadzuReader.cpp
pwiz_aux/msrc/utility/vendor_api/thermo/RawFile.cpp
pwiz_tools/SeeMS/Types.cs

- fixed Shimadzu TIC chromatogram time values being converted to frac…tions of seconds rather than seconds, and fixed the cvParam's units from minutes to seconds
- fixed thread safety issue with Thermo 64-bit reader which resulted in strange behavior for files with non-MS controllers
- fixed SeeMS chromatogram graphs to show time units and adjust based on the View/Time in Minutes option

Fix Shimadzu TIC chromatogram time values

---

pwiz_tools/BiblioSpec/src/LibReader.cpp
pwiz_tools/BiblioSpec/src/LibReader.h

- fixed BlibToMs2 to not warn when converting non-redundant blib files (before recent BlibFilter changes, BlibFilter output had spectrum ids renumbered to be contiguous, but that is no longer the case)

- fixed BlibToMs2 to not warn when converting non-redundant blib

---

pwiz_tools/Bumbershoot/idpicker/Forms/IDPickerForm.cs
pwiz_tools/Bumbershoot/idpicker/Forms/NewVersionForm.Designer.cs
pwiz_tools/Bumbershoot/idpicker/Forms/NewVersionForm.resx
pwiz_tools/Bumbershoot/idpicker/Forms/SpectrumTableForm.cs
pwiz_tools/Bumbershoot/idpicker/Util/Path.cs

- IDPicker: fixed IndexOutOfRange error when expanding row in spectrum view to PSM list when data filter includes protein group, gene, or gene group
- IDPicker: improved error feedback in LocateSpectrumSource
* IDPicker: hid Show Change Log button since it's not currently working

- IDPicker: fixed IndexOutOfRange error when expanding row

---

pwiz/data/vendor_readers/Thermo/SpectrumList_Thermo.cpp
pwiz/data/vendor_readers/Thermo/SpectrumList_Thermo.hpp
pwiz_aux/msrc/utility/vendor_api/thermo/RawFile.cpp
pwiz_aux/msrc/utility/vendor_api/thermo/RawFile.h
pwiz_tools/examples/msbenchmark.cpp

- added support for assigning precursor spectrum by checking the "Master Scan" header item
- fixed precursor spectrum heuristic to check that isolation m/z is within the precursor spectrum's scan window(s)
- added simAsSpectra and srmAsSpectra options to msbenchmark
* added valueIfMissing parameters for RawFile::getTrailerExtraValue*() functions; will switch to use these instead of try/catch later

Improve Thermo finding precursor spectrum heuristic and enable using Master Scan

---

pwiz_tools/Skyline/Model/AuditLog/EnumNames.Designer.cs
pwiz_tools/Skyline/Model/AuditLog/EnumNames.resx
pwiz_tools/Skyline/TestTutorial/TutorialAuditLogs/en/TestDiaQeFullSearchTutorial.log
pwiz_tools/Skyline/TestTutorial/TutorialAuditLogs/en/TestDiaQeTutorial.log
pwiz_tools/Skyline/TestTutorial/TutorialAuditLogs/en/TestDiaTtofFullSearchTutorial.log
pwiz_tools/Skyline/TestTutorial/TutorialAuditLogs/en/TestDiaTtofTutorial.log
pwiz_tools/Skyline/TestTutorial/TutorialAuditLogs/en/TestDriftTimePredictorTutorial.log
pwiz_tools/Skyline/TestTutorial/TutorialAuditLogs/en/TestHiResMetabolomicsTutorial.log
pwiz_tools/Skyline/TestTutorial/TutorialAuditLogs/en/TestTargetedMSMSTutorial.log
pwiz_tools/Skyline/TestTutorial/TutorialAuditLogs/en/TestTargetedMSMSTutorialAsSmallMoleculeMasses.log
pwiz_tools/Skyline/TestTutorial/TutorialAuditLogs/en/TestTargetedMSMSTutorialAsSmallMolecules.log
pwiz_tools/Skyline/TestTutorial/TutorialAuditLogs/fr/TestDiaQeFullSearchTutorial.log
pwiz_tools/Skyline/TestTutorial/TutorialAuditLogs/fr/TestDiaQeTutorial.log
pwiz_tools/Skyline/TestTutorial/TutorialAuditLogs/fr/TestDiaTtofFullSearchTutorial.log
pwiz_tools/Skyline/TestTutorial/TutorialAuditLogs/fr/TestDiaTtofTutorial.log
pwiz_tools/Skyline/TestTutorial/TutorialAuditLogs/fr/TestDriftTimePredictorTutorial.log
pwiz_tools/Skyline/TestTutorial/TutorialAuditLogs/fr/TestHiResMetabolomicsTutorial.log
pwiz_tools/Skyline/TestTutorial/TutorialAuditLogs/fr/TestTargetedMSMSTutorial.log
pwiz_tools/Skyline/TestTutorial/TutorialAuditLogs/fr/TestTargetedMSMSTutorialAsSmallMoleculeMasses.log
pwiz_tools/Skyline/TestTutorial/TutorialAuditLogs/fr/TestTargetedMSMSTutorialAsSmallMolecules.log
pwiz_tools/Skyline/TestTutorial/TutorialAuditLogs/tr/TestDiaQeFullSearchTutorial.log
pwiz_tools/Skyline/TestTutorial/TutorialAuditLogs/tr/TestDiaQeTutorial.log
pwiz_tools/Skyline/TestTutorial/TutorialAuditLogs/tr/TestDiaTtofFullSearchTutorial.log
pwiz_tools/Skyline/TestTutorial/TutorialAuditLogs/tr/TestDiaTtofTutorial.log
pwiz_tools/Skyline/TestTutorial/TutorialAuditLogs/tr/TestDriftTimePredictorTutorial.log
pwiz_tools/Skyline/TestTutorial/TutorialAuditLogs/tr/TestHiResMetabolomicsTutorial.log
pwiz_tools/Skyline/TestTutorial/TutorialAuditLogs/tr/TestTargetedMSMSTutorial.log
pwiz_tools/Skyline/TestTutorial/TutorialAuditLogs/tr/TestTargetedMSMSTutorialAsSmallMoleculeMasses.log
pwiz_tools/Skyline/TestTutorial/TutorialAuditLogs/tr/TestTargetedMSMSTutorialAsSmallMolecules.log

"Use only scans withing time frame of MS/MS IDs" -> "Use only scans within time frame of MS/MS IDs"
and
"Use only scans withing time frame of predicted RT" -> "Use only scans within time frame of predicted RT"

Fix a couple of typos in audit logging:

---

pwiz_tools/Skyline/Model/Lib/LibraryKey.cs
pwiz_tools/Skyline/Model/Results/SpectrumFilter.cs
pwiz_tools/Skyline/SettingsUI/ViewLibraryDlg.cs
pwiz_tools/Skyline/Test/CrosslinkSequenceParserTest.cs

Fix some problems with invalid peptide crosslink sequences:
1. If there are more than one crosslink between a pair of peptides, make sure that Skyline reports that as not supported (reported by Yu)
2. Fix exceptions that happen hovering over crosslinked peptides with unmatched modifications in Spectral Library viewer.
Also:
3. Fix NullReferenceException using Triggered Acquisition in small molecule document (reported by jrenders)

Fixes related to invalid crosslinked peptides

---

pwiz_tools/Skyline/Executables/SkylineRunner/Program.cs
pwiz_tools/Skyline/Executables/SkylineRunner/Properties/Resources.Designer.cs
pwiz_tools/Skyline/Executables/SkylineRunner/Properties/Resources.resx

Problem reported by Sonnet Davis.  Skyline was installed in the expected location but SkylineRunner (via AutoQC Loader) would exit with the following error:
Error: Could not connect to Skyline.
Make sure you have a valid Skyline installation.
SkylineRunner sometimes takes longer than 5s to connect to the named pipe in WaitForConnection().  Increasing the timeout fixed the problem.

SkylineRunner: Increase wait timeout for connecting to Skyline

---

pwiz_tools/Skyline/FileUI/PublishDocumentDlg.cs
pwiz_tools/Skyline/Properties/Resources.Designer.cs
pwiz_tools/Skyline/Properties/Resources.resx

PublishDocumentDlg displays a list of configured Panorama servers along with a tree view of the folders on each server where the user can upload Skyline documents.  If an error occurs while querying the list for folders on a server (e.g. the user could not be authenticated with the saved username and password) the underlying error is not displayed to the user.

Skyline: Display underlying error if an exception occurs while getting a list of folders from a Panorama server

---

pwiz_tools/Skyline/Util/PanoramaUtil.cs

Call LabKey's AdminController.HealthCheckAction instead of ProjectController.GetContainersAction which does not return the expected JSON key if the "Home" container on the server is not public (https://www.labkey.org/home/Developer/issues/Secure/issues-details.view?issueId=20686).

Skyline: Fix IsPanorama() server check

---

pwiz_tools/Skyline/TestFunctional/DdaSearchTest.cs

This change disables the asserts that are failing in TestDdaSearch on 32 bit TeamCity.
The rest of the test still runs as normal.

Disable the part of TestDdaSearch that is intermittently failing on 32 bit TeamCity.

---

pwiz_tools/Skyline/Model/Databinding/Entities/PeptideResult.cs
pwiz_tools/Skyline/Model/Databinding/Entities/Precursor.cs
pwiz_tools/Skyline/Model/Databinding/Entities/PrecursorResult.cs
pwiz_tools/Skyline/Model/Databinding/SkylineViewContext.cs
pwiz_tools/Skyline/Model/DocSettings/AbsoluteQuantification/CalibrationCurveFitter.cs
pwiz_tools/Skyline/Model/DocSettings/AbsoluteQuantification/FiguresOfMerit.cs
pwiz_tools/Skyline/Model/DocSettings/AbsoluteQuantification/QuantificationResult.cs
pwiz_tools/Skyline/Model/GroupComparison/PeptideQuantifier.cs
pwiz_tools/Skyline/TestFunctional/QualitativeIonRatioTest.cs
pwiz_tools/Skyline/TestFunctional/SingleReplicateResponseCurveTest.cs

It used to be on the PeptideResult, but based on user feedback, it needs to be a precursor level value.
(Reported by Jeffrey)

Move QualitativeIonRatio to the PrecursorResult.

---

pwiz_tools/Skyline/Model/Databinding/Entities/PeptideResult.cs
pwiz_tools/Skyline/Model/Databinding/Entities/Precursor.cs
pwiz_tools/Skyline/Model/Databinding/Entities/PrecursorResult.cs
pwiz_tools/Skyline/Model/Databinding/SkylineViewContext.cs
pwiz_tools/Skyline/Model/DocSettings/AbsoluteQuantification/CalibrationCurveFitter.cs
pwiz_tools/Skyline/Model/DocSettings/AbsoluteQuantification/FiguresOfMerit.cs
pwiz_tools/Skyline/Model/DocSettings/AbsoluteQuantification/QuantificationResult.cs
pwiz_tools/Skyline/Model/GroupComparison/PeptideQuantifier.cs
pwiz_tools/Skyline/TestFunctional/QualitativeIonRatioTest.cs
pwiz_tools/Skyline/TestFunctional/SingleReplicateResponseCurveTest.cs

Move QualitativeIonRatio to the PrecursorResult.
It used to be on the PeptideResult, but based on user feedback, it needs to be a precursor level value.
(Reported by Jeffrey)

Move QualitativeIonRatio to the PrecursorResult. (#1191)

---

pwiz_tools/Skyline/Executables/Installer/SkylineInstaller/Product.wxs
pwiz_tools/Skyline/Model/DdaSearch/MSAmandaSearchWrapper.cs
pwiz_tools/Skyline/Skyline.csproj
pwiz_tools/Skyline/TestFunctional/DdaSearchTest.cs

* fixed publish category for enzymes.xml and Instruments.xml (defaulted to Data File, overrode them to Include)
* fixed missing MSAmanda dependencies giving NRE instead of sensible error message
* removed Method\Bruker\BDal.Submethod.Wrapper.xml from Skyline project since it's an XMLDOC file for the corresponding assembly

* fixed publish category for enzymes.xml and Instruments.xml

---

pwiz_tools/Skyline/TestFunctional/PasteMoleculesTest.cs

The expected row count is 32 (since the view gets changed to include some Transition columns), but the test usually succeeds because the number of rows is initially 16, and never notices that the row count is wrong.
This test has been intermittently failing since April 2019.

Fix intermittent failure in PasteMoleculesTest.

---

pwiz_tools/Skyline/FileUI/PeptideSearch/DDASearchControl.cs
pwiz_tools/Skyline/FileUI/PeptideSearch/ImportPeptideSearchDlg.cs
pwiz_tools/Skyline/Model/DdaSearch/MSAmandaSearchWrapper.cs
pwiz_tools/Skyline/TestFunctional/DdaSearchTest.cs

- fixed non-Unimod mods causing errors in MSAmanda
- fixed error caused by going back from DDA settings page to spectra page, changing input files, and forward again
* fixed search engine UIUpdate not connecting after the first time the DDASearchControl is shown
* added test for canceling search, adding another spectrum file, and starting search again
@brendanx67 I assume you'll want these in 20.2 as well?

MSAmanda fixes

---

pwiz_tools/Skyline/Model/Lib/BiblioSpecLite.cs

A user reported an exception (in Skyline 20.1) where they were getting a NullReferenceException in BiblioSpecLiteLibrary.AddAlignedRetentionTimes.
https://skyline.ms/announcements/home/issues/exceptions/thread.view?rowId=48174  
The files necessary to reproduce this bug are here:
/net/maccoss/vol6/home/nicksh/bugs/AddIrtsNullReference
This seems to happen if Skyline successfully gets a retention time alignment between two runs, but then Skyline is unable to refine the regression enough to get past the R-squared threshold.
I believe the correct fix is to not try to align the retention times in this case, and just use the original times.
I could imagine that the fix might be to use fileAlignments.Regression if fileAlignments.RegressionRefined is null, but that's probably not a good thing do …

Fix exception in Import Peptide Search if regression has failed

---

pwiz_tools/Skyline/Skyline.Designer.cs
pwiz_tools/Skyline/Skyline.resx

This reverts the recent changes to Skyline.resx that came from a high resolution monitor.
There are still two other forms that set "ImageScalingSize" in them:
EditIrtCalcDlg.Designer.cs
DetectionsToolbar.Designer.cs
I imagine that these two should only get fixed in master, not 20.2.
With this fix:
Without this fix:

Revert highres changes in Skyline.resx

---

pwiz/data/vendor_readers/Shimadzu/ChromatogramList_Shimadzu.cpp
pwiz/data/vendor_readers/Shimadzu/Reader_Shimadzu_Test.data/20140312_六mix_column_1 (scheduled) 一个试-centroid.mzML
pwiz/data/vendor_readers/Shimadzu/Reader_Shimadzu_Test.data/20140312_六mix_column_1 (scheduled) 一个试.mzML
pwiz_aux/msrc/utility/vendor_api/Shimadzu/Jamfile.jam
pwiz_aux/msrc/utility/vendor_api/Shimadzu/ShimadzuReader.cpp
pwiz_aux/msrc/utility/vendor_api/Shimadzu/ShimadzuReader.hpp
scripts/wix/vendor-dlls.wxs-fragment

- replaced Shimadzu DataReader with IoModule for MRM files as the for…mer was causing debug assertions on some new QTOF files (MRM files will also get TIC chromatograms now)
@brendanx67 We should get this in 20.2.

- replaced Shimadzu DataReader with IoModule for MRM files

---

pwiz_tools/Skyline/Controls/Graphs/Calibration/CalibrationForm.cs
pwiz_tools/Skyline/Controls/Graphs/SummaryReplicateGraphPane.cs

NullReferenceException in CalibrationForm.GetFormTitle (reported on 8/31/2020)
ArgumentNullException in SummaryReplicateGraphPane.SetSelectedFile (reported on 9/17/2020)
(reported anonymously on Exception Web).

Fix a couple of exceptions from Exception Web:

---

pwiz_tools/Skyline/Properties/Settings.cs

(thanks to Brendan for noticing this)

override IonMobilityLibraryList.GetDisplayName so that "None" gets localized properly

---

pwiz_tools/Skyline/Properties/Settings.Designer.cs
pwiz_tools/Skyline/Util/Util.cs

When debugging, "Exceptions Settings">"Break When Thrown">(all possible exceptions) is a great way to quickly locate a test exception. Employing exceptions as normal flow of control severely limits that feature's usefulness.
We should always use things like TryParse in favor of Parse when the language provides them. Exceptions should be exceptional.
Also, fix the typo in DetectionGraphType default value that was causing this to trip in the first place.

Skyline: refactor our ParseEnum method to use Enum.TryParse() instead of Enum.Parse() in a try/catch block.

---

pwiz_tools/Skyline/SkylineFiles.cs

This code was originally added in 2012 with a comment relating to stress testing and anti virus.
I could not get any document sharing test to fail even with antivirus enabled and running tests in a loop.
If we do see that some part of the sharing a document might fail, then we could put a TryTwice around a particular step, but it is a not good to put it around the whole process.

Remove "Helpers.TryTwice" around code that shares a Skyline document.

---

pwiz_tools/Skyline/Properties/Settings.Designer.cs
pwiz_tools/Skyline/Properties/Settings.settings

Settings.Designer.cs should never be edited by hand.
Visual Studio generates it from the file Settings.settings whenever Settings.settings is modified.
Visual Studio provides an editor for Settings.settings, but it's sometimes easier to edit the XML in Settings.settings directly.
If you have a complicated setting value type that cannot be represented by the XML in Settings.settings, then you can add the setting to Settings.cs, but never Settings.Designer.cs.
(Also, removed setting "DetectionsFontSize" since it was not being used, and I could not figure out what default value it should have).

Add some things to Settings.settings that had been manually added to Settings.Designer.cs

---

pwiz_aux/msrc/utility/vendor_api/Shimadzu/ShimadzuReader.cpp
pwiz_tools/Shared/ProteowizardWrapper/MsDataFileImpl.cs
pwiz_tools/Skyline/TestData/Results/ShimadzuSrmTest.cs

* fixed MsDataFileImpl.GetChromatogram() to convert time arrays to minutes rather than assuming they're always in minutes
@brendanx67  @nickshulman My first attempt at this got the math wrong, but no tests failed (at least in TestData and TestFunctional, haven't tried TestPerf). Any ideas which test I should augment to check that the time units are correct?

* fixed MsDataFileImpl.GetChromatogram() to convert time arrays to minutes

---

pwiz_aux/msrc/utility/vendor_api/Shimadzu/ShimadzuReader.cpp
pwiz_tools/Shared/ProteowizardWrapper/MsDataFileImpl.cs
pwiz_tools/Skyline/TestData/Results/ShimadzuSrmTest.cs

- fixed MsDataFileImpl.GetChromatogram() to convert time arrays to minutes rather than assuming they're always in minutes
- fixed error caused by calling GetMSSpectrum when the final scan number of an event isn't near the endTime

Fix Shimadzu issues

---

pwiz_tools/Skyline/SettingsUI/IonMobility/EditIonMobilityLibraryDlg.cs
pwiz_tools/Skyline/TestFunctional/IonMobilityTest.cs

…  if the user does not specify otherwise.
Issue was rasied in https://skyline.ms/announcements/home/issues/exceptions/thread.view?rowId=48729
> User comments:
> Came across this error the other week and didn't report it because it didn't seem significant enough but I figure this could be useful for the stable non-daily release.
> 
> If you open or create an ion mobility library file before the "Name" field is completed, this error pops up. I clicked open, thinking the name would be auto-completed and got this error, so others users may encounter this issue too.
>
>Cheers,
>Chris
reported by Chris Ashwood

Skyline: when creating an ion mobility library, use the filename as basis for the library name

---

pwiz_aux/msrc/utility/vendor_api/thermo/RawFile.cpp

- enabled reference and exception peaks in Thermo vendor centroids (one user reported their m/z of interest being mislabeled as an exception peak due to being too close to the lockmass m/z)

- enabled reference and exception peaks in Thermo vendor centroids

---

pwiz_tools/Skyline/Model/Results/MeasuredResults.cs
pwiz_tools/Skyline/SettingsUI/DefineAnnotationDlg.Designer.cs
pwiz_tools/Skyline/SettingsUI/DefineAnnotationDlg.cs
pwiz_tools/Skyline/SettingsUI/DefineAnnotationDlg.resx

1. Fix Issue 753: Value list annotations should not allow empty lists
Also fix order of controls on DefineAnnotationDlg so labels come before their textboxes so that MessageBoxHelper displays the correct name when showing error messages
Add extra information to Duplicate Key exception thrown by MeasuredResults.set_Chromatograms to try to track down exception that keeps getting reported on Exception Web.

DefineAnnotationDlg and MeasuredResults changes

---

pwiz_tools/Skyline/TestData/Results/ThermoQuantTest.cs
pwiz_tools/Skyline/TestPerf/PerfTicAreaTest.cs

1. Change expected values in PerfTicAreaTest. The expected numbers are slightly different because lockmass peaks are now being included in the spectra.
2. Turn off optimization in ThermoQuantTest to get better information about line number of test failure.

Nightly test fixes:

---

pwiz_tools/Skyline/FileUI/PeptideSearch/SearchSettingsControl.cs

:facepalm:
This is causing users to think they are using a wide tolerance for fragment ions (like 1 Da) but it's being treated as 1 ppm if they're using ppm for parent tolerance.

Fix fragment tolerance always using precursor tolerance units

---

pwiz_tools/Skyline/FileUI/PeptideSearch/SearchSettingsControl.cs
pwiz_tools/Skyline/Properties/Resources.Designer.cs
pwiz_tools/Skyline/Properties/Resources.ja.resx
pwiz_tools/Skyline/Properties/Resources.resx
pwiz_tools/Skyline/Properties/Resources.zh-CHS.resx

* moved "fragmentIons not in combo box" message out of resx to an inline verbatim string; it is intended to catch programming errors

Move "fragmentIons not in combo box" message out of resx

---

pwiz_tools/Skyline/Jamfile.jam

* added workaround for first IDE build messing up DLL file copies after a clean quickbuild of Skyline
If you want to build for running in the IDE, use the pwiz_tools/Skyline//Build target.
Tthe existing pwiz_tools/Skyline//Skyline.exe target will continue to leave Skyline files in Release directory.
The Build target will clean them which works around the file copy problem.

Workaround for first IDE build after a clean quickbuild of Skyline

---

pwiz_tools/Skyline/TestSettings_x64-template.testsettings
pwiz_tools/Skyline/TestSettings_x86-template.testsettings

I do not know why this has suddenly stopped working for me, but I can't run tests in the IDE anymore.
I always build Skyline from the commandline with:
quickbuild ..... pwiz_tools/Skyline//Skyline.exe
For some reason, when I do this now, I always fail tests because "prmschduler.dll" and Shimadzu's DataReader.dll have not been copied into the TestResults/.../Out directory
These changes to the testsettings file fix this for me.
(I don't think this has anything to do with recent pull request #1349)

Enable running tests from the IDE.

---

pwiz_tools/Skyline/FileUI/ExportMethodDlg.cs
pwiz_tools/Skyline/Properties/Resources.Designer.cs
pwiz_tools/Skyline/Properties/Resources.resx
pwiz_tools/Skyline/SettingsUI/EditCustomMoleculeDlg.resx

Not reported by any user, noticed it while working on something else

Skyline: clean up a few lingering UI references to ion mobility "predictor" (should be "library")

---

pwiz_tools/Skyline/Menus/RefineMenu.Designer.cs
pwiz_tools/Skyline/Menus/RefineMenu.resx
pwiz_tools/Skyline/Menus/SkylineControl.cs
pwiz_tools/Skyline/Skyline.cs
pwiz_tools/Skyline/TestFunctional/SkylineMenuTest.cs
pwiz_tools/Skyline/TestFunctional/TestFunctional.csproj

Fix the UI mode hiding/showing of Refine menu items.
This was broken by previous pull request #1354 
(also, a couple of menu items did not have their event handlers hooked up right).

Fix UI Modes on Refine menu items

---

pwiz_tools/Skyline/Menus/RefineMenu.cs

There were several places where "this" (i.e. "RefineMenu") was being used, and it should have been SkylineWindow.

Fix a few places on RefineMenu broken by previous refactor

---

pwiz_tools/Skyline/EditUI/PasteDlg.cs
pwiz_tools/Skyline/FileUI/PeptideSearch/ImportFastaControl.cs
pwiz_tools/Skyline/FileUI/PeptideSearch/ImportPeptideSearchDlg.cs

* fixed ImportFastaControl not checking for existence of filepath before letting user continue, and in DDA search mode, disabled multiline FASTA control even before Browse button is clicked, and made Clear button not restore to multiline mode
* added a generic string-only override for ImportFastaHelper.ShowFastaError

* fixed ImportFastaControl not checking for existence of filepath

---

pwiz_tools/Skyline/FileUI/PeptideSearch/ImportPeptideSearchDlg.cs
pwiz_tools/Skyline/SettingsUI/FullScanSettingsControl.cs

Here we only increase the height of the ImportPeptideSearchDlg if the built library contains ion mobilities.
(Side note: we can't decrease the height when selected from the start page even though the workflow group box is hidden, because it cuts off stuff on the Full Scan settings page.)

Fix ImportPeptideSearchDlg height

---

pwiz_tools/Skyline/TestFunctional/OptimizeTest.cs

This line was accidentally added as part of heat map checkin.

Remove "PauseTest()" call from Optimize Test.

---

libraries/boost-build/src/tools/msvc.jam

Should greatly reduce PDB size-on-disk when building debug build (without optimization). Defaults to on but can be turned off with debug-store-compress=off.

Enable /PDBCOMPRESS via <debug-store-compress>

---

pwiz_tools/Skyline/Controls/SequenceTree.cs
pwiz_tools/Skyline/Model/GroupComparison/GroupComparisonDef.cs
pwiz_tools/Skyline/TestFunctional/GroupComparisonTest.cs

Certain characters need to be escaped before being passed to SendKeys.Send method.
(Reported on exception web)
Also, fix problem where bringing up Group Comparison dialog would have the "Name" filled in as "__internal__".
(This bug was introduced a few weeks ago and has not made it into a Skyline-Daily)

Fix exception typing ")" into blank node at bottom of Sequence Tree.

---

pwiz_tools/Shared/Common/Controls/Clustering/DendrogramScale.cs
pwiz_tools/Skyline/Controls/Clustering/HierarchicalClusterGraph.cs
pwiz_tools/Skyline/Controls/Databinding/DataboundGridControl.cs
pwiz_tools/Skyline/Controls/Graphs/RTLinearRegressionGraphPane.cs

1. NullReferenceException bringing up a Heat Map which had either no rows or no columns
2. IndexOutOfRangeException clicking on any point in LinearRegressionGraphPane.

Fixes from the exception web:

---

pwiz_tools/BiblioSpec/src/BlibBuild.cpp
pwiz_tools/BiblioSpec/src/BlibBuilder.cpp
pwiz_tools/Skyline/FileUI/PeptideSearch/DDASearchControl.cs
pwiz_tools/Skyline/FileUI/PeptideSearch/ImportPeptideSearchDlg.cs
pwiz_tools/Skyline/Model/DdaSearch/MSAmandaSearchWrapper.cs
pwiz_tools/Skyline/Model/Lib/BiblioSpecLiteBuilder.cs
pwiz_tools/Skyline/SettingsUI/BuildLibraryDlg.cs
pwiz_tools/Skyline/TestTutorial/TutorialAuditLogs/en/TestDdaTutorial.log

* added support for BiblioSpec to read .mzid.gz files (pwiz can read them just like uncompressed files)
* changed MSAmandaWrapper's expected output filepath to the .mzid.gz file
* fixed ImportPeptideSearchDlg continuing to import library even when DDA search fails
@nickshulman Does the ImportPeptideSearchDlg change make sense to you? It didn't make sense to me to run CloseWizard() if the build library step failed (without cancellation). It makes more sense to me to let the user go back and try again, or let the user cancel explicitly from the wizard.

* added support for BiblioSpec to read .mzid.gz files

---

pwiz_aux/msrc/utility/vendor_api/Waters/WatersRawFile.hpp

- fixed Waters "Unknown Generic Error" due to calling GetDriftTime() on functions existing in Waters .RAW but not listed in _extern.inf
Reported by Laura (Rozas?) and tomas-pluskal
Closes https://github.com/ProteoWizard/pwiz/issues/1409

- fixed Waters "Unknown Generic Error"

---

pwiz/data/vendor_readers/ABI/SpectrumList_ABI.cpp
pwiz_aux/msrc/utility/vendor_api/ABI/WiffFile.cpp
scripts/misc/clean_vendor_targets.bat

- fixed precursor ion spectrum support for WIFF files (use `<product>` element instead of `<precursor>`)

- fixed precursor ion spectrum support for WIFF files

---

pwiz_tools/Skyline/TestRunner/Program.cs

* added MutedTotalHandleLeakTestNames and MutedUserGdiHandleLeakTestNames fields to TestRunner (will be used to ignore TestDdaSearch handle leak in release branch)

Add handle leak muting for TestRunner

---

pwiz_tools/Skyline/TestUtil/AssertEx.cs

AssertEx.RoundTrip method is writing wrong UTF encoding mark into the XML header (UTF-16 instead of UTF-8)

Fix the Unicode bug in AssertEx method

---

pwiz_tools/BiblioSpec/src/MaxQuantModReader.h
pwiz_tools/BiblioSpec/src/MaxQuantReader.cpp
pwiz_tools/BiblioSpec/src/MaxQuantReader.h

Reported by Ida Suppanz
Tested as working on Ida's data (as well as after tweaking their mqpar.xml to use a C-terminal label instead of N-terminal).

- fixed BiblioSpec's MaxQuant reader not applying terminal label-type mods

---

pwiz/data/identdata/IO.cpp

- fixed mzIdentML reader mutating input files using unspecific cleavagege enzyme (clearing name and trying to interpret real enzyme from siteRegexp); now that is only done for the old, obsolete NoEnzyme term; unspecific cleavage is only special now by forcing the specificity attribute to non-specific
Should close https://github.com/MSGFPlus/msgfplus/issues/117

- fixed mzIdentML reader mutating input files using unspecific cleavage

---

libraries/boost-build/src/tools/common.jam

* changed Windows hard-link/copy action to not hide error output from the fallback copy, to only try deleting if file exists, and not to hide standard error from the delete.

Improve Windows hard-link/copy action

---

pwiz_tools/Skyline/Model/Lib/BiblioSpecLite.cs

Need to handle exceptions when trying to get details on the offending library.

Skyline: better error handling when trying to read a damaged BiblioSpec file into Skyline

---

pwiz_tools/Skyline/SettingsUI/Irt/CalibrateIrtDlg.Designer.cs
pwiz_tools/Skyline/SettingsUI/Irt/CalibrateIrtDlg.cs
pwiz_tools/Skyline/TestFunctional/IrtTest.cs
pwiz_tools/Skyline/TestTutorial/IrtTutorialTest.cs

So I think the actual problem was that the test was doing stuff with the form, but sometimes before the Form.Shown event handler had executed.
I'm not 100% sure here but I ran it a bunch of times on Brian's machine and didn't get any failures with this fix.

Fix irt tests

---

pwiz_tools/Skyline/Model/ModificationMatcher.cs
pwiz_tools/Skyline/Test/VariableModTest.cs

- ModificationMatcher explicit mods prevent loss mods

Skyline: Fix case importing a transition list

---

pwiz_tools/Skyline/Model/AbstractModificationMatcher.cs
pwiz_tools/Skyline/Model/ModificationMatcher.cs
pwiz_tools/Skyline/Test/ModificationMatcherTest.cs

- It seems my last PR caused some problems in wider use than our automated tests
- New automated test added to cover more cases, including the one that caused the NRE

Skyline: Fix a NRE in Edit > Insert > Peptides found by Nick with neutral losses

---

pwiz/data/msdata/SpectrumList_mzXML.cpp
pwiz_tools/BiblioSpec/src/mzxmlParser.cpp

Tested with the PEAKS pepxml and mzxml. The resulting blib gets the ionMobility values as expected. Didn't take it all the way into Skyline though.

- added support for invK0 attribute written by PEAKS export

---

pwiz/analysis/dia_umpire/DiaUmpire.cpp
pwiz/analysis/dia_umpire/DiaUmpire.hpp
pwiz/utility/bindings/CLI/analysis/spectrum_processing.hpp
pwiz_tools/Shared/ProteowizardWrapper/DiaUmpire.cs
pwiz_tools/Skyline/FileUI/PeptideSearch/ConverterSettingsControl.cs
pwiz_tools/Skyline/Jamfile.jam
pwiz_tools/Skyline/TestFunctional/DiaSearchTest.cs

* made DiaUmpire spill file format to be configurable; the mz5 format leaks some memory so Skyline needs to use a stable format for leak checking
* added TestDiaSearchFixedWindows to Pass1Subset test

Workaround DiaUmpire spill file leak

---

pwiz_tools/Shared/ProteowizardWrapper/DiaUmpire.cs
pwiz_tools/Skyline/Model/DiaUmpireDdaConverter.cs
pwiz_tools/Skyline/TestFunctional/DiaSearchTest.cs

* disabled iteration listener for DiaUmpire.WriteToFile to check if it's the only one causing access violations
* switched DiaUmpire output file format to mzML if UseMzMlSpillFile is set
* added -diaumpire.mzML file cleaning in DiaSearchTest
* added temporary wide tolerances for ValidateTargets in DiaSearchTest (I've observed up to 10 peptides off of target, which is a lot worse than 1, but it's a temporary measure and doesn't seem to impact the perftest as much)

Skyline DiaUmpire stability fixes

---

pwiz_tools/Skyline/EditUI/EditLinkedPeptidesDlg.cs
pwiz_tools/Skyline/Model/DocSettings/Modification.cs
pwiz_tools/Skyline/Properties/Resources.Designer.cs
pwiz_tools/Skyline/Properties/Resources.resx
pwiz_tools/Skyline/Test/SrmSettingsTest.cs

Now that users are able to add neutral loss modifications to their peptides using the "Modify Peptide" dialog, the error "Loss-only modifications may not be explicit" no longer applies.
(user "jmr" reported this error with a crosslink modification which had zero mass and some neutral losses, but this error can be reproduced with simple neutral loss modifications)
Also, fix an error "Protein sequence may not be empty" that can happen in the Edit Linked Peptides dialog if the focus is in the new row of the peptide sequences grid when you press "OK" on the Edit Linked Peptides dialog when the focus is in an uncommitted new row in the DataGridView.
(also reported by jmr)

Fix "Loss-only modifications may not be explicit." error

---

pwiz/analysis/dia_umpire/DiaUmpire.cpp
pwiz/utility/bindings/CLI/analysis/spectrum_processing.cpp
pwiz/utility/bindings/CLI/msdata/MSDataFile.cpp
pwiz_tools/Shared/ProteowizardWrapper/DiaUmpire.cs
pwiz_tools/commandline/msconvert.cpp

Possibly due to missing KeepAlive calls. Let's see.

Fix DiaUmpire crashes from CLI bindings

---

pwiz/analysis/dia_umpire/DiaUmpire.cpp
pwiz/analysis/dia_umpire/PeakCluster.hpp
pwiz/analysis/dia_umpire/PeakCurve.hpp
pwiz/analysis/spectrum_processing/SpectrumList_DiaUmpire.cpp
pwiz/utility/bindings/CLI/analysis/spectrum_processing.cpp
pwiz/utility/misc/String.cpp
pwiz_tools/Shared/Common/SystemUtil/ProcessRunner.cs
pwiz_tools/Shared/ProteowizardWrapper/DiaUmpire.cs
pwiz_tools/Skyline/FileUI/PeptideSearch/DDASearchControl.cs
pwiz_tools/Skyline/Jamfile.jam
pwiz_tools/Skyline/Model/DiaUmpireDdaConverter.cs
pwiz_tools/Skyline/Skyline.csproj
pwiz_tools/Skyline/TestFunctional/DiaSearchTest.cs
pwiz_tools/Skyline/TestPerf/DiaUmpireTutorialTest.cs
pwiz_tools/Skyline/TestSettings_x64-template.testsettings
pwiz_tools/Skyline/TestSettings_x86-template.testsettings
pwiz_tools/commandline/msconvert.cpp

* added extra debug conditional code to DiaUmpire.cpp
* changed DiaUmpire.cpp params file parser to support variable names with or without SE prefix
* added window sizes to DiaUmpire output file's processingMethod userParams for variable size scheme
* moved window scheme into pwiz.ProteowizardWrapper.DiaUmpire.Config
* fixed DDASearchControl to ignore repeated identical progress messages
* added msconvert as a dependency of Skyline (built with same without-cxt setting)
* fixed TestDia*DiaUmpire* tests not deleting previous DiaUmpire output files
* removed MSTest restriction from TestDiaSearch* since it is run out of process now

Switch from in-process DiaUmpire to msconvert

---

pwiz_tools/Skyline/Controls/Clustering/BoundGraphDataCalculator.cs
pwiz_tools/Skyline/Controls/Graphs/ExportMethodScheduleGraph.cs
pwiz_tools/Skyline/Controls/Graphs/GraphDataCalculator.cs
pwiz_tools/Skyline/Controls/Graphs/RTGraphController.cs
pwiz_tools/Skyline/Controls/Graphs/RTScheduleGraphPane.cs
pwiz_tools/Skyline/FileUI/ExportMethodDlg.cs
pwiz_tools/Skyline/TestFunctional/ExportMethodDialogTest.cs
pwiz_tools/Skyline/TestRunnerLib/TestRunnerFormLookup.csv

Fix Exception "Scheduling failure (no targets?)" displaying RTScheduleGraphPane if Bruker template file is specified and the document is empty.
(Reported on the exception web)
Fix NullReferenceException trying to display Scheduling Graph from Export Method dialog.
(Discovered by Kaipo)
Fix Overflow exception if user sets the scheduling window to "NaN" (not a number).
(Found by Nick. I'll do a separate PR to make it so that MessageBoxHelper prevents the user from being able to type NaN into a DecimalListTextBox).
Also, added a step to TestExportMethodDlg which brings up ExportMethodScheduleGraph

Fix RTScheduleGraphPane exceptions (#1551)

---

pwiz_tools/Skyline/CommandArgs.cs
pwiz_tools/Skyline/CommandLine.cs
pwiz_tools/Skyline/Executables/SkylineRunner/ErrorChecker.cs
pwiz_tools/Skyline/Executables/SkylineRunner/Program.cs
pwiz_tools/Skyline/Executables/SkylineRunner/Properties/Resources.Designer.cs
pwiz_tools/Skyline/Executables/SkylineRunner/SkylineRunner.csproj
pwiz_tools/Skyline/Properties/Resources.Designer.cs
pwiz_tools/Skyline/Properties/Resources.ja.resx
pwiz_tools/Skyline/Properties/Resources.resx
pwiz_tools/Skyline/Properties/Resources.zh-CHS.resx
pwiz_tools/Skyline/TestData/CommandLineTest.cs
pwiz_tools/Skyline/TestData/TestData.csproj

* Skyline: Always output a message beginning with "Error:" when returning a non-zero exit code from CommandLine.
- Attempted improvements at the new logic for SkylineRunner error exit codes
- make SkylineRunner error exit codes more robust to output with --timestamp and --memstamp
Co-authored-by: Brendan MacLean <brendanx67@users.noreply.github.com>
Co-authored-by: brendanx67 <brendanx@proteinms.net>

Skyline: Always output a message beginning with "Error:" when returning a non-zero exit code from CommandLine. (#1531)

---

pwiz_tools/Skyline/FileUI/PeptideSearch/ImportFastaControl.resx

@brendanx67 I did test it. It's a little odd that you saw the bottom anchoring behavior even though it's not bottom anchored; probably due to the alignment shenanigans that it does due to being able to switch between multiline or not.

* fixed top anchor for FASTA textbox

---

pwiz_tools/Bumbershoot/idpicker/Forms/ProteinTableForm.cs

* fixed "Specified cast invalid" for protein view when pivoting non-isobaric quant modes

Fixed "Specified cast invalid" for protein view

---

pwiz_tools/Skyline/TestData/CommandLineTest.cs

SkylineRunnerErrorDetectionTest was causing (by means of the "--culture" commandline argument) LocalizationHelper.CurrentUICulture to get changed and not changed back, which caused subsequent tests to fail.
The "--culture" command line argument is only necessary if the test needs to test the commandline in a new process (in which case it does not matter if it cleans itself up).
Since SkylineRunnerErrorDetectionTest is doing its work by calling into the commandline code in this process, it can just use "LocalizationHelper.CallWithCulture" to cause the culture to be set to what it needs to.
The FullScanFilterTest fails if you do "Run All Tests" in Visual Studio. It's also been failing in the Debug code coverage build on TeamCity.

Fix failure in "FullScanFilterTest" when running all tests within Visual Studio.

---

pwiz_tools/Skyline/Model/SrmDocumentSharing.cs
pwiz_tools/Skyline/TestData/CommandLineTest.cs
pwiz_tools/Skyline/TestUtil/AbstractUnitTestEx.cs

Fix failure in "FullScanFilterTest" when running all tests within Visual Studio. (#1569)
* Fix failure in "FullScanFilterTest" when running all tests within Visual Studio.
SkylineRunnerErrorDetectionTest was causing (by means of the "--culture" commandline argument) LocalizationHelper.CurrentUICulture to get changed and not changed back, which caused subsequent tests to fail.
Fix problem where Audit Log (.skyl) file does not get included in .sky.zip (#1570)
(Reported by Brendan)

Cherry pick test and document sharing fixes from master (#1569, #1570)

---

pwiz_tools/Skyline/Skyline.Designer.cs

The tooltips on the menu items "Remove Repeated Peptides" and "Remove Duplicate Peptides" are not showing up.
This can be fixed by setting "ShowToolTips" to true on the Skyline menu strip.
I do not know why this worked back in Skyline 20.2, but it did, even though back then "ShowToolTips" was false. It must be that moving the menu items to the separate RefineMenu control caused a change in behavior.
These two menu items are the only menu items in Skyline that are supposed to have a tooltip.
There is also sometimes a tooltip on the recent files at the bottom of the File menu. Those tooltips never stopped working.
(Reported by Deanna)

Set menuStrip.ShowToolTips to true

---

pwiz_tools/Skyline/Controls/Graphs/RTLinearRegressionGraphPane.cs
pwiz_tools/Skyline/Skyline.Designer.cs

Tooltips are not showing up because MenuStrip.ShowItemTooltips was false.
Not sure why this was not an issue in earlier versions of Skyline, but the tooltips stopped showing up sometime after Skyline 20.2.
(Reported by Deanna)
Fix problem where progress bar on RTLinearRegressionGraphPane sometimes does not disappear. (#1578)
(not reported by anyone)

Fix tooltips on "Remove Repeated Peptides" and "Remove Duplicate Peptides" (#1574)

---

pwiz_tools/Skyline/FileUI/PeptideSearch/ImportFastaControl.cs
pwiz_tools/Skyline/TestPerf/DdaTutorialTest.cs

* replaced RecordAuditLogs with IsRecordMode in DdaTutorialTest
* fixed ImportFastaControl to hide targetFastaPanel (for importing targets from a separate FASTA) when not doing a DDA/DIA search

DdaTutorialTest and ImportFastaControl fixes

---

pwiz_tools/Skyline/Properties/Resources.ja.resx
pwiz_tools/Skyline/Properties/Resources.zh-CHS.resx

Changes added to the Japanese and Chinese resx files with PR 1531 were overwritten with the commit to merge localization changes for 21.1. Adding those changes back:
- Added translated "CommandStatusWriter_WriteLine_Error_"
- Removed PanoramaHelper_ValidateServer_ and PanoramaHelper_ValidateFolder_ (no longer used in the code)
- Removed CommandArgs_PanoramaArgsComplete_plural_ and CommandArgs_PanoramaArgsComplete_. Their value has changed and will have to be translated.

Add back lost changes to translated resx files

---

libraries/ext-boost.jam

* fixed x86 debug compile (only for Skyline for some reason, maybe related to CXT being excluded)

* fixed x86 debug compile

---

.gitignore
pwiz_tools/BiblioSpec/src/LibReader.cpp
pwiz_tools/BiblioSpec/src/PwizReader.cpp
pwiz_tools/BiblioSpec/src/Reportfile.cpp
pwiz_tools/BiblioSpec/src/SearchLibrary.cpp
pwiz_tools/Skyline/Controls/Graphs/RTLinearRegressionGraphPane.cs
pwiz_tools/Skyline/TestFunctional/DiaSearchTest.cs

- Query retention times were being reported as 0 instead of the actual value
- Library/reference spectrum retention times were not being recorded in the report file.

Fix for reporting query retention times and library retention times now added to report from blib libraries

---

.github/workflows/build_and_test.yml
.github/workflows/cherrypick-to-release.yml

Switch from triggering on push to master to triggering on issue comment
Looks like I have to merge this to master before I can test it: `This event will only trigger a workflow run if the workflow file is on the default branch.`

Remove inappropriate merge strategy and try again with default strategy

---

pwiz_tools/Skyline/Controls/Graphs/SpectrumGraphItem.cs
pwiz_tools/Skyline/TestFunctional/LibraryExplorerTest.cs

In the library explorer spectrum graph, ranked small molecule fragments are colored differently than unranked small molecule fragments. However, the annotations were being colored as if all small molecule fragments were unranked. This resulted in a mismatch between the color of the lines on the graph and the color of the annotations. 
This change fixes the mismatch by considering the rank of small molecule fragments when assigning the color of annotations.

Fix mismatch between color of annotations and lines on small molecule library explorer graph

---

pwiz_tools/Skyline/Controls/Graphs/SpectrumGraphItem.cs
pwiz_tools/Skyline/TestFunctional/LibraryExplorerTest.cs

Only test small molecule annotations after switching to a small molecule library

Fix TestLibraryExplorerAsSmallMolecules

---

pwiz_tools/Skyline/Executables/Installer/Product-template.wxs
pwiz_tools/Skyline/Skyline.csproj

Remove all of the system requirements from the ClickOnce installer except .Net 4.72.
Also add msvcp140.dll, vcomp140.dll and vcruntime140.dll to pwiz_tools/Skyline/percolator folder so that MSAmanda can run without error on a clean machine.
Also, add the "*.exe.config" files for the executables in the "Method" folder. When the ".exe.config" file is missing, Windows assumes that the exe requires .Net 3.5, and the user gets prompted to install it.
With this change, I am not aware of anything that would not work if the user installed Skyline on a clean Windows 10 machine.

Remove .Net 3.5 from system requirements for ClickOnce installer.

---

pwiz_tools/Skyline/Model/Databinding/DocumentViewTransformer.cs
pwiz_tools/Skyline/TestFunctional/TicNormalizationTest.cs

(Not reported by anyone but I ran into this bug while answering Roman's support request)

Fix problem where "Protein Abundance" column would display as "column not found" if the report also had any peptide-level columns.

---

pwiz_tools/Skyline/Model/Results/ChromHeaderInfo.cs
pwiz_tools/Skyline/Model/Results/TimeIntervals.cs
pwiz_tools/Skyline/Test/ChromPeakTest.cs
pwiz_tools/Skyline/TestFunctional/TriggeredAcquisitionTest.cs

It "Triggered chromatogram extraction" is checked on the Transition Instrument Settings, the Area values all end up 60 times smaller than they are supposed to be.
The light:heavy ratios would still be correct, so users might not notice.
(Not reported by a user. I ran into this bug while working on a different feature).

Fix problem where if "Triggered Acquisition" causes peak areas to be 60 times too small

---

pwiz_tools/Skyline/FileUI/ImportTransitionListColumnSelectDlg.cs
pwiz_tools/Skyline/Model/SmallMoleculeTransitionListReader.cs
pwiz_tools/Skyline/Model/SrmDocument.cs
pwiz_tools/Skyline/SkylineFiles.cs
pwiz_tools/Skyline/TestFunctional/PasteMoleculesTest.cs
pwiz_tools/Skyline/Util/Extensions/Text.cs

A fix for a bug where the first line of a transition list was not imported in the case where the transition list did not contain a header row

Fix transition list first line import bug

---

pwiz_tools/Skyline/TestFunctional/ZedGraphClipboardTest.cs

Add information to the exception that gets thrown by TestZedGraphClipboard to try to track down intermittent nightly failure.

Add a little more information to TestZedGraphClipboard 

---

pwiz_tools/Skyline/TestFunctional/ZedGraphClipboardTest.cs

There was a StackOverflow page that said that maybe calling "Clipboard.SetDataObject" might work more reliably than "Clipboard.SetText".

Still trying to fix intermittent failure in TestZedGraphClipboard.

---

Jamroot.jam
libraries/boost-build/src/tools/msvc.jam

* added --build-path option to allow overriding PWIZ_BUILD_PATH (using non-default value will still break SeeMS and MSConvertGUI but it's still useful)
* fixed MSVC not using 64-bit tooling on 64-bit hosts (hopefully this will fix the debug build issues happening with VS 2019; it seemed to fix them on my local machine)

Build system fixes

---

pwiz_aux/msrc/utility/vendor_api/Bruker/Baf2Sql.cpp
pwiz_aux/msrc/utility/vendor_api/Bruker/Baf2Sql.hpp

- added precursor charge state for Bruker BAF files (tested locally but I don't have any small datasets with non-zero charge states to add for an automated test)
Reported by Anna Popova

- added precursor charge state for Bruker BAF files

---

README.md
pwiz/data/msdata/ChromatogramList_mzML_Test.cpp
pwiz/data/msdata/IO.cpp
pwiz/data/msdata/IOTest.cpp
pwiz/data/msdata/SpectrumList_mzML_Test.cpp
pwiz_tools/SeeMS/Dialogs/SpectrumListForm.cs

- changed mzML binary data array behavior when DetailLevel < FullData: now the BDAs will be created, but the arrays are left empty; this allows metadata readers (like SeeMS) to tell that it's a 3-array combined IMS spectrum

mzML binary data arrays for metadata detail levels

---

pwiz/data/msdata/MSDataFile.cpp
pwiz/data/msdata/MSDataFileTest.cpp
pwiz/data/msdata/Reader.cpp
pwiz/data/msdata/SpectrumListBase.cpp
pwiz/data/msdata/SpectrumList_MGF_Test.cpp
pwiz/data/msdata/SpectrumList_mzML_Test.cpp
pwiz/utility/misc/Filesystem.cpp
pwiz/utility/misc/Filesystem.hpp
pwiz_tools/BiblioSpec/src/PwizReader.cpp

* added hack to find() for trying index=123 if scan=124 is looked for and not found, and vice versa
* fixed BiblioSpec not handling CVID_Unknown from getDefaultNativeIDFormat()
* added pwiz::util::check_path_length() to throw an exception on Windows for paths that are too long
- added checks on Windows for paths which exceed 250 characters; now trying to read/write these paths should give a sensible error message instead of a mysterious crash (I used 250 instead of the actual Windows limit of 260 because RawFileReader was failing for paths longer than 250)
BiblioSpec issue reported by Karl-Heinz.
Closes #1790

Find scan/index hack and path too long error

---

pwiz_tools/Skyline/FileUI/PeptideSearch/TransitionSettingsControl.cs

e.g. https://skyline.ms/announcements/home/issues/exceptions/thread.view?rowId=53056

Fix control positions on TransitionSettingsControl being wrong if Initialized multiple times

---

pwiz_tools/Skyline/Test/AdductTest.cs
pwiz_tools/Skyline/Util/Adduct.cs

Came in on Exception web without any data, but I was able to repro by feeding the parser a description like "+M" in a new test step.

fix an unhandled exception when attempting to parse an ill-formed adduct description

---

pwiz/analysis/dia_umpire/DiaUmpire.cpp
pwiz/analysis/dia_umpire/DiaUmpire.hpp
pwiz/analysis/dia_umpire/DiaUmpireMath.hpp
pwiz/analysis/dia_umpire/Jamfile.jam
pwiz/analysis/dia_umpire/PeakCurve.hpp

- fixed step counts when MultithreadOverWindows is off
* moved peak curve/cluster deallocation to a background thread (this fixes the long delay, with no progress messages, after processing all the DIA windows and before writing spectra)
* added MaxNestedThreads parameter and fixed the default so the nested thread pool will use all cores (the MaxThreads parameter which controls the number of windows processed at a time now defaults to half the number of cores)
* made profiling-guided optimizations in memory allocations and math inner loops; performCWT still takes the most compute time, and it would be great if the inner loop could be vectorized because it's pure math, but I couldn't figure out a reasonably easy way to do it because the index into the Mexican hat wavelet skips around

DiaUmpire optimizations

---

pwiz/analysis/dia_umpire/Jamfile.jam

AVX2, at least, is too new to rely on. This auto-vectorization is not doing anything substantial anyway (because as mentioned in #1834 , I couldn't get the most compute-intensive loop to meet the vectorization constraints).

Disable auto-vectorization

---

pwiz_tools/Skyline/SettingsUI/ViewLibraryDlg.cs

User noticed slow load time for large peptide library

temporary fix for performance issues around IM filtering in library viewer - just disable for peptides until we address the actual problem

---

pwiz_tools/Skyline/FileUI/PeptideSearch/ConverterSettingsControl.cs
pwiz_tools/Skyline/FileUI/PeptideSearch/SearchSettingsControl.cs
pwiz_tools/Skyline/Model/AbstractDdaConverter.cs
pwiz_tools/Skyline/Model/DdaSearch/MsconvertDdaConverter.cs
pwiz_tools/Skyline/Model/DiaUmpireDdaConverter.cs
pwiz_tools/Skyline/TestFunctional/DdaSearchTest.cs
pwiz_tools/Skyline/TestFunctional/DiaSearchTest.cs
pwiz_tools/Skyline/TestPerf/DdaTutorialTest.cs
pwiz_tools/Skyline/Util/UtilInstall.cs

* fixed error processing DIA raw files from vendor formats with MS-GF+ and MSFragger
* turned off calibrate_mass in TestDdaSearchMsFragger to speed it up
* made downloading of DDA search tools dependent on IsPass0
* fixed TestDiaSearchVariableWindows* tests not able to handle downloading missing tools

* fixed error processing DIA raw files

---

pwiz/data/identdata/Serializer_pepXML.cpp
pwiz/data/proteome/Serializer_FASTA.cpp
pwiz/data/vendor_readers/ABI/SpectrumList_ABI.cpp
pwiz_tools/BiblioSpec/Jamfile.jam

- added Percolator terms to Serializer_pepXML's translation tables
- fixed MS2 spectra in WIFF files sometimes missing precursor info
* fixed csv.h missing from BiblioSpec subset tarball
* fixed indexing bug in Serializer_FASTA caused by earlier getlinePortable() change

Fix several issues in pwiz core

---

pwiz_tools/Skyline/Controls/Startup/StartupActions.cs
pwiz_tools/Skyline/EditUI/PasteDlg.cs
pwiz_tools/Skyline/TestFunctional/StartPageInsertTransitionListTest.cs
pwiz_tools/Skyline/TestFunctional/TestFunctional.csproj

PasteDlg no longer supports "PasteFormat.transition_list", so the "Import Transition List" button on the Start Page needed to be updated to use "ShowInsertTranstionListDlg" instead of "ShowPasteDlg".
Reported on Exception Web here:
https://skyline.ms/announcements/home/issues/exceptions/thread.view?rowId=54010

Fix NRE using "Import Transition List" button on Start Page

---

pwiz_tools/Skyline/FileUI/ImportTransitionListColumnSelectDlg.cs
pwiz_tools/Skyline/TestFunctional/PasteMoleculesTest.cs

Thanks to Nick for catching this. Too many of our tests set the columns explicitly and we missed this failure to set that column based on input text alone.

Precursor charge state wasn't being recognized in small molecule transition list import

---

pwiz_tools/Skyline/TestFunctional/CantReadSkydTest.cs

It now waits and retries if it is unable to get a write lock on the .skyd file.

Fix intermittent failure in TestCantReadSkyd

---

Jamroot.jam
pwiz_tools/Skyline/Executables/Installer/Jamfile.jam
pwiz_tools/Skyline/Executables/Installer/Product-template.wxs

* commented out several apparently unused/unnecessary MSVC runtime DLLs and moved CompassXtract-only DLLs to a separate, conditionally included list

* commented out several apparently unused/unnecessary MSVC runtime DLLs

---

Jamroot.jam

Looks like we missed a place where we needed to check for 14.3 as well as 14.2

VS2022 build wasn't copying the msparser DLLs

---

pwiz/data/msdata/Serializer_mzXML.cpp

There's no way to know the correct nativeID type so just fall back to scan number only.
Closes #1954

* fixed reading mzXML from mzML parentFile

---

scripts/misc/smartBuildTrigger.py

Disable Skyline x86 builds on release branch (I actually thought all branches were using master build of the script but apparently that's wrong).

* commented out x86 triggers in smartBuildTrigger.py

---

pwiz_tools/Skyline/Util/Install.cs

I wanted to use the class "Install" in pull request #1981, but the class did not work during unit tests.
The class was looking at "Assembly.GetExecutingAssembly()" instead of the Skyline executable, which ends up returning something not useful when running as a unit test.
Also, moved the initializing code into a static initializer. It used to be that "Install.Type" would not return the correct value until after the property "Install.Version" was first queried.

Fix the "Install" class so that it can be used in unit tests.

---

pwiz_tools/Skyline/SkylineFiles.cs
pwiz_tools/Skyline/TestFunctional/AccessServerTest.cs

This fixes the TestAuditLogTutorial failure

Save the document before uploading to Panorama but only if it is "dirty"

---

pwiz_tools/Skyline/Model/Results/ChromHeaderInfo.cs
pwiz_tools/Skyline/Model/Results/DocNodeChromInfo.cs
pwiz_tools/Skyline/Model/Results/Scoring/IPeakScoringModel.cs
pwiz_tools/Skyline/Test/ObjectSizeTest.cs
pwiz_tools/Skyline/TestData/Results/StructSizeTest.cs

I was planning on adding some new fields to TransitionGroupChromInfo, but before I did so, I thought it would be a good idea to make that class smaller.
Currently instances of this class are 192 bytes
With these changes the class is 120 bytes.
Most of the size reduction comes from changing "float?" fields (which are 8 bytes) to just a "float" (4 bytes) combined with one bit in "_flags".
Before these changes:
With these changes:

Reduce size of class "TransitionGroupChromInfo".

---

pwiz_tools/Shared/Common/DataBinding/Documentation/DocumentationGenerator.cs

Removed "KeyValuePair`2" from Reports documentation. (Reported by Brian Pratt)

Removed "KeyValuePair`2" from Reports documentation.

---

pwiz_tools/Skyline/FileUI/InsertTransitionListDlg.resx

Reported by user Kaitlyn
Developer note: no automated test for this as it's only reproducible by an actual user paste action. Per https://docs.microsoft.com/en-us/dotnet/api/system.windows.forms.textboxbase.maxlength?view=netframework-4.7.2 "In code, you can set the value of the Text property to a value that has a length greater than the value specified by the MaxLength property. This property only affects text entered into the control at run time."

Removed the unintended 32767 character limit for pasting transition lists from the clipboard into the Edit > Insert > Transition List dialog.

---

pwiz_tools/Skyline/TestRunner/Program.cs

* added TeamCity testSuite commands so Skyline tests run by TeamCity are grouped by suite (Test.dll, TestData.dll, TestFunctional.dll, etc; it's named off whatever the "test" argument is, or "all" if not specified)

* added testSuite grouping for Skyline tests run on TeamCity

---

pwiz_tools/Skyline/SkylineGraphs.cs

Fix for a user-reported exception: https://skyline.ms/announcements/home/issues/exceptions/thread.view?rowId=54792

Fix for the NullReferenceException in Library Match Viewer.

---

pwiz_tools/Skyline/Controls/Graphs/GraphChromatogram.cs
pwiz_tools/Skyline/Model/SkylineVersion.cs
pwiz_tools/Skyline/Properties/Resources.Designer.cs
pwiz_tools/Skyline/Properties/Resources.resx

Fixed the display of peak boundaries on the chromatogram graph when all transitions shown are non-quantitative (reported by Brendan)
Added "Skyline 21.2" to the list of available versions at "File > Share" (not reported by anyone).

Fix display of peak boundaries when all chromatograms are non-quantitative

---

pwiz_tools/Skyline/Controls/Clustering/PcaPlot.cs

Fixed error that can happen showing the PCA plot when the total number of principal components for the dataset is one. (reported most recently by Chris on the exception web)

Fix alglib assertion in pca plot

---

pwiz_tools/Skyline/Model/SrmDocument.cs

Change exception type to "OperationCancelledException" if exception is encountered in SrmDocument.ChangeSettings and task has already been canceled.

Attempt to fix intermittent failure in TestMidas.

---

pwiz_tools/Skyline/Controls/Graphs/GraphChromatogram.cs
pwiz_tools/Skyline/Model/RetentionTimes/RetentionTimeValues.cs

Fixed error displaying multiple peptide chromatogram graph if any of the chosen peaks has a start retention time equal to zero. (Reported by Yasmine)

Fix NullReferenceException in GraphChromatogram.DisplayPeptides

---

Jamroot.jam

It's a minimal change and seems to resolve the issue building the release branch on KAIPOT-PC1

Add explicit support for VS2022, seems to be needed on machines where VS2022 is the only option

---

pwiz_tools/Skyline/TestFunctional/ToolServiceTest.cs

It's a pretty common failure, would be nice to understand more about it

Hopefully a somewhat more informative error message for TestToolService failures in Nightly runs

---

pwiz_tools/Skyline/Model/DocSettings/TransitionIonMobilityFiltering.cs
pwiz_tools/Skyline/TestFunctional/IonMobilityTest.cs

Reported by user Sue Abbatiello
Developers note: the "FixedWidth" member was accidentally omitted from the IonMobilityWindowWidthCalculator.Equals method

Fix for "Issue 785: Transition Settings - Ion Mobility - Fixed width value not saved when it is all that changes"

---

pwiz_tools/Skyline/Model/PeptideDocNode.cs

Fixed error that could happen if a particular precursor did not have any results. (Reported by Bob)

Fix NRE in PeptideChromInfoListCalculator.AddChromInfoList

---

pwiz_tools/Skyline/Alerts/AlertDlg.cs
pwiz_tools/Skyline/Alerts/ReportErrorDlg.cs
pwiz_tools/Skyline/Controls/AuditLog/AuditLogExtraInfoForm.cs
pwiz_tools/Skyline/Properties/Settings.Designer.cs
pwiz_tools/Skyline/Properties/Settings.settings
pwiz_tools/Skyline/Skyline.csproj
pwiz_tools/Skyline/Test/CodeInspectionTest.cs
pwiz_tools/Skyline/Util/UtilUIExtra.cs
pwiz_tools/Skyline/app.config

Prevented clipboard error pressing "Copy" button on message dialog (reported on Exception Web)
Also:
Change a few other places that were using "Clipboard.SetText" to use ClipboardHelper.SetClipboardText
Remove unused setting "StackTraceListVersion"
Always include product version in body of exception posts (used to leave it off if not ClickOnce install)
Add code inspection to prevent using Clipboard.SetText outside of test code.
Change CodeInspectionTest to use compiled regular expression because it's faster

Some bug fixes

---

pwiz_tools/Skyline/Controls/Graphs/GraphChromatogram.cs

Fixed error in full scan spectrum viewer that could happen if you rapidly click multiple times on the chromatogram graph. (Reported by Lauren)

Fix ChromSource AssumptionException in UpdateScanProvider

---

pwiz_aux/msrc/utility/vendor_api/ABI/Jamfile.jam
pwiz_tools/Skyline/Executables/Installer/FileList64-template.txt
pwiz_tools/Skyline/Executables/Installer/Product-template.wxs

Fixed missing msconvert.exe from Admin Installer (reported by Dilip)
Also, change capitalization of a couple of dll's and "zh-TW" folder to be consistent between admin installer and the regular installer.

Add msconvert.exe to Administrator Installer

---

pwiz_tools/Skyline/TestTutorial/GroupedStudiesTutorialTest.cs
pwiz_tools/Skyline/TestTutorial/QuasarTutorialTest.cs
pwiz_tools/Skyline/Util/Util.cs
pwiz_tools/Skyline/Util/UtilIO.cs

These changes should fix the problem with InstallToolsTest taking an hour to complete (apparently just noise around trying to delete directories that don't exist), and the occasional failure that seems to be from an interaction of TestGroupedStudiesTutorialDraft and TestGroupedStudies1Tutorial

Tweaks for code coverage speed and stability

---

pwiz_tools/Skyline/SkylineNightly/SkylineNightly.csproj
pwiz_tools/Skyline/SkylineNightly/app.manifest

This manifest file contains <supportedOS id=> tags which indicate that this app is compatible with all currently known versions of Windows.
Having these tags in the manifest make it so that "Environment.OSVersion" will return the actual Windows version number, instead of the version number that Windows was pretending to be (which was "6.2.9200.0" which meant Windows version 8).
The version number for the current version of Windows 11 is "10.0.22000.194".
The app.manifest in this pull request is the one that Visual Studio gives you when you add a manifest file to the project, which just has a lot of commented placeholders in it. I have uncommented the supportedOS tags.

Add "app.manifest" to Skyline Nightly

---

pwiz/data/vendor_readers/Waters/Reader_Waters.cpp

* added catch-all block in Reader_Waters to catch OS exceptions and allow client code like Skyline to see them without unexplained crashing
Reported by Nick?

* added catch-all block in Reader_Waters to catch OS exceptions

---

pwiz_tools/Skyline/Executables/SkylineBatch/SkylineBatch/Properties/app.manifest
pwiz_tools/Skyline/Properties/app.manifest
pwiz_tools/Skyline/SkylineCmd/Properties/app.manifest
pwiz_tools/Skyline/SkylineTester/Properties/app.manifest
pwiz_tools/Skyline/TestRunner/app.manifest

This error is the same as mentioned on this StackOverflow page:
https://stackoverflow.com/questions/27106385/clickonce-manifest-has-invalid-children-but-xml-matches-old-published-manifest
where they said the solution is to remove the Vista line from the application compatibility section.
From testing on my Windows 11 machine, it appeared to be necessary to remove both the Windows 7 and Windows Vista GUIDs.

Attempt to fix clickonce installer error "The element 'assembly' has invalid child element 'SignedInfo'".

---

pwiz_tools/Skyline/Skyline.csproj

Fixed error about missing "OFX.Core.Contracts.dll" when importing SCIEX 6500 QQQ wiff file (reported by Matt)

Add OFX.Core.Contracts.dll to ClickOnce installer.

---

pwiz_tools/Skyline/Alerts/MsFraggerDownloadDlg.cs

With the MSFragger 3.5 release it seems they tweaked the verification code a bit so a new post variable is needed.
This PR also adds support for the "receive_emails" post variable which Skyline has had a checkbox for, but it didn't do anything.
Reported by Mike

Fix MSFragger download agreement

---

pwiz_tools/Skyline/Model/Crosslinking/CrosslinkBuilder.cs
pwiz_tools/Skyline/Model/Crosslinking/CrosslinkSite.cs
pwiz_tools/Skyline/Model/Lib/LibraryKey.cs
pwiz_tools/Skyline/Test/CrosslinkSequenceParserTest.cs

Fixed Unhandled Error when inserting crosslinked peptide sequence which specified "0" as amino acid position. (Reported by Juan)
Fixed Unhandled Error inserting crosslinked peptide whose precursor m/z was very close to Instrument Max Mz setting. (Reported by Juan)

Fix some Unhandled Errors related to crosslinked peptides in Edit > Insert > Peptides:

---

pwiz_tools/Skyline/Model/Results/OnDemandFeatureCalculator.cs

Fix "InvalidOperationException: Cannot truncate data set after interpolation" adjusting peak boundaries with Candidate Peak grid showing.
Fixed error adjusting peak boundaries while Candidate Peaks grid was showing with scheduled PRM data. (Reported by Marc on exception web)

Fix Candidate Peak grid bug

---

pwiz_tools/Skyline/Model/Results/TimeIntensities.cs

Fixed bug where mass error would sometimes be reported as zero when "Triggered chromatogram acquisition" is checked (reported by Jeffrey, thanks to Nick)

Fix Triggered Chromatogram Acquisition mass error.

---

pwiz_tools/Skyline/Program.cs
pwiz_tools/Skyline/Test/AnalyticsTest.cs
pwiz_tools/Skyline/Test/Test.csproj

* added SendGa4AnalyticsHit() to send an instance event to the new GA4 property
We continue to send events to UA. I modeled the GA4 event after the UA event, but I'm not sure if there isn't some better way to do it. There's a lot of builtin events in GA4, but none of them seem to fit what we're doing with the custom "Instance" event. The "login" event seemed closest but I wasn't clear whether you're supposed to add custom properties to builtin event types. And it's not really a login anyway.
I am considering whether to make the validation variable dependent on whether it's running as a test. But we'd only want to test it once (could be its own test). Do I need to make it public to call it from a unit test?

Added SendGa4AnalyticsHit() to send an event to GA4

---

pwiz_tools/Skyline/Model/Crosslinking/CrosslinkBuilder.cs
pwiz_tools/Skyline/Model/Crosslinking/NeutralFragmentIon.cs
pwiz_tools/Skyline/Test/CrosslinkModTest.cs
pwiz_tools/Skyline/TestUtil/AssertEx.cs

Fixed problem where Skyline would allow transitions which contained multiple crosslink fragment ions which were not actually attached to each other (reported by Bob, thanks Nick)

Prevent disconnected crosslinked fragment ions

---

pwiz_tools/Skyline/Util/DataGridViewPasteHandler.cs

Fixed unhandled error when trying to paste into the Document Grid when it is empty (reported anonymously, thanks Nick)

Fix ArgumentOutOfRangeException pasting into empty document grid

---

pwiz_tools/Skyline/Properties/Resources.Designer.cs
pwiz_tools/Skyline/Properties/Resources.ja.resx
pwiz_tools/Skyline/Properties/Resources.resx
pwiz_tools/Skyline/Properties/Resources.zh-CHS.resx
pwiz_tools/Skyline/SettingsUI/ViewLibraryDlg.cs
pwiz_tools/Skyline/SettingsUI/ViewLibraryDlg.ja.resx
pwiz_tools/Skyline/SettingsUI/ViewLibraryDlg.resx
pwiz_tools/Skyline/SettingsUI/ViewLibraryDlg.zh-CHS.resx

Here's what I think the fix should be:
1. If showRedundantSpectra is true, then labelFilename should say "Fil&amp;e:"
2. If showRedundantSpectra is false, then labelFilename should say "File: " followed by the filename
3. We should never try to parse the text in labelFilename, and instead. the file name should be stored in "_sourceFile".

Fix TestMs1Tutorial

---

pwiz_tools/Shared/Common/SystemUtil/ValueCache.cs

As of .Net 4.7.2, you can now recover the actual stored value from a HashSet  - they added 
public bool TryGetValue (T equalValue, out T actualValue);
so we no longer need to use a dictionary whose values are the same as its keys to retrieve the originally stored value.
Internal issue only, no user report

Improved version of ValueCache which should use less memory

---

pwiz_tools/Skyline/EditUI/AssociateProteinsDlg.cs
pwiz_tools/Skyline/TestFunctional/ImportPeptideSearchTest.cs

* fixed OK button never being enabled when AssociateProteinsDlg's PeptideCount == 0
* fixed TestImportPeptideSearch not waiting for OK button to be enabled
I don't know if this will fix the actual intermittent failure but it definitely fixes a usability bug when the FASTA mapping results in no peptide matches.

* fixed AssociateProteinsDlg's OK button never being enabled

---

.gitignore
pwiz_tools/Skyline/Skyline.sln

Add "BAF2SQL-README.txt" and "BAF2SQL-THIRD-PARTY-LICENSE-README.txt" to .gitignore at root of project.
Also remove references to ".testsettings" files from Skyline.sln. Not sure whether these things show up in the Visual Studio UI, but I figured they didn't belong in the .sln file anymore.

Add a couple of Bruker files to .gitignore

---

scripts/misc/smartBuildTrigger.py
scripts/misc/vcs_trigger_and_paths_config.py

* added branch specification for non-Skyline builds in vcs_trigger_and_paths_config.pyd_paths_config.py so they don't get triggered for "build everything" builds on Skyline's release branch

Add branch specification for non-Skyline builds in vcs_trigger_and_paths_config.py

---

pwiz_tools/BiblioSpec/src/BuildParser.cpp

BiblioSpec was outputting the message "could not find matches for the following basename with any of the supported file extensions (.mz5, .mz5, .mzML, .mzXML, .ms2, .cms2, .bms2, .pms2)..." where ".mz5" appeared twice.
Fixed incorrect repetition of the first filename extension when BiblioSpec says that it canoot find a file (not reported by anyone)

Fix duplicate filename extension in BlibBuild.exe error message 

---

pwiz.vcxproj
pwiz.vcxproj.filters
pwiz/analysis/dia_umpire/ScanData.hpp

- fixed DIA-Umpire on spectra that aren't sorted by m/z (e.g. from scanSumming timsTOF data)
Closes https://github.com/ProteoWizard/pwiz/issues/2195

- fixed DIA-Umpire on spectra that aren't sorted by m/z

---

pwiz_tools/Skyline/FileUI/ImportTransitionListColumnSelectDlg.cs
pwiz_tools/Skyline/SkylineFiles.cs
pwiz_tools/Skyline/TestTutorial/ExistingExperimentsTutorialTest.cs

- Use WaitForBackgroundProteomeLoaderCompleted() to avoid unexpected document change
- Fix SkylineWindow.ImportMassList() to preserve protein associations from the ImportTransitionListColumnSelectDlg when document changes before ModifyDocument() can commit the change

Skyline (22.2): Fix intermittent failure in TestExistingExperimentsTutorial

---

pwiz/analysis/spectrum_processing/SpectrumList_Filter.cpp
pwiz/analysis/spectrum_processing/SpectrumList_ScanSummer.cpp
pwiz/utility/minimxml/SAXParser.cpp
pwiz/utility/minimxml/SAXParser.hpp
pwiz/utility/minimxml/SAXParserTest.cpp

- fixed xml_root_element to be able to handle XML files without an XML declaration "<?xml ...?>"; reported by Bruna
- fixed scanSumming filter not to change times to seconds when calculating scan time for summed spectra; reported by Amey
- changed scan number filter to fall back to index if there is no scan= in the nativeId
* changed xml_root_element to throw a new exception type xml_root_error instead of runtime_error (finally I can ignore those exceptions when debugging without turning off all runtime_errors!)

Several pwiz fixes

---

pwiz_tools/Skyline/Program.cs
pwiz_tools/Skyline/Test/AnalyticsTest.cs

OK, so after fiddling with Puppeteer for a while, looking at what it was sending, and doing a bit more research about what the cryptically named query parameters meant, I decided that maybe we can just fudge it and make direct requests to google-analytics. It seems to be working. The fact it uses a POST method but actually sends the parameters in the URL is odd, but that's the way it does it in the browser too. When useDebugUrl is true, the page_view hit can be seen in [DebugView](https://analytics.google.com/analytics/web/#/m/p318139389/debugview) and when it's false you can see it in [Realtime view](https://analytics.google.com/analytics/web/#/p318139389/realtime/overview) (and this is also the only way you can see the geolocation is working; DebugView doesn't do the geolocation …

Fix ga4 hit geolocation

---

pwiz_tools/Skyline/Properties/Settings.Designer.cs
pwiz_tools/Skyline/Properties/Settings.settings
pwiz_tools/Skyline/SettingsUI/MsGraphExtension.cs
pwiz_tools/Skyline/SettingsUI/MsGraphExtensionResx.resx
pwiz_tools/Skyline/SettingsUI/ViewLibraryDlg.Designer.cs
pwiz_tools/Skyline/SettingsUI/ViewLibraryDlg.cs
pwiz_tools/Skyline/SettingsUI/ViewLibraryDlg.ja.resx
pwiz_tools/Skyline/SettingsUI/ViewLibraryDlg.resx
pwiz_tools/Skyline/SettingsUI/ViewLibraryDlg.zh-CHS.resx
pwiz_tools/Skyline/Skyline.csproj
pwiz_tools/Skyline/app.config

- Persist splitter positions and property page visibility
- Change property page categorization to make more sense
- Add a File Path property when File Name contains a full path

Skyline: Polish ViewLibraryDlg property page UI

---

pwiz_tools/Skyline/TestTutorial/TargetedMSMSTutorialTest.cs

Fix TestTargetedMSMSTutorial and TestTargetedMSMSTutorialAsSmallMolecules by changing expected number of properties in the property sheet.

Fix TestTargetedMSMSTutorial

---

pwiz_tools/Skyline/Model/ElementLocators/ElementRefs.cs

Fixed "Unexpected Error" changing annotation value in document grid when the document had been changed (reported anonymously)

Fix NRE in "ElementRefs.GetNodeRef"

---

pwiz_tools/Skyline/Model/Lib/LibraryKey.cs
pwiz_tools/Skyline/SettingsUI/IonMobility/EditIonMobilityLibraryDlg.cs
pwiz_tools/Skyline/TestFunctional/CrosslinkImsTest.cs
pwiz_tools/Skyline/TestUtil/TestFunctional.cs

Fixed bug where ion mobility library entries for crosslinked peptides would be duplicated each time you pressed the "Use Results" button (reported by Juan)

Prevent duplicate entries in imsdb for crosslinked peptides

---

pwiz_tools/Skyline/TestFunctional/MultiSampleImportPeakBoundariesTest.cs
pwiz_tools/Skyline/TestRunner/Program.cs
pwiz_tools/Skyline/TestTutorial/TargetedMSMSTutorialTest.cs

- ran parallel test all night and got failures in TestTargetedMsMsTutorial and TestMultiSampleImportPeakBoundaries
- also found that parallel testing never passed through the runsmallmoleculeversions argument

Skyline: Test fixes based on all night parallel test run failures

---

pwiz_tools/Skyline/FileUI/ImportTransitionListColumnSelectDlg.Designer.cs
pwiz_tools/Skyline/FileUI/ImportTransitionListColumnSelectDlg.cs
pwiz_tools/Skyline/Model/Import.cs
pwiz_tools/Skyline/Model/PeptideGroupDocNode.cs
pwiz_tools/Skyline/SettingsUI/ViewLibraryDlg.Designer.cs
pwiz_tools/Skyline/SettingsUI/ViewLibraryDlg.cs
pwiz_tools/Skyline/TestFunctional/AssayLibraryImportTest.cs

- Fixed assay library importing to correctly handle unsorted transition lists
- Fixed import transition list column selection to start in the right UI mode
- Fixed toolbar buttons and right-click menu in Spectral Library Explorer, broken adding the property page

Skyline: Fixes found testing import of PaSER assay libraries

---

pwiz_tools/Skyline/FileUI/ImportTransitionListColumnSelectDlg.cs
pwiz_tools/Skyline/Model/Import.cs
pwiz_tools/Skyline/Model/SrmDocument.cs
pwiz_tools/Skyline/SkylineFiles.cs
pwiz_tools/Skyline/TestFunctional/PasteMoleculesTest.cs
pwiz_tools/Skyline/TestFunctional/PasteTransitionListTest.cs
pwiz_tools/Skyline/Util/Extensions/Text.cs

Bruker reported an OutOfMemoryException trying to import a large assay library from PaSER. Testing with 6,000,000 line file (5x the Pan Human library) exposed a number of areas broken in this handling by changes in ImportTransitionListColumnSelectDlg with the introduction of small molecule support and a fix to handle non-rectangular data provided by a user.
These fixes now only support showing columns for long lines in the first 100 rows that we show in the form. Otherwise, the first unexpectedly long line now produces a normal error giving the line number with the line containing extra fields.
Attempting to restore save column selections also read the entire file and information derived from clicking "Check For Errors" was always discarded.

Skyline: Fixes for large transition list / assay library import

---

pwiz/data/vendor_readers/ABI/ChromatogramList_ABI.cpp
pwiz/data/vendor_readers/ABI/Reader_ABI_Test.data/swath.api-sample-centroid.mzML
pwiz/data/vendor_readers/Thermo/ChromatogramList_Thermo.cpp
pwiz_tools/Shared/ProteowizardWrapper/MsDataFileImpl.cs
pwiz_tools/Skyline/Controls/Graphs/GraphChromatogram.cs
pwiz_tools/Skyline/Properties/Resources.Designer.cs
pwiz_tools/Skyline/Properties/Resources.resx
pwiz_tools/Skyline/TestFunctional/PasteTransitionListTest.cs

- removed empty BP chromatograms for WIFF2 files
- added pressure trace support for Thermo files
- Skyline: improved message displayed by TIC chromatogram graph if the file has no MS1 spectra
Review requested about the TIC chromatogram message.

Add support for pressure chromatograms from Thermo

---

pwiz_tools/Skyline/Controls/Graphs/GraphSpectrum.cs

Fixed bug where Library Match graph disappears if spectrum being displayed has no intensities that are greater than zero (reported by Rich)
The X and Y axes would disappear from the Library Match graph if all of the intensities of the displayed spectrum were zero. This happens a lot with EncyclopeDIA quant libraries where the peptide was detected in the chromatogram library but had no signal in the quantification runs.
Before fixing the bug:
After fixing the bug (note that X and Y axes are visible):

Fix blank library match when spectrum intensities are all zero

---

pwiz_tools/Skyline/Model/Results/SpectrumFilter.cs
pwiz_tools/Skyline/TestPerf/PerfHighEnergyIonMobilityOffsetForPRM.cs
pwiz_tools/Skyline/TestPerf/TestPerf.csproj

Formerly we applied it only in All Ions mode, but it is also desirable in PRM etc.
Reported by user Anne

Ion mobility filtering for full scan data should use high energy ion mobility offset values for all acquisition types

---

pwiz_tools/Skyline/Model/Databinding/ReportSharing.cs
pwiz_tools/Skyline/TestData/CommandLineTest.cs

Fixed bug where "--report-add" commandline argument would cause all reports from "External Tools" group to be copied to the "Main" group.

Remove hack that was added to make ConsoleAddSkyrTest.

---

pwiz_tools/Skyline/Model/Results/DocNodeChromInfo.cs

I can't actually see a control path that would allow this to be set null, but it can't hurt to add a check to make sure it's EMPTY rather than null. 
Not clear that this is actually the problem, but inspired by https://skyline.ms/announcements/home/issues/exceptions/thread.view?entityId=f15c02de-375f-103b-b47c-22f53556c296&_anchor=57340

Guard against possible null value

---

pwiz_tools/Skyline/Model/GroupComparison/GroupComparer.cs
pwiz_tools/Skyline/TestPerf/OrbiPrmTutorialTest.cs

Fix NaN's that appear in fold change values in PRM tutorial (reported by Brendan)
The bug was originally introduced by the change to GroupComparer.cs in PR #2155.
This is my best guess as to how to fix this bug, but I need to do some more investigation including comparing the results that we get with this fix to what the results were before the bug was introduced.

Prevent NaN's in fold change values in PRM tutorial

---

pwiz_tools/Skyline/Model/GroupComparison/GroupComparer.cs
pwiz_tools/Skyline/TestPerf/OrbiPrmTutorialTest.cs

Fix NaN's that appear in fold change values in PRM tutorial (reported by Brendan)

Prevent NaN's in fold change values in PRM tutorial (#2318)

---

pwiz_tools/Skyline/TestRunner/Program.cs

* overloaded TestRunner's workerport argument to manually set the port the server listens on
Having a manual workerport allows creating a Firewall exclusion based on port instead of on program path.

TestRunner manual workerport

---

pwiz_tools/Skyline/Model/Results/PeakIntegrator.cs

Crawdad peak finder was being invoked for manually integrated peaks in a misguided attempt to set "Coeluting" to a meaningful value for manually integrated peaks. There were some scenarios where this code was much too slow.
Fixed performance problem with manually integrated peaks (reported by Elena)

Remove slow code from PeakIntegrator.IntegratePeak

---

pwiz_tools/Skyline/Model/Results/PeakIntegrator.cs

Remove slow code from PeakIntegrator.IntegratePeak Crawdad peak finder was being invoked for manually integrated peaks in a misguided attempt to set "Coeluting" to a meaningful value for manually integrated peaks. There were some scenarios where this code was much too slow.
Fixed performance problem with manually integrated peaks (reported by Elena)

Remove slow code from PeakIntegrator.IntegratePeak (#2354)

---

pwiz_tools/Skyline/Model/DocSettings/AbsoluteQuantification/CalibrationCurveFitter.cs
pwiz_tools/Skyline/TestFunctional/FiguresOfMeritTest.cs

The failure was "intermittent" because to speed up the test, TestFiguresOfMerit only tests a random subset of possible sets of settings. This failure happened when calculating the LOD with Bilinear fit.

Fix nightly failure in TestFiguresOfMerit

---

pwiz_tools/Skyline/SkylineNightly/Nightly.cs
pwiz_tools/Skyline/SkylineTester/SkylineTesterWindow.cs
pwiz_tools/Skyline/TestRunnerLib/RunTests.cs

- Fix Nightly parsing of perf tests to avoid assigning memory values of the first failure to all prior tests
- Fix TestRunner to avoid reporting 0.0 heap value during perf tests
- Fix SkylineTester parsing to avoid graphing zero memory values when lines contain unexpected output

Skyline:  Tester fixes

---

pwiz_tools/BiblioSpec/src/DiaNNSpecLibReader.cpp

- may not be ready for merging but hopefully fixes for issues seen at CRG course
- increased robustness by comparing .speclib and .tsv Precursor.IDs to avoid a mix-up situation

BlibBuild: Fixes for DIA-NN speclib parsing

---

pwiz_tools/Skyline/Model/CustomMolecule.cs
pwiz_tools/Skyline/Test/AdductTest.cs
pwiz_tools/Skyline/TestFunctional/PasteMoleculesTest.cs
pwiz_tools/Skyline/TestRunner/Program.cs
pwiz_tools/Skyline/TestUtil/AssertEx.cs
pwiz_tools/Skyline/Util/Adduct.cs
pwiz_tools/Skyline/Util/BioMassCalc.cs

This is a strange construction but we used to allow it, I broke that recently.
Reported by Phil

Restore Skyline's ability to deal with chemical formulas that contain zero counts (e.g. C12N5H0 - that's a zero, not an Oxygen)

---

pwiz_tools/Skyline/TestUtil/AbstractUnitTest.cs
pwiz_tools/Skyline/Util/UtilInstall.cs

Quick fix for change to MacCoss S3. Per discussion with Brian C will later switch to CNAME entry on skyline.ms so it can be redirected without changing code.

* switched s3 bucket for SKYLINE_TOOL_TESTING_MIRROR_URL

---

pwiz_tools/Skyline/Model/Irt/DbIrtPeptide.cs
pwiz_tools/Skyline/SettingsUI/EditOptimizationLibraryDlg.cs
pwiz_tools/Skyline/SettingsUI/Irt/EditIrtCalcDlg.cs
pwiz_tools/Skyline/SettingsUI/PeptideGridViewDriver.cs
pwiz_tools/Skyline/SettingsUI/SimpleGridViewDriver.cs

Fixes some bugs with grid view, e.g. pressing delete/backspace when a cell is selected where the underlying property can't be set to `string.Empty`

SimpleGridViewDriver fixes

---

scripts/misc/nightly_trigger_and_paths_config.py

* disabled nightly smart trigger for Skyline code coverage build because there's currently no way in the smart trigger code to only trigger for PR merges and not for PR commits
Instead I will re-enable the nightly VCS trigger on TeamCity.

* disabled nightly smart trigger for Skyline code coverage build

---

pwiz_tools/Bumbershoot/idpicker/IDPicker.csproj
scripts/misc/tc-perftests.bat

(I'm not sure why this would be different between the Parag AWS AMI and the MacCoss one, but it's what I noticed taking up space on Z: when I logged in.)

* added clearing of z:\temp to tc-perftests.bat

---

pwiz_tools/Skyline/FileUI/ImportTransitionListColumnSelectDlg.cs

Fixed "Unhandled Error" that could happen doing Import Transition List if .skyd file is modified (reported anonymously on Exception Web)

Handle exceptions in ImportTransitionListColumnSelectDlg.CheckForErrors

---

pwiz_tools/Skyline/TestFunctional/LibraryExplorerTest.cs

1. Need to use "ShowAndDismissDlg" instead of "RunDlg" because PR #2426 made it so that RunDlg waits until the method which showed the dialog returned.
2. Move some code inside of a RunUI because it might throw cross thread exception.

Fix "TestLibraryExplorerAsSmallMolecules":

---

pwiz_tools/Skyline/Alerts/ReportErrorDlg.cs
pwiz_tools/Skyline/Alerts/ReportShutdownDlg.cs
pwiz_tools/Skyline/Properties/Resources.Designer.cs
pwiz_tools/Skyline/Properties/Resources.resx
pwiz_tools/Skyline/Skyline.Designer.cs
pwiz_tools/Skyline/Skyline.cs
pwiz_tools/Skyline/Skyline.resx
pwiz_tools/Skyline/TestFunctional/ReportErrorDlgTest.cs

1. Set "ShowInTaskbar" to "True" because the dialog does not have a parent.
2. Use entire text of error for the detail section of the dialog (used to look for "StackTrace:" but that is no longer part of the message).
3. Add menu item "Help > Crash Skyline" which only shows up if you hold down ctrl+shift while dropping Help menu.

Improvements to ReportShutdownDlg:

---

pwiz_tools/Skyline/FileUI/PeptideSearch/SearchSettingsControl.cs
pwiz_tools/Skyline/ToolsUI/PythonInstaller.cs
pwiz_tools/Skyline/ToolsUI/RInstaller.cs
pwiz_tools/Skyline/Util/UtilInstall.cs

1. Use MessageDlg.ShowWithExeption to show the error instead of ReportErrorDlg.
2. Add out parameter "error" to IAsynchronousDownloadClient.DownloadFileAsync so that error can be displayed to user.
(Hoping to get more information about why Will's download is still failing even after the Skyline-daily patch)

Better error handling when downloading MSGF+ fails:

---

pwiz_tools/Skyline/Model/DdaSearch/MsFraggerSearchEngine.cs

* added "keep-intermediate-files" option for MSFragger search engine to aid in debugging

MSFragger keep intermediate files option

---

pwiz_tools/Skyline/Model/PeptideGroupDocNode.cs

Add Assume.AreEqual(group.FastaSequenceList.Count, proteinMetadata.ProteinMetadataList.Count) to make sure single protein metadata is never assigned to a FastaSequenceGroup.
(This will be helpful when we come up with a fix for a bug that was reported by Rich)

Add "Assume.AreEqual" to PeptideGroupDocNode.ChangeProteinMetadata

---

pwiz_tools/Skyline/SkylineTester/Main.cs
pwiz_tools/Skyline/SkylineTester/SkylineTesterWindow.Designer.cs
pwiz_tools/Skyline/Test/UtilTest.cs
pwiz_tools/Skyline/TestRunner/Program.cs

- Make SafeDeleteTest safe for parallel testing by saving to the TestResults folder
- Fix generating TestRunner.exe call for parallel testing to work with debug builds
- Add some keyboard mnemonics to SkylineTester for quicker runs without using the mouse

Skyline: Test improvements while working on parallel testing

---

pwiz_tools/Skyline/TestData/CommandLineTest.cs

- Mark it as NoParallelTesting to reduce failures during parallel testing

Skyline: Move --warn-on-failure testing to ConsoleMultiWarnOnFailureImportTest

---

pwiz_tools/Skyline/Controls/SequenceTree.cs
pwiz_tools/Skyline/Properties/Settings.Designer.cs
pwiz_tools/Skyline/Properties/Settings.settings
pwiz_tools/Skyline/app.config

Changed behavior to prevent "Replicates > Best" setting from being remembered after exiting Skyline because it can be very confusing if Skyline is always switching what the current replicate is whenever the currently selected peptide changes (reported most recently by Claudia)

Use a static variable instead of "Settings.Default.ShowTreeReplicateEnum"

---

pwiz_tools/Skyline/TestFunctional/DocumentFileLockingTest.cs

CodeInspectionTest was finding "RunUI()" and "OkDialog" inside of a comment. Removing the parentheses enabled the test to pass.

Fix CodeInspectionTest

---

pwiz_tools/Skyline/Controls/Graphs/GraphChromatogram.cs

Fixed selecting peak by clicking on retention time number above candidate peak (reported by Juan)

Fix choosing peak by clicking on retention time above found peak

---

pwiz_tools/Skyline/Model/Irt/IrtPeptidePicker.cs
pwiz_tools/Skyline/SettingsUI/Irt/EditIrtCalcDlg.cs

Enabled using crosslinked peptides in Edit iRT Calculator dialog (reported by Juan)

Support for crosslinked peptides in iRT databases

---

pwiz_aux/msrc/utility/vendor_api/Shimadzu/ShimadzuReader.cpp

- fixed converting Shimadzu DDA precursor m/z values from integers (1e9 instead of 1e5)
I wish we had a small Shimadzu DDA test file.

Fix Shimadzu DDA precursor m/z values

---

pwiz_tools/Skyline/TestFunctional/AccessServerTest.cs
pwiz_tools/Skyline/TestFunctional/DetectionsPlotTest.cs
pwiz_tools/Skyline/TestFunctional/DocumentSizeErrorTest.cs
pwiz_tools/Skyline/TestFunctional/EditCustomMoleculeDlgTest.cs
pwiz_tools/Skyline/TestFunctional/EditNoteTest.cs
pwiz_tools/Skyline/TestFunctional/EditStaticModTest.cs
pwiz_tools/Skyline/TestFunctional/ExportMethodDialogTest.cs
pwiz_tools/Skyline/TestFunctional/IonMobilityTest.cs
pwiz_tools/Skyline/TestFunctional/IrtTest.cs
pwiz_tools/Skyline/TestFunctional/IsolationSchemeTest.cs
pwiz_tools/Skyline/TestFunctional/LabelPeakPickingTest.cs
pwiz_tools/Skyline/TestFunctional/LibraryBuildTest.cs
pwiz_tools/Skyline/TestFunctional/ManageResultsTest.cs
pwiz_tools/Skyline/TestFunctional/PythonInstallerTest.cs
pwiz_tools/Skyline/TestFunctional/ReintegrateDlgTest.cs
pwiz_tools/Skyline/TestFunctional/TestPeakAreaDotpGraph.cs
pwiz_tools/Skyline/TestPerf/PerfImportAgilentSpectrumMillRampedIMSTest.cs
pwiz_tools/Skyline/TestPerf/PerfMeasuredDriftTimes.cs
pwiz_tools/Skyline/TestPerf/PerfMeasuredInverseK0.cs
pwiz_tools/Skyline/TestTutorial/CustomReportsTutorialTest.cs
pwiz_tools/Skyline/TestTutorial/GroupedStudiesTutorialTest.cs
pwiz_tools/Skyline/TestTutorial/SmallMolMethodDevCEOptTutorial.cs
pwiz_tools/Skyline/TestUtil/TestFunctional.cs

- Many cases were fine with WaitForClosedForm() after the RunUI, but some not
- This increases consistency in using OkDialog(dlg, dlg.OkDialog) and may fix intermittent failures

Skyline: Find and replace dlg.OkDialog() inside RunUI(() => {...})

---

pwiz_tools/Shared/Common/DataBinding/Controls/NavBar.Designer.cs

Changed so that the find box on the Document Grid starts out case insensitive (requested by Mike)

Make find box on Document Grid case insensitive by default

---

pwiz_tools/SeeMS/DataGridViewAutoFilter/DataGridViewAutoFilterColumnHeaderCell.cs
pwiz_tools/SeeMS/Dialogs/SpectrumListForm.Designer.cs
pwiz_tools/SeeMS/Dialogs/SpectrumListForm.cs
pwiz_tools/SeeMS/Dialogs/TreeViewForm.Designer.cs
pwiz_tools/SeeMS/Dialogs/TreeViewForm.cs
pwiz_tools/SeeMS/Dialogs/TreeViewForm.resx

- added detailed tooltips for several columns in SeeMS, accessed by clicking rather than hovering
- added ability to select multiple values (by holding Ctrl while clicking) in the spectrum/chromatogram column AutoFilter lists

SeeMS detail tooltips and filter multiselect

---

pwiz/data/msdata/SpectrumListBase.cpp
pwiz/data/vendor_readers/ABI/SpectrumList_ABI.cpp
pwiz/utility/bindings/CLI/common/IterationListener.cpp
pwiz/utility/bindings/CLI/common/IterationListener.hpp
pwiz_aux/msrc/utility/vendor_api/ABI/WiffFile2.ipp
pwiz_aux/msrc/utility/vendor_api/Waters/WatersRawFile.hpp
pwiz_tools/MSConvertGUI/MainLogic.cs
pwiz_tools/MSConvertGUI/Program.cs
pwiz_tools/MSConvertGUI/ProgressForm.cs

I don't know if it's really ALL instruments that can make WIFF2s, but it's a lot more than just the X500 now.
Although the new SDK can read MRM chromatograms, it can't tell you the Q3 mass for the chromatograms it gives you. I have reported that defect to Sciex. In the meantime I added a warning that WIFF2 MRM/SIM data should point at the WIFF file instead, which led me to discover that MSConvertGUI wasn't displaying the stderr warnings that msconvert.exe shows. I spent a lot of time trying to read the stderr on the .NET side without modifying the C++ side; it might be possible but I couldn't figure it out, so there's a new C function in the binding that will redirect cerr/cout output to a callback function. This might also be useful in Skyline when importing results.

Update WIFF2 SDK to support all(?) instruments

---

pwiz_tools/Skyline/Skyline.csproj

The following files were marked as "Prerequisite" instead of "Include": Clearcore2.Data.CommonInterfaces.dll
Clearcore2.Data.dll
Sciex.Data.SimpleTyples.dll
Clearcore2.RawXYProcessing.dll
This is similar to a problem that was fixed in pull request #1835
Fixed error reading any wiff files by latest Skyline-daily (reported by Becker)

Add missing sciex dll's to ClickOnce installer.

---

pwiz_tools/Skyline/Model/Import.cs
pwiz_tools/Skyline/Model/Proteome/ProteinAssociation.cs

Fix bug where protein descriptions assigned by "Associate Proteins" would disappear when the document was saved and reloaded (reported by Mike)

Associate proteins description fix (#2501)

---

pwiz_tools/Skyline/Model/Results/ChromDataSet.cs
pwiz_tools/Skyline/Model/Results/MedianPeakShape.cs
pwiz_tools/Skyline/Model/Results/PeakIntegrator.cs
pwiz_tools/Skyline/Model/Results/TimeIntensities.cs
pwiz_tools/Skyline/TestData/Results/TimeIntensitiesTest.cs

Fix error if SRM chromatogram has zero points in it (reported by Regine)
Fix performance problem calculating the "Shape Correlation" value for Transition Results:
1. Reduce number of calls to "BinarySearch" in "TimeIntensities.GetInterpolatedIntensity" by remembering the last index.
2. Use static method "Statistics.QNthItem" in "MedianPeakShape.GetMedianPeakShape" to calculate medians without having to construct new Statistics objects.

Speed up calculating "Shape Correlation" for Transition Results

---

pwiz_tools/Skyline/Model/Results/ChromatogramCache.cs

Fixed error doing "Save As" on document with very large .skyd file after removing a replicate.
If "ChromatogramCache.OptimizeToPath" takes a long time to run, and there is a settings change going on in the background, then two threads were trying to use the same ReadStream at the same time and that resulted in an error about how "FileStream" is not thread safe.

Fix exception doing Save As on document with very large .skyd file.

---

pwiz_tools/Skyline/Model/DdaSearch/MsgfPlusSearchEngine.cs

* changed MSGF+ mods file to be created as a string and only write it to disk when running MS-GF+ so it can be cleaned up in the finally block
I made this change in the course of looking for the tempfile-left-over bug. Still makes sense to me even after you fixed the bug.

MSGF+ mods as string

---

pwiz_tools/Skyline/TestRunner/Program.cs
pwiz_tools/Skyline/TestRunnerLib/RunTests.cs
pwiz_tools/Skyline/TestUtil/ExtensionTestContext.cs

* added try/catch around async operations for parallel mode (to reduce whitespace changes and prepare for future refactoring I moved most of the code of these operations to local functions)
* added parallel mode check that at least one worker has connected within 15 seconds and moved the "check BOTH private and public" note to the error when no worker connects)

Parallel mode error handling and connection check

---

pwiz_tools/BiblioSpec/src/PwizReader.cpp
pwiz_tools/BiblioSpec/src/PwizReader.h

- fixed BiblioSpec to read ion mobility vendor files in combined spectra form (addresses BiblioSpec taking forever to try to read MSAmanda searches direct from ddaPASEF .d)

Fix BiblioSpec combine ion mobility

---

pwiz_tools/Skyline/TestTutorial/AuditLogTutorialTest.cs

Fix intermittent failure in TestAuditLogTutorial (failure would never happen on Nightly because failure required Skyline onscreen)

Fix intermittent failure in TestAuditLogTutorial.

---

pwiz_tools/Skyline/TestFunctional/BatchCalibrationTest.cs

Add some extra information to the assert in BatchCalibrationTest to try to track down intermittent failure.

Add some extra information to the assert in "BatchCalibrationTest"

---

pwiz_tools/Skyline/Model/DocSettings/Loss.cs
pwiz_tools/Skyline/Model/PeptideDocNode.cs
pwiz_tools/Skyline/Model/TransitionDocNode.cs
pwiz_tools/Skyline/Model/TransitionGroupDocNode.cs
pwiz_tools/Skyline/Properties/Resources.Designer.cs
pwiz_tools/Skyline/Properties/Resources.ja.resx
pwiz_tools/Skyline/Properties/Resources.resx
pwiz_tools/Skyline/Properties/Resources.zh-CHS.resx
pwiz_tools/Skyline/Skyline.csproj
pwiz_tools/Skyline/TestFunctional/EditNeutralLossesTest.cs
pwiz_tools/Skyline/TestFunctional/TestFunctional.csproj
pwiz_tools/Skyline/Util/Util.cs

Fixed bug where adding a new neutral loss to a static modification could result in a document that could not be reopened after it was saved. Fixed bug where "ShapeCorrelation" would not round-trip when saving large document.

Fix some issues revealed by PR#2405 ("AssertSerializable")

---

pwiz_tools/Skyline/Skyline.cs

I noticed that when TestToolService fails, the contents of the Immediate Window includes all of the text from earlier tests that have run (everything since the last time ImmediateWindow.Clear was called by any of a couple of tests. I cannot think of any reason that we would want the immediate window to behave that way so I will change "_skylineTextBoxStreamWriterHelper" to be an instance variable instead of static.

Change "_skylineTextBoxStreamWriterHelper" to be instance variable

---

pwiz_tools/Skyline/Test/TypedMassTest.cs

The check is only performed in debug builds for performance reasons.
No user impact.

Fix a test that only failed in debug build because it was comparing unlike (mono vs avg) mass types

---

pwiz_tools/Skyline/TestData/CommandLineRefineTest.cs

@nickshulman Is there a better way to do this (get localized system error messages) that I missed?

* fixed ConsoleInvalidValuesTest

---

pwiz_tools/Skyline/SkylineTester/Main.cs

- avoids file corruption that can cause SkylineNightly to fail indefinitely

Skyline: Delete TestRunner.exe user.config files before SkylineTester runs it

---

pwiz_tools/Skyline/Model/Irt/IrtDb.cs
pwiz_tools/Skyline/SkylineFiles.cs
pwiz_tools/Skyline/TestUtil/TestFilesDir.cs

This fix does two things:
1. Get rid of "_sessionFactory" in "IrtDb" class, and instead open and dispose the session factory whenever it is needed.
2. Add calls to GC.Collect and GC.WaitForPendingFinalizers before trying to delete files.
This seems to make the test failure less likely to happen, but it is hard to tell for sure.
I am still running tests on my computer.

Attempt to fix TestAssayLibraryImport

---

pwiz_tools/Skyline/Program.cs
pwiz_tools/Skyline/Test/AnalyticsTest.cs
pwiz_tools/Skyline/TestRunner/Program.cs

* fixed SendGa4AnalyticsHitTest to accept 200 response, but print response body as debug output
* improved performance of stale Docker image check
* added "all" option for languages in TestRunner
If I go ahead and add 200 as an accepted value for the test, it'll be a problem to figure out which computers returned 200 instead of 204 in order to check the new response output. :(

* fixed SendGa4AnalyticsHitTest to accept 200 response

---

.github/workflows/cherrypick-pr-to-release.yml

This doesn't actually need to be updated on release branch because the action will always be run based on master or a PR based on master, but it's a simple test that can't affect the release.

* updated cherrypick action branch to 23.1

---

pwiz_aux/msrc/utility/vendor_api/thermo/RawFile.cpp
pwiz_aux/msrc/utility/vendor_api/thermo/RawFileTypes.h
pwiz_tools/commandline/msconvert.cpp

Revert "- fixed reading instrument model for very old Thermo RAW files which may store instrument model only in status log - added commandline parameters for msconvert to output file"
This reverts commit a2350d7526d1c321fc658420b3a1b089ac64cdd1.

Revert possible trigger for DiaUmpireTutorial failures

---

pwiz/data/vendor_readers/Thermo/Reader_Thermo_Test.data/BSA-FT-ETD-centroid.mzML
pwiz/data/vendor_readers/Thermo/Reader_Thermo_Test.data/BSA-FT-ETD.mzML
pwiz/data/vendor_readers/Thermo/Reader_Thermo_Test.data/BSA-FT-HCD-centroid.mzML
pwiz/data/vendor_readers/Thermo/Reader_Thermo_Test.data/BSA-FT-HCD.mzML
pwiz/data/vendor_readers/Thermo/Reader_Thermo_Test.data/FT-HCD-MSX-centroid.mzML
pwiz/data/vendor_readers/Thermo/Reader_Thermo_Test.data/FT-HCD-MSX.mzML
pwiz/data/vendor_readers/Thermo/Reader_Thermo_Test.data/IsolationMzOffset-ReportedMassOffset-centroid.mzML
pwiz/data/vendor_readers/Thermo/Reader_Thermo_Test.data/IsolationMzOffset-ReportedMassOffset.mzML
pwiz/data/vendor_readers/Thermo/SpectrumList_Thermo.cpp

- added mass resolving power to scans when "FT Resolution" or "Orbitrap Resolution" item is available in Thermo RAW scan trailer
Requested on psidev mailing list.

- added mass resolving power to Thermo scans

---

.gitignore
pwiz/analysis/spectrum_processing/SpectrumList_PeakPicker.cpp
pwiz/data/vendor_readers/.gitattributes
pwiz/data/vendor_readers/ABI/Reader_ABI_Test.data/.gitattributes
pwiz/data/vendor_readers/Agilent/Reader_Agilent_Test.data/.gitattributes
pwiz/data/vendor_readers/Bruker/Reader_Bruker_Test.data/.gitattributes
pwiz/data/vendor_readers/Mobilion/Reader_Mobilion_Test.data/.gitattributes
pwiz/data/vendor_readers/Shimadzu/Reader_Shimadzu_Test.data/.gitattributes
pwiz/data/vendor_readers/Thermo/Reader_Thermo_Test.data/.gitattributes
pwiz/data/vendor_readers/UIMF/Reader_UIMF_Test.data/.gitattributes
pwiz/data/vendor_readers/Waters/Reader_Waters_Test.data/.gitattributes

- removed "Warning: vendor peakPicking was requested, but is unavailable" message that showed even when no spectra in the file need centroiding
* consolidated .gitattributes files from most vendor test data directories and set mzML files to be diffable in the consolidated file
* made more specific .gitignore rules so new mzML files in vendor test data directories won't be ignored

- removed "Warning: vendor peakPicking was requested" even when no spectra in the file need centroiding

---

.gitignore
pwiz/analysis/spectrum_processing/SpectrumList_PeakPicker.cpp
pwiz/data/vendor_readers/.gitattributes
pwiz/data/vendor_readers/ABI/Reader_ABI_Test.data/.gitattributes
pwiz/data/vendor_readers/Agilent/Reader_Agilent_Test.data/.gitattributes
pwiz/data/vendor_readers/Bruker/Reader_Bruker_Test.data/.gitattributes
pwiz/data/vendor_readers/Mobilion/Reader_Mobilion_Test.data/.gitattributes
pwiz/data/vendor_readers/Shimadzu/Reader_Shimadzu_Test.data/.gitattributes
pwiz/data/vendor_readers/Thermo/Reader_Thermo_Test.data/.gitattributes
pwiz/data/vendor_readers/UIMF/Reader_UIMF_Test.data/.gitattributes
pwiz/data/vendor_readers/Waters/Reader_Waters_Test.data/.gitattributes

- removed "Warning: vendor peakPicking was requested, but is unavailable" message that showed even when no spectra in the file need centroiding
* consolidated .gitattributes files from most vendor test data directories and set mzML files to be diffable in the consolidated file
* made more specific .gitignore rules so new mzML files in vendor test data directories won't be ignored

Cherry pick 2654 to release

---

pwiz/data/msdata/MSData.cpp
pwiz/data/msdata/MSData.hpp
pwiz/data/msdata/SpectrumListBase.cpp
pwiz/data/msdata/SpectrumListBase.hpp
pwiz_tools/BiblioSpec/src/BlibBuild.cpp
pwiz_tools/BiblioSpec/src/BuildParser.cpp
pwiz_tools/BiblioSpec/src/BuildParser.h
pwiz_tools/BiblioSpec/src/MascotResultsReader.cpp
pwiz_tools/BiblioSpec/src/MaxQuantReader.cpp
pwiz_tools/BiblioSpec/src/MzIdentMLReader.cpp
pwiz_tools/BiblioSpec/src/PepXMLreader.cpp
pwiz_tools/BiblioSpec/src/PercolatorXmlReader.cpp
pwiz_tools/BiblioSpec/src/PrideXmlReader.cpp
pwiz_tools/BiblioSpec/src/ProteinPilotReader.cpp
pwiz_tools/BiblioSpec/src/ProxlXmlReader.cpp
pwiz_tools/BiblioSpec/src/PwizReader.cpp
pwiz_tools/BiblioSpec/src/PwizReader.h
pwiz_tools/BiblioSpec/src/SQTreader.cpp
pwiz_tools/BiblioSpec/src/TSVReader.cpp
pwiz_tools/BiblioSpec/src/WatersMseReader.cpp
pwiz_tools/BiblioSpec/src/mzTabReader.cpp
pwiz_tools/BiblioSpec/tests/inputs/mismatched-nativeid-format.mzid
pwiz_tools/BiblioSpec/tests/inputs/mismatched-scan-numbers.pepXML
pwiz_tools/Shared/BiblioSpec/BlibBuild.cs
pwiz_tools/Shared/Common/SystemUtil/ProcessRunner.cs
pwiz_tools/Skyline/Model/DdaSearch/MsFraggerSearchEngine.cs
pwiz_tools/Skyline/TestFunctional/LibraryBuildTest.cs
pwiz_tools/Skyline/TestUtil/TestFilesDir.cs
pwiz_tools/Skyline/Util/DataSourceUtil.cs

- fixed MSFragger DDA search to handle DDA PASEF data correctly
- added log output of the count of BiblioSpec PSMs that do not pass score filter and improved error message when score filter is the cause of no PSMs being added
* moved Skyline BlibBuild stdin file to input file directory and set it to only be deleted if library build succeeds (so the file will still be available to rerun the BlibBuild command if the library build fails)
* added ProcessRunner lines starting with "warning" to error log

MSFragger DDA PASEF search and better BiblioSpec errors

---

pwiz_tools/Skyline/Jamfile.jam
pwiz_tools/Skyline/Skyline.sln

Make it so that Skyline project depends on SkylineCmd project instead of the other way around.
As far as I can tell this fixes the problem where doing a build immediately after having done a clean build fails.

Switch dependency ordering between SkylineCmd and Skyline projects

---

pwiz_tools/Bumbershoot/quameter/quameter.cpp

- Use a `double` as initial value for the `accumulate` call to calculate the TIC in `quameter`. Closes #2684 .

fix: quameter TIC: avoid summing of double and integer values

---

pwiz_tools/Skyline/TestRunner/Program.cs

Not sure why, but the default 60 timeout for TestRunner connecting to Docker workers often isn't enough on my Win10 machine. This change lets me set an environment variable "SKYLINE_TESTRUNNER_DOCKER_TIMEOUT_SEC" to extend that to whatever seems to work.
This value can already be set at the commandline, but I don't want to have to do that every time I start working in a new branch.

Add an optional environment variable to override default parallel test worker connection timeout

---

pwiz_tools/Skyline/Model/Results/ChromatogramCache.cs
pwiz_tools/Skyline/TestFunctional/EditSpectrumFilterTest.cs

Fixed bug where Spectrum Filters in small molecule documents result in "Chromatogram Information Unavailable" (reported by Tara)

Fix spectrum filters for small molecule documents

---

pwiz_tools/Shared/PanoramaClient/PanoramaDirectoryPicker.cs
pwiz_tools/Shared/PanoramaClient/PanoramaFilePicker.cs
pwiz_tools/Shared/PanoramaClient/PanoramaFolderBrowser.cs
pwiz_tools/Skyline/Executables/SkylineBatch/SkylineBatch/RemoteFileControl.cs
pwiz_tools/Skyline/Executables/SkylineBatch/SkylineBatch/RemoteSourceForm.cs
pwiz_tools/Skyline/SkylineFiles.cs
pwiz_tools/Skyline/TestConnected/PanoramaClientDownloadTest.cs
pwiz_tools/Skyline/TestFunctional/TestPanoramaClient.cs

Use for LongWaitDlg was causing a Thread handle leak because was creating a control on a background thread and adding event handlers to that control. I don't think the LongWaitDlg was serving its intended purpose. So, I just removed it. I am left wondering how this code should actually be querying the web server for its JSON information in a way that involves a LongWaitDlg that can actually be canceled. But, I left that for another time. The existing code didn't do that, and it wasn't doing anything inside LongWaitDlg.PerformWork() that would ever be slow enough to require the progress form to show, and it had not support for canceling.
I did a bit of code clean up and simplification along the way also.

Skyline: clean-up and fix leak in new panorama client code

---

pwiz_tools/Shared/PanoramaClient/PanoramaDirectoryPicker.cs
pwiz_tools/Shared/PanoramaClient/PanoramaFilePicker.cs
pwiz_tools/Skyline/Executables/SkylineBatch/SkylineBatch/App.config
pwiz_tools/Skyline/Executables/SkylineBatch/SkylineBatch/RemoteFileControl.cs
pwiz_tools/Skyline/Executables/SkylineBatch/SkylineBatch/RemoteSourceForm.Designer.cs
pwiz_tools/Skyline/Executables/SkylineBatch/SkylineBatch/RemoteSourceForm.cs
pwiz_tools/Skyline/Executables/SkylineBatch/SkylineBatch/RemoteSourceForm.resx
pwiz_tools/Skyline/Executables/SkylineBatch/SkylineBatchTest/RemoteFileSourceFunctionalTest.cs
pwiz_tools/Skyline/Properties/Resources.Designer.cs
pwiz_tools/Skyline/Properties/Resources.resx
pwiz_tools/Skyline/Skyline.resx
pwiz_tools/Skyline/SkylineFiles.cs
pwiz_tools/Skyline/TestConnected/PanoramaClientDownloadTest.cs

- Re-introduce a progress form during File > Open From Panorama with LongOperationRunner
- Add a mnemonic to File > Open From Panorama
- Change the form tile for File > Open From Panorama to "Open From Panorama" (was "Panorama Folders")
- Fix the panorama button in RemoteSourceForm to make it anchored right

Skyline: Fixes for new PanoramaClient UI in Skyline and SkylineBatch

---

pwiz_tools/Skyline/Model/Export.cs

When exporting Agilent CE Optimization Transition Lists, stop adding 0.01 to the Q3 m/z values (requested by Marilyn)

Don't add 0.01 to Q3 m/z values for Agilent CE Opt transition lists

---

pwiz/data/vendor_readers/ABI/SpectrumList_ABI.cpp
pwiz_tools/commandline/msconvert.cpp

- fixed calculation of bogus isolation window offsets when WIFF2 file returns 0 for lower/upper window bounds
- changed msconvert to replace non-printable filename characters with underscore (like it already does for `\/*:?<>|"`) (reported by Robert)

- fixed calculation of bogus WIFF2 isolation window offsets

---

pwiz_tools/Skyline/Model/DocSettings/Prediction.cs
pwiz_tools/Skyline/TestFunctional/NonLinearRegressionTest.cs

Fixed error that sometimes happens choosing "Kernel Density Estimation" on run to run regression graph (reported on exception web)

Fix error choosing "Kernel Density Estimation" on run to run regression

---

pwiz_tools/Skyline/Model/Results/SpectraChromDataProvider.cs

Fix case where the TIC chromatograms and the QC traces get all scrambled up if there is any Retention Time filtering going on.
Fixed incorrect TIC area in documents with QC traces and transition full scan retention time filtering (reported by Markus)

Fix TIC chromatogram (#2739)

---

pwiz_tools/Skyline/TestData/CommandLineTest.cs

Fix test failures on parallel testing for ConsoleExportSpecLibTest and ConsoleExportMProphetTest

Fix test failures on parallel testing for ConsoleExportSpecLibTest and ConsoleExportMProphetTest

---

pwiz_tools/Skyline/TestFunctional/ToolServiceTest.cs
pwiz_tools/Skyline/TestUtil/AbstractUnitTest.cs

N.B. you can argue that placing the logic in AbstractUnitTest instead of the test itself is overly ornate, but I wanted it near other machine-specific test logic.

Avoid running TestToolService on machines where it is consistently flaky (just BRENDANX-UW7 for now)

---

pwiz_tools/Skyline/Jamfile.jam
pwiz_tools/Skyline/Skyline.csproj

If a file "Model/Prosit/Config/PrositConfig_production.xml" is available, the Skyline Jamfile will always copy it to PrositConfig.xml for embedding in the exe. When the bjam commandline includes "--official" the build still fails if "Model/Prosit/Config/PrositConfig_production.xml" is not available.
Also, remove a stale reference to Model\Prosit\Config\UpdatePrositConfiguration.bat in the .csproj file.
I'll update the wiki page once this is merged to master.

Change the way developers can enable Prosit on local builds

---

pwiz_tools/Skyline/TestPerf/EncyclopeDiaSearchTutorialTest.cs
pwiz_tools/Skyline/TestTutorial/PeakPickingTutorialTest.cs
scripts/misc/tc-perftests.bat

* split tc-perftests.bat on TeamCity into tutorials and perftests and enabled pass0 testing for tutorials

Enable pass0 testing for tutorials on TeamCity

---

pwiz_tools/Skyline/Model/Results/ChromHeaderInfo.cs
pwiz_tools/Skyline/Model/Results/MeasuredResults.cs

Fixed error right-clicking on chromatogram graph that happens with some documents where chromatograms had been extracted by Skyline-daily version 23.0.9.157 (reported by Mike)

Fix NRE in MeasuredResults.QcTraceNames

---

pwiz_aux/msrc/utility/vendor_api/Bruker/TsfData.cpp

- fixed Bruker TSF reader crashing when enumerating chromatograms when the file has empty spectra (reported by Ho-Tak)

- fixed Bruker TSF reader crashing when enumerating chromatograms

---

pwiz_tools/Skyline/Controls/Graphs/AreaReplicateGraphPane.cs

Fixed error displaying dot product line on Peak Area Replicate Comparison graph when currently selected peptide has no transitions of the type (precursor or product) currently being displayed.

Fix IndexOutOfRangeException in AreaReplicateGraphPane.UpdateGraph

---

pwiz_tools/Skyline/Executables/SkylineBatch/SkylineBatch/MainSettings.cs

Fixed spurious Skyline batch error about empty directory when directory contained .d folders (reported by Shawn)

Fix Skyline batch warning about empty directory

---

pwiz_tools/Skyline/TestData/ConsoleVerboseExceptionsTest.cs

Remove localized portion of the stack trace message

Fix Nightly failure in ConsoleVerboseExceptionsTest

---

pwiz_tools/Skyline/Model/TransitionGroupDocNode.cs
pwiz_tools/Skyline/Test/MQuestScoringTest.cs

Reduced the minimum number of values required for a dot product to be calculated from 3 to 2 (requested by Philip)
This change makes Skyline calculate the dot products even when there are only 2 transitions.
(An earlier email I sent said that this change caused about a dozen tests to fail, but I think it was just the one test "MQuestSummaryScoreTest". I had other changes on my machine which were causing other tests to fail)

Reduce the minimum ions required for a dot product from 3 to 2

---

pwiz_tools/Skyline/Controls/Graphs/SummaryReplicateGraphPane.cs
pwiz_tools/Skyline/Model/Results/ChromInfoData.cs

Fixed error in Retention Times Replicate Comparison graph when aligning retention times and there are missing results (reported on Exception Web)

Fix NRE in Retention Times Replicate Comparison

---

pwiz_tools/Shared/PanoramaClient/PanoramaFilePicker.cs
pwiz_tools/Shared/PanoramaClient/PanoramaFolderBrowser.cs
pwiz_tools/Skyline/TestConnected/PanoramaClientDownloadTest.cs
pwiz_tools/Skyline/TestFunctional/TestPanoramaClient.cs
pwiz_tools/Skyline/TestUtil/TestFunctional.cs

I made it so that PanoramaFilePicker.ClickFile and PanoramaFolderBrowser.SelectNode return a boolean so that the test can assert that the item to be clicked was actually there.
This should make it easier to figure out what is going wrong if this test ever fails in the future.

Improve failure messages when "TestPanoramaClient" or "PanoramaClientDownloadTest" fails.

---

pwiz_tools/Skyline/Model/Results/TimeIntensities.cs

Fixed error that could happen if DIA-NN chosen peak was outside of extracted chromatogram range (reported by Michele)

Fix error integrating zero-width peak

---

pwiz_tools/Skyline/CommandArgs.cs
pwiz_tools/Skyline/TestData/CommandLineTest.cs

- fixed --tran-product-*-special-ion commands not being processed if they are the only filter arguments passed

- fixed --tran-product-*-special-ion commands

---

pwiz_tools/Skyline/Controls/Graphs/GraphChromatogram.cs
pwiz_tools/Skyline/Model/Databinding/Entities/Transition.cs

Fixed unhandled error when selected QC trace is not present in a particular replicate (reported by Vyncent) Fixed truncation of report text copied to clipboard when report columns include "CleavageAa" (reported by Brendan)

Fix chromatogram and report bugs

---

pwiz_tools/Shared/CommonUtil/Collections/ReferenceValue.cs
pwiz_tools/Skyline/Test/ModEquivalentTest.cs

Also, fix incorrect implementation of "ReferenceValue.Equals" (unrelated to anything else).

Speed up "ModEquivalentTest".

---

pwiz_tools/Skyline/ToolsUI/ToolStoreDlg.cs

Use "ContentDispositionHeaderValue" to parse the content-disposition header value.

Fix Tool Store download.

---

pwiz_tools/Skyline/Properties/Settings.Designer.cs
pwiz_tools/Skyline/Properties/Settings.settings

Manual edits had made to the generated file "Settings.Designer.cs" instead of the correct thing of adding entries to "Settings.settings" and running the custom tool.

Add missing entries in "Settings.Settings"

---

pwiz_tools/Skyline/Model/Results/ChromInfoData.cs

Fix error in Replicate Area graph when a peptide has missing results for one replicate (reported on exception web)

Fix exception in PeptideChromInfoData.GetPeptideChromInfoDatas

---

pwiz_tools/Skyline/Model/DdaSearch/MSAmandaSearchWrapper.cs
pwiz_tools/Skyline/TestRunnerLib/RunTests.cs

* changed MSAmanda temporary directory to use standard ~SK temp prefix instead of ~SK_MSAmanda which should bring the path length issues under control on KAIPO-DEV

* changed MSAmanda temporary directory to use ~SK temp prefix

---

pwiz_tools/Shared/CommonUtil/Collections/CollectionUtil.cs
pwiz_tools/Shared/CommonUtil/Collections/NaturalComparer.cs
pwiz_tools/Skyline/Alerts/ShareResultsFilesDlg.cs
pwiz_tools/Skyline/FileUI/OpenDataSourceDialog.cs
pwiz_tools/Skyline/Model/Lib/ViewLibraryPepInfo.cs
pwiz_tools/Skyline/Properties/Resources.Designer.cs
pwiz_tools/Skyline/Properties/Resources.resx
pwiz_tools/Skyline/SettingsUI/ViewLibraryDlg.cs
pwiz_tools/Skyline/SettingsUI/ViewLibraryPepInfoList.cs
pwiz_tools/Skyline/Test/TextUtilTest.cs

* Peptides and/or molecules are shown in natural sort order (i.e. aware of numerical values embedded in strings) - this matters more for molecules with constructed names like "mass123.456", "mass123.0456" etc. For peptides it generally amounts to the same thing as a plain alphanumeric sort.
* We now show the number of things that match the filter rather than always just giving the total count.
* We remember the user's search string for each filter type as they choose and return to different filters.
* Fixed a bottleneck that was preventing display of ion mobility values in the library explorer.
This required a new natural sort class to complement the existing one, which turns out to be filename specific. The original doesn't understand that "z123.4056" comes before "z123.456" because it …

Library Explorer improvements inspired by larger small molecules libraries:

---

pwiz_tools/Skyline/Controls/Graphs/GraphChromatogram.cs
pwiz_tools/Skyline/Model/ElementLocators/ElementLocator.cs
pwiz_tools/Skyline/Test/ElementLocatorTest.cs

Fixed error using tool service to delete protein whose locator is "MoleculeGroup:/" (reported by Philip) Fixed error doing "Apply Peak to All" when one replicate has missing chromatograms (reported anonymously on exception web)

Fix ToolService error

---

pwiz_tools/Skyline/Skyline.csproj

Move all of the "Resources.Designer.cs" files to an earlier section in "Skyline.csproj". This seems to make it so that the "ReSharper - Move to Resource" dialog properly recognizes them as a file that you can move a string into.

Move the XxxResources.Designer.cs files in Skyline.csproj

---

pwiz_tools/Skyline/Controls/Databinding/SkylineViewContext.cs
pwiz_tools/Skyline/Model/Results/PeptideChromData.cs

Fixed unhandled error when exporting report definition to a .skyr file that cannot be written to (reported anonymously on exception web)
Also fixed to output a warning message to the Immediate Window if a single transition's chromatogram is being discarded because of the Explicit Retention Time.

Fix unhandled access denied "share report" error

---

pwiz_tools/Skyline/Test/MassListIonsTest.cs
pwiz_tools/Skyline/Util/Extensions/Text.cs

- Improve diagnostics to help understand why KAIPOT-PC1 fails MassListSpecialIonsTest

Skyline: Add string extension TextUtil.ToLines for line separation

---

pwiz_tools/Shared/Common/Controls/LiteDropDownList.cs
pwiz_tools/Skyline/EditUI/EditPepModsDlg.cs
pwiz_tools/Skyline/FileUI/ImportTransitionListColumnSelectDlg.cs
pwiz_tools/Skyline/TestFunctional/LiteDropdownListTest.cs

after list is cleared
- Remove Nick's prior attempt at a fix
- Expand LiteDropdownListTest to cover the problem case

Skyline: Fix LiteDropDownList use to set SelectedIndex to -1

---

pwiz_tools/Skyline/Model/GroupComparison/MatchExpression.cs
pwiz_tools/Skyline/Test/MatchExpressionTest.cs
pwiz_tools/Skyline/Test/Test.csproj

Fixed volcano plot formatting when Match Expression includes both fold change and p-value (reported by Alex)
This bug was introduced in Skyline-daily in January as part of the feature work peptide relative abundance graph.

Fix volcano plot formatting

---

pwiz_tools/Skyline/TestConnected/PanoramaClientDownloadTest.cs

- Add code to avoid deleting downloaded .sky.zip files before SkylineWindow is done with them

Skyline: Attempt to fix intermittent failures in PanoramaClientDownloadTest

---

pwiz_tools/Shared/CommonUtil/SystemUtil/PathEx.cs
pwiz_tools/Skyline/TestUtil/TestFilesDir.cs

On Macs2, the value of the system environment variable "SKYLINE_DOWNLOAD_PATH" is D:\Shared\SkylineDownloadPath.
Users can override that by setting their own value for that environment variable.
The cleanup code at the end of tests tries to rename some of the folders in there which fails because the folders are owned by someone else.
This change makes it so that this renaming does not happen if the folder path has been set in a system environment variable instead of a user level environment variable.
A different way that this could have been implemented would be to check whether the folder was owned by a different user, but the system/user environment variable seems more likely to work in all scenarios.

Fix using shared downloads folder on macs2

---

pwiz_tools/Skyline/Executables/AutoQC/AutoQC/MainForm.cs

Fixed error starting AutoQC on some computers (reported by Hayoung)
A user reported an NRE in "MainForm.ListViewSizeChanged" on the Skyline support board:
https://skyline.ms/announcements/home/support/thread.view?rowId=63931
I did the same fix to Skyline Batch a couple of months ago in PR #2879.

Fix NRE in AutoQC

---

pwiz_tools/Skyline/SettingsUI/ViewLibraryDlg.cs
pwiz_tools/Skyline/TestFunctional/RedundantComboBoxTest.cs
pwiz_tools/Skyline/TestTutorial/TargetedMSMSTutorialTest.cs

The contents of the ListBox in ViewLibraryDlg sometimes gets reset inside "ViewLibraryDlg_Shown" so it's best to continually set the SelectedIndex while waiting for the graph to update.

Fix TestTargetedMSMSTutorial and TestRedundantComboBox

---

pwiz_tools/Skyline/Test/AdductTest.cs
pwiz_tools/Skyline/Util/Adduct.cs

Skyline may occasionally improperly calculate the ion charge of complicated adduct descriptions (e.g. "[M+2CH3+Cl]" where we did not pick up on the contributed charge +2 of 2CH3, and only used the -1 of Cl). Adding an explicit charge declaration (e.g. "[M+2CH3+Cl]**+**") would formerly just cause an error, with Skyline insisting on its own calculated charge. Now Skyline respects the declared charge.
Skyline will still complain about obviously wrong declarations like "[M+2H]-".
(Also, "CH3" is now understood as imparting a charge of +1, so  "[M+2CH3+Cl]" is now handled properly.)
Reported by user Alex

Honor explicit adduct charge declarations (e.g. the trailing "+" in "[M+2CH3+Cl]+")

---

pwiz_tools/Skyline/Model/DocSettings/AbsoluteQuantification/RegressionFit.cs

Fixed "Matrix must be positive definite" error that sometimes happened with bilinear fit calibration curves (reported by Oleg)

Fix Bilinear Fit calibration curve error

---

pwiz_tools/Skyline/Model/Results/ChromDataProvider.cs

Reduce performance problems introduced by PR #2931. Only call "MsDataFileImpl.GetCollisionEnergy" if importing with collision energy optimization. This will speed up tests such as "TestLabelPeakPicking" which have SRM chromatograms but do not do CE optimization

Speed up reading SRM chromatograms

---

pwiz_tools/Skyline/Model/DocSettings/DataSettings.cs

TestRunner sets "Program.FunctionalTest" to "true" at the beginning of the test run, but that typically gets set back to false by "MyTestCleanup". When Program.FunctionalTest is true, audit logging was getting turned on when saving a document as part of "convert to small molecules" which then, because of PR #2919, the document gets assigned a new GUID which causes an Assert.AreEqual to fail comparing the settings of a round-trip document.

Fix some small molecule tests which have been failing when run individually from TestRunner.

---

.github/workflows/build_and_test.yml

macos-latest is now M1/ARM, which is not fully compiling and I don't have a way to develop/debug it.

Revert to macos-13 for GitHub actions

---

pwiz_tools/Skyline/Controls/Graphs/DetectionsPlotPane.cs

Fixed error showing Detections graph when document has no results (reported by Hillary)

Fix NRE in DetectionsPlotPane

---

pwiz/data/msdata/Serializer_mzXML.cpp
pwiz/data/msdata/SpectrumList_mzXML.cpp

- fixed scanWindow not being serialized properly in mzXML (startMz/endMz)
- fixed some cvParam ordering and unit issues causing metadata differences between mzML and round-tripped mzXML

mzXML serialization issues

---

pwiz_tools/Skyline/TestFunctional/InteractiveCommandLineToolTest.cs
pwiz_tools/Skyline/TestRunner/Program.cs
pwiz_tools/Skyline/TestUtil/TestFunctional.cs

* fixed using wrong base image when building always_up_runner on MACS2
* set NoParalleTesting on TestInteractiveCommandLineTool because MACS2 has some issue unzipping the nested ZIP file

MACS2 parallel testing fixes

---

pwiz_tools/Skyline/CommandArgUsage.Designer.cs
pwiz_tools/Skyline/CommandArgUsage.resx
pwiz_tools/Skyline/CommandArgs.cs
pwiz_tools/Skyline/CommandLine.cs
pwiz_tools/Skyline/EditUI/AssociateProteinsDlg.cs
pwiz_tools/Skyline/TestData/CommandLineTest.cs

- added --associate-proteins-fasta argument for associating existing …document peptides with a FASTA (i.e. without having to use --import-fasta); --import-fasta will still be used if --associate-proteins-fasta is not provided
* fixed valid value range for --associate-proteins-min-peptides (1-1000) but added error handling in AssociateProteinsDlg's MinPeptidesPerProtein property to convert a '0' value to '1'

--associate-proteins-fasta argument

---

pwiz_tools/Skyline/Controls/Graphs/GraphSpectrum.cs
pwiz_tools/Skyline/Controls/IonTypeSelectorControl.cs
pwiz_tools/Skyline/Model/DocSettings/Loss.cs
pwiz_tools/Skyline/Model/DocSettings/PeptideSettings.cs
pwiz_tools/Skyline/Model/Lib/LibraryRankedSpectrumInfo.cs
pwiz_tools/Skyline/TestFunctional/NeutralLossLibraryTest.cs

- Code to annotate MS/MS spectra based hide/show status on the formula keeping mass-only losses hidden always (fix requested by Dan - FragPipe team)

Skyline: Fix loss annotation in MS/MS spectra to work for mass-only losses

---

pwiz_tools/Skyline/Model/Koina/Config/KoinaConfig.cs
pwiz_tools/Skyline/TestFunctional/EncyclopeDiaSearchTest.cs

* added using keyword to disposable X509Store (shouldn't make much di…fference because it's only called once though)
* temporarily removed cancelability testing from EncyclopeDiaSearchTest because it may be leading to non-deterministic results

Koina fixes

---

pwiz_tools/Skyline/Model/Results/ChromatogramCache.cs
pwiz_tools/Skyline/Skyline.Designer.cs

Someone added code to Skyline.Designer.cs which uses "Settings.Default" which does not work in Visual Studio design viewToolStripMenuItem
Fixed rare unhandled error displaying chromatograms (reported a few times anonymously on exception web)

Fix going design view for "SkylineWindow"

---

pwiz_tools/Skyline/Executables/Installer/Product-template.wxs
pwiz_tools/Skyline/Skyline.csproj

(Hardklor.exe had already been added with the main feature finding commit)
Also, remove "hardklor_logo.png" from set of files that Skyline ships with since it is just supposed to be a resource.

Add "BullseyeSharp.exe" to administrator installer file list

---

pwiz_tools/Shared/Common/Controls/DataGridViewProgressBar.cs
pwiz_tools/Shared/Common/Controls/MultiProgressControl.Designer.cs

With the cancelability aspect of the test enabled, some DataGridViewProgressCells were not being disposed.

* fixed leak with EncyclopeDIA MultiProgressControl

---

pwiz_tools/Skyline/TestConnected/KoinaBuildLibraryFromCsvTest.cs
pwiz_tools/Skyline/TestConnected/KoinaBuildLibraryTest.cs
pwiz_tools/Skyline/TestConnected/KoinaConnectionTest.cs
pwiz_tools/Skyline/TestUtil/TestFunctional.cs

* added NoParallelTesting markup for Koina tests due to Docker runner not having access to root certificates needed; at some point I will fix this by exporting those root certs on the host, copying them to the runner, and having Skyline read them from a file

* added NoParallelTesting markup for Koina tests

---

pwiz_tools/Shared/CommonUtil/SystemUtil/CommonFormEx.cs
pwiz_tools/Skyline/Controls/Graphs/PeptidesAndTransitionGroups.cs
pwiz_tools/Skyline/Model/Results/ChromatogramCache.cs

Fixed graphs are sometimes blank when displaying more than 100 precursors at the same time (reported by Q)

Fix blank chromatogram graphs 

---

pwiz_tools/Shared/CommonUtil/SystemUtil/ProcessRunner.cs
pwiz_tools/Skyline/Model/Lib/EncyclopeDiaHelpers.cs

* changed temp directory logic for EncyclopeDIA in an attempt to fix nightly failures (I have not been able to reproduce, but I suspect the failure to find sqlite files is due to some collision in temp directories when multiple ED processes run at the same time)
* changed ProcessRunner.SetTmpDirForCleanup to use ProcessStartInfo's TMP variable if set

Attempt to fix EncyclopeDIA nightly failures

---

pwiz_tools/Skyline/TestUtil/AssertEx.cs

File comparison with "ignore path differences" wasn't working well for non-columnar files such as audit logs

---

pwiz_tools/Skyline/TestPerf/BullseyeSharpTest.cs

TestBullseyeSharp fails on TC code coverage build because as a UnitTest it wasn't explicitly checking the RunPerfTests flag

---

pwiz_tools/Skyline/Model/DocSettings/UniMod.cs
pwiz_tools/Skyline/Test/ModificationMatcherTest.cs
pwiz_tools/Skyline/Test/UniModStaticList.xml
pwiz_tools/Skyline/Test/UniModTest.cs

Get more specific about which Cysteine modifications (alkylation) are likely fixed modifications.
Add isobaric tag modifications to the set of modifications likely fixed.

Skyline: Improve Unimod variable modification defaults

---

pwiz/data/msdata/Reader.cpp
pwiz/data/msdata/Reader.hpp
pwiz/data/vendor_readers/ABI/Reader_ABI.cpp
pwiz/data/vendor_readers/Thermo/Reader_Thermo.cpp
pwiz_aux/msrc/utility/vendor_api/ABI/WiffFile.cpp
pwiz_aux/msrc/utility/vendor_api/ABI/WiffFile2.ipp
pwiz_tools/commandline/msconvert.cpp

- made failures reading WIFF metadata optionally fatal (depending on ignoreUnknownInstrumentError setting)
- fixed ignoreUnknownInstrumentError default value to be false
- fixed reading CE from WIFF file spectra
- added fallback handling for when calling centroiding or framing zeros on WIFF2 spectra throws exceptions but the profile/unframed spectra are available
- * added Reader::Config::instrumentMetadataError to encapsulate the "if(unknownInstrumentIsError) throw; else print warning" logic

Fixes for reading Sciex MRM3 files and better WIFF error handling

---

pwiz/data/msdata/ReaderTest.cpp
pwiz/data/vendor_readers/Bruker/Reader_Bruker.hpp
pwiz/data/vendor_readers/ExtendedReaderList.cpp

* fixed Reader_Bruker_TSF not being included in FullReaderList (so its supported file extensions did not get enumerated by SeeMS and MSConvertGUI)
Cherry picking to release so I can test it actually works...

* fixed Reader_Bruker_TSF not being included in FullReaderList

---

pwiz/data/msdata/Reader.cpp
pwiz/data/msdata/Reader.hpp
pwiz/data/vendor_readers/ABI/Reader_ABI.cpp
pwiz/data/vendor_readers/Thermo/Reader_Thermo.cpp
pwiz_aux/msrc/utility/vendor_api/ABI/WiffFile.cpp
pwiz_aux/msrc/utility/vendor_api/ABI/WiffFile2.ipp
pwiz_tools/commandline/msconvert.cpp

* added Reader::Config::instrumentMetadataError to encapsulate the "if(unknownInstrumentIsError) throw; else print warning" logic
- made failures reading WIFF metadata optionally fatal (depending on ignoreUnknownInstrumentError setting)
- fixed ignoreUnknownInstrumentError default value to be false
- fixed reading CE from WIFF file spectra
- added fallback handling for when calling centroiding or framing zeros on WIFF2 spectra throws exceptions but the profile/unframed spectra are available

Cherry pick 3023 to release

---

pwiz_tools/Skyline/Test/EncyclopeDiaHelpersTest.cs

* removed TestKoinaOutputToEncyclopediaLibraries that is slow to run (especially for a unit test) and offers basically no extra coverage over the TestEncyclopeDiaSearch functional test

* removed TestKoinaOutputToEncyclopediaLibraries

---

pwiz_tools/Shared/Common/DataBinding/Controls/ColumnListEditor.ja.resx
pwiz_tools/Shared/Common/DataBinding/Controls/ColumnListEditor.zh-CHS.resx
pwiz_tools/Shared/PanoramaClient/Properties/Resources.ja.resx
pwiz_tools/Shared/PanoramaClient/Properties/Resources.zh-CHS.resx
pwiz_tools/Skyline/CommandArgUsage.ja.resx
pwiz_tools/Skyline/CommandArgUsage.zh-CHS.resx
pwiz_tools/Skyline/Controls/Spectra/SpectrumGridForm.ja.resx
pwiz_tools/Skyline/Controls/Spectra/SpectrumGridForm.zh-CHS.resx
pwiz_tools/Skyline/EditUI/EditSpectrumFilterDlg.ja.resx
pwiz_tools/Skyline/EditUI/EditSpectrumFilterDlg.zh-CHS.resx
pwiz_tools/Skyline/FileUI/PeptideSearch/PeptideSearchResources.ja.resx
pwiz_tools/Skyline/FileUI/PeptideSearch/PeptideSearchResources.zh-CHS.resx
pwiz_tools/Skyline/Menus/ChromatogramContextMenu.ja.resx
pwiz_tools/Skyline/Menus/ChromatogramContextMenu.zh-CHS.resx
pwiz_tools/Skyline/Model/AuditLog/PropertyNames.ja.resx
pwiz_tools/Skyline/Model/AuditLog/PropertyNames.zh-CHS.resx
pwiz_tools/Skyline/Model/Databinding/Entities/ColumnCaptions.ja.resx
pwiz_tools/Skyline/Model/Databinding/Entities/ColumnCaptions.zh-CHS.resx
pwiz_tools/Skyline/Model/SpectrumPropertiesResx.ja.resx
pwiz_tools/Skyline/Model/SpectrumPropertiesResx.zh-CHS.resx
pwiz_tools/Skyline/Skyline.ja.resx
pwiz_tools/Skyline/Skyline.zh-CHS.resx
pwiz_tools/Skyline/SkylineResources.ja.resx
pwiz_tools/Skyline/SkylineResources.zh-CHS.resx

There were a few terms that have been translated in more than one way into Japanese, and those ambiguous translation are not included in this pull request.
| English | Translation A | Translation B |
|--|--|--|
Formula|分子式|式
Down|下|下へ
Description|表記|説明
There were no ambiguous translations in Chinese.
So, there are 32 Chinese changes and 29 Japanese changes.

Update translated text for items whose text we already had translations for.

---

pwiz_tools/Shared/Common/Common.csproj
pwiz_tools/Shared/Common/DataBinding/AbstractViewContext.cs
pwiz_tools/Shared/Common/DataBinding/RowItemEnumerator.cs
pwiz_tools/Skyline/Controls/Databinding/SkylineViewContext.cs

Fixed Skyline uses too much memory outputting report with "Normalized Area" column when document has Peptide Quantification regression method set to something other than "None" (reported by Genn)
This change allows the "RowItem" objects that contain the objects in the report to be garbage collected right after they are written. This enables the "CalibrationCurveFitter" held onto by "pwiz.Skyline.Model.Databinding.Entities.Peptide" to be collected.

Reduce memory usage when outputting reports

---

pwiz_tools/Skyline/Model/Export.cs
pwiz_tools/Skyline/TestFunctional/ExportIsolationListTest.cs

- Agilent reported that halving the window width was a mistake
- This PR puts the window width back to the way it was before the negative predicted RT fix

Skyline: Fix window widths for Agilent method/list export

---

pwiz_tools/Skyline/FileUI/PeptideSearch/SearchControl.cs
pwiz_tools/Skyline/TestFunctional/DdaSearchTest.cs
pwiz_tools/Skyline/TestUtil/AbstractUnitTestEx.cs
pwiz_tools/Skyline/TestUtil/TestFunctional.cs

- fixed search errors from Search control to be more specific (the main message from the Exception is put in the message box instead of just "Error")
* added TestDdaSearchMsFraggerBadFasta to check for specific error message
* added special handling for "process cannot access the file 'X' because it is being used by another process" in functional tests: now the locking process will be reported

- fixed search errors from Search control to be more specific

---

pwiz_tools/Skyline/Model/Results/ChromatogramCache.cs

Fixed missing chromatograms for small molecules in some SRM documents (reported by Jess, recently introduced in Skyline-daily)
I will write a unit test for this if I get permission to use the data files.

Fix missing small molecule chromatograms

---

pwiz_tools/Skyline/Model/Results/ChromatogramCache.cs

Fixed missing chromatograms for small molecules in some SRM documents (reported by Jess, recently introduced in Skyline-daily)

Fix missing small molecule chromatograms (#3072)

---

pwiz_tools/Skyline/TestFunctional/DdaSearchTest.cs

I think I know how to solve it but given the release timing it's simpler to just disable for now. The TestDdaSearchMsgfPlus test failure is a side effect of the BadFasta test failing.

* disabled BadFasta test until I can solve timing and/or pass1 issues

---

pwiz_tools/Skyline/Model/Databinding/Entities/Precursor.cs

Changed to display "#N/A" for Collision Energy in Document Grid when no collision energy formula provided (not reported by anyone but inspired by import transition list Issue #1006)

Make Precursor Collision Energy nullable in the Document Grid

---

pwiz_tools/Skyline/Model/DdaSearch/HardklorSearchEngine.cs

This is a quick fix for stable testing, but I still need to determine why order matters, and if it does, what order is best.

In parallelized feature finding, the order in which Hardklor/Bullseye jobs complete is unpredictable and this led to some test failures.

---

pwiz_tools/Skyline/Model/Lib/BiblioSpecLite.cs

Fixed unhandled error when .blib file has unrecognized score type (reported on exception web)

Fix unhandled error when score type is "Pecan_ELIB conversion"

---

pwiz/analysis/spectrum_processing/SpectrumListFactory.cpp
pwiz/analysis/spectrum_processing/SpectrumListFactoryTest.cpp
pwiz/analysis/spectrum_processing/SpectrumList_Filter.cpp
pwiz/analysis/spectrum_processing/SpectrumList_Filter.hpp
pwiz/utility/misc/unit.hpp

- added isolationWindows spectrum list filter which filters by absolute m/z pairs (like `[123.4,125.4] [234.5,236.5]` to only accept spectra with one of those two isolation windows)
- added isolationWidth spectrum list filter which filters by width (like `[2.5,3.5]` to only accept spectra with an isolation width of 2.5 or 3.5)

- added isolationWindows and isolationWidth spectrum list filters

---

pwiz_tools/Skyline/TestUtil/TestFunctional.cs

Fixes a problem with exceptions being thrown under the debugger in TestLibraryBuild

Add a convenience function GetUIValue() for getting a value on the UI thread.

---

pwiz_tools/Skyline/SkylineFiles.cs
pwiz_tools/Skyline/TestFunctional/EncyclopeDiaSearchTest.cs
pwiz_tools/Skyline/TestPerf/EncyclopeDiaSearchTutorialTest.cs

Added prompt to configure Koina before running EncyclopeDIA search (reported by Eric)
If the user does "File > Search > EncyclopeDIA Search..." and they have not configured Koina yet they will see this message:
The wizard will not start if they choose "No" or if they don't actually configure Koina.

Prompt user to configure Koina before EncyclopeDIA search

---

pwiz_tools/Skyline/Model/PeakMatcher.cs

Fixed unhandled error doing "Apply peak to all" sometimes (reported by Gustavo)

Fix IndexOutOfRangeException in ApplyPeak (#3136)

---

pwiz_tools/Skyline/Model/DocSettings/AbsoluteQuantification/ScoredBilinearCurve.cs

Fixed "bilinear turning point" LOD calculation when LOD is at lowest calibration point (reported by Lilian)

Fix LOD calculation when LOD is at lowest calibration point

---

pwiz_tools/Skyline/Test/AdductTest.cs
pwiz_tools/Skyline/Util/Adduct.cs

Fix a bug in m/z calculation where the mass of the adduct was not being added to molecules described only as a mass with no chemical formula

---

pwiz_tools/Skyline/TestFunctional/VolcanoPlotFormattingTest.cs

The test was incorrectly using "ToUpperInvariant" to try to create a string which was supposed to match case insensitively; changed to ToUpper. (Also added an extra step to the test to make failure less intermittent)

Fix intermittent failure in Turkish TestVolcanoPlotFormatting

---

pwiz_tools/Skyline/CommandLine.cs
pwiz_tools/Skyline/Menus/EditMenu.cs
pwiz_tools/Skyline/Model/AbstractModificationMatcher.cs
pwiz_tools/Skyline/Model/Import.cs
pwiz_tools/Skyline/Model/ModelResources.designer.cs
pwiz_tools/Skyline/Model/ModelResources.resx
pwiz_tools/Skyline/Model/Optimization/OptimizationDb.cs
pwiz_tools/Skyline/Model/Transition.cs
pwiz_tools/Skyline/SkylineFiles.cs
pwiz_tools/Skyline/Test/SrmDocEditTest.cs
pwiz_tools/Skyline/TestData/CommandLineImportTest.cs
pwiz_tools/Skyline/TestFunctional/CopyPasteTest.cs
pwiz_tools/Skyline/TestFunctional/ReportErrorDlgTest.cs

- More consistently strip charge state indicators
- Merge PeptideGroupDocNodes from peptide lists to avoid creating different peptides for every precursor
- Improve error message when modification matcher fails to create PeptideDocNode instead of NRE
- Fix File > Import > Fasta to recognize peptide list files
- Speed up StripChargeIndicators by not looking for adducts on a known peptide sequence
- Create single constant strings for FASTA prefix ">" and peptide list prefix ">>"

Skyline: Fixes to importing peptide lists for FragPipe team

---

pwiz_tools/Skyline/CommandLine.cs
pwiz_tools/Skyline/TestData/CommandLineImportTest.cs

- This avoids adding a lot of transitions that will get re-picked after the library is built

Skyline: Wait to import peptide list until after importing peptide search

---

pwiz_tools/Skyline/Model/PeakMatcher.cs

Fixed error doing "Apply peak to all" when a particular replicate has no chromatograms that match transitions in the document but does have some hidden MS1 chromatograms (reported by Jeannie)

Fix AssumptionException in PeakMatcher.cs

---

pwiz_tools/Skyline/Properties/Settings.Designer.cs
pwiz_tools/Skyline/Properties/Settings.settings
pwiz_tools/Skyline/Test/CodeInspectionTest.cs
pwiz_tools/Skyline/app.config

a little bit of voodoo around settings that are collections of strings - Settings Designer may not create an app.config entry if the collection is empty. On the other hand, if the collection is non-empty then edited to be empty, the app.config entry will exist, but with an empty string as its value.
also had to change "Prosit" to "Koina" in app.config

added static code inspection for values that don't agree between Settings.settings and app.config

---

pwiz_tools/Skyline/TestRunner/Program.cs

internal test issue, not reported by any user

TestRunner: if more than one leak type is detected, log them all rather than just the first

---

.gitignore

Add /pwiz_aux/msrc/utility/vendor_api/Mobilion/*.h to .gitignore file

Add Mobilion header files to .gitignore

---

pwiz_tools/Skyline/SkylineFiles.cs

Fixed starting screen position of "Add Decoy Peptides" dialog (not reported by anyone) Dialog was getting parented by a window that had already been closed, so CenterParent start position did not work.

Fix position of GenerateDecoysDlg

---

pwiz_tools/Skyline/Model/Koina/Config/KoinaConfig_development.xml
pwiz_tools/Skyline/TestConnected/KoinaBuildLibraryFromCsvTest.cs

Requested by Koina dev.
@brendanx67 Shall I cherry pick this (unless there won't be another release patch)?

Change default Koina URL

---

pwiz_tools/Skyline/Controls/Graphs/GraphFullScan.cs

Make BackgroundScanProvider communicate with GraphFullScan through BeginInvoke instead of Invoke to avoid the case where GraphFullScan tries to Join the background thread just as it is trying to Invoke to the UI thread.

Skyline: Attempt a fix for the deadlock in TestMs1Tutorial

---

pwiz_tools/Shared/Common/DataBinding/Controls/Editor/FilterTab.resx
pwiz_tools/Skyline/Controls/Databinding/PivotReplicateAndIsotopeLabelWidget.ja.resx
pwiz_tools/Skyline/Controls/Databinding/PivotReplicateAndIsotopeLabelWidget.resx
pwiz_tools/Skyline/Controls/Databinding/PivotReplicateAndIsotopeLabelWidget.zh-CHS.resx
pwiz_tools/Skyline/Controls/GroupComparison/VolcanoPlotFormattingDlg.cs
pwiz_tools/Skyline/Model/GroupComparison/MatchRgbHexColor.cs
pwiz_tools/Skyline/SkylineTester/TabTutorials.cs
pwiz_tools/Skyline/TestFunctional/PeakAreaRelativeAbundanceGraphTest.cs
pwiz_tools/Skyline/TestFunctional/VolcanoPlotFormattingTest.cs
pwiz_tools/Skyline/TestPerf/DiaSwathTutorialTest.cs
pwiz_tools/Skyline/TestPerf/DiaUmpireTutorialTest.cs
pwiz_tools/Skyline/TestRunner/Program.cs
pwiz_tools/Skyline/TestUtil/PauseAndContinueForm.cs
pwiz_tools/Skyline/TestUtil/ScreenshotManager.cs
pwiz_tools/Skyline/TestUtil/ScreenshotPreviewForm.cs
pwiz_tools/Skyline/TestUtil/TestFunctional.cs

- Fixed layout in ViewEditor for Japanese and Chinese
- Fixed to VolcanoPlotFormattingDlg for failure in IsPauseForScreenShots mode
- Removed screenshotlist argument from TestRunner and SkylineTester
- Fixed issue with auto-screenshot mode not saving to non-existent language folders
- Fixed ScreenshotPreviewForm startup placement in auto-size mode on 2nd monitor
- Added console output for each screenshot
- Cleaned up unnecessary Thread.Sleep() code in ScreenshotPreviewForm
- Cleaned up a bit inside ScreenshotManager and add code to ForceOnScreen() the frame to be screenshot
- Added keyboard commands (Ctrl-C and Ctrl-Shift-C) to copy new and old bitmaps respectively.
- Removed Thread.Sleep() in auto-screenshot mode for more testing
- Improved commenting in several places

Skyline: Various fixes and improvements for tutorial screenshots

---

pwiz_tools/Skyline/Controls/Graphs/GraphSpectrum.cs
pwiz_tools/Skyline/Controls/UndoRedoButtons.cs
pwiz_tools/Skyline/Skyline.cs
pwiz_tools/Skyline/TestPerf/SmallMolLibrariesTutorialTest.cs
pwiz_tools/Skyline/TestPerf/TestPerf.csproj
pwiz_tools/Skyline/TestTutorial/AuditLogTutorialTest.cs
pwiz_tools/Skyline/TestTutorial/CustomReportsTutorialTest.cs
pwiz_tools/Skyline/TestTutorial/Ms1FullScanFilteringTutorial.cs
pwiz_tools/Skyline/TestTutorial/TestTutorial.csproj
pwiz_tools/Skyline/TestUtil/ScreenshotManager.cs
pwiz_tools/Skyline/TestUtil/ScreenshotPreviewForm.cs
pwiz_tools/Skyline/TestUtil/TestFunctional.cs

- Moved ScreenshotManager instantiation to where SkylineWindow is not null
- Added support for showing Undo and Redo dropdowns
- Improved and centralized support for showing Reports dropdown
- Removed left over ZIP files from .csproj files
- Improved and centralized code to keep screenshot forms on screen

Skyline: First drafts of AuditLogTutorialTest and SmallMolLibrariesTutorialTest

---

.gitignore

* added remaining WIFF test files and /pwiz/utility/bindings/CLI/example/binaries location to .gitignore
* added artifact_xml directory to .gitignore and changed TeamCity artifact upload script to create artifact XMLs in that directory (I considered using an out-of-repo location but that would require the Windows path separators to be escaped in the Python script)

More .gitignore fixes

---

pwiz/data/vendor_readers/Mobilion/ChromatogramList_Mobilion.cpp
pwiz/data/vendor_readers/Mobilion/Reader_Mobilion.cpp
pwiz/data/vendor_readers/Mobilion/Reader_Mobilion_Detail.hpp
pwiz/data/vendor_readers/Mobilion/SpectrumList_Mobilion.cpp

Looks a bit funny when parallel processing multiple .mbi files in Skyline and MSConvertGUI, as only one proceeds at a time, but it does complete

Mobilion reader uses HDF5 library, which isn't thread safe. Put a processwide lock in the ctor to ensure only one thread is in use at a time

---

pwiz_tools/Skyline/TestTutorial/TargetedMSMSTutorialTest.cs

Internal test issue, not reported by any user

A newly added section of code in this tutorial test just needed to be skipped when run as small molecules.

---

pwiz_tools/Skyline/TestConnected/ArdiaFunctionalTest.cs
scripts/misc/vcs_trigger_and_paths_config.py

* fixed code inspection (build failure from my last PR was hidden because the new TestConnected config had the wrong status report string copied from the code inspection config)

Fix code inspection

---

pwiz_tools/Skyline/SkylineTester/SkylineTesterWindow.cs
pwiz_tools/Skyline/Test/ErrorIfPersistentFilesDirModifiedTest.cs
pwiz_tools/Skyline/TestPerf/DdaTutorialTest.cs
pwiz_tools/Skyline/TestUtil/AbstractUnitTest.cs
pwiz_tools/Skyline/TestUtil/TestFilesDir.cs
pwiz_tools/Skyline/TestUtil/TestFunctional.cs

- Helps avoid the case where a prior failure causes an echo failure in the next run because cleanup deletes left over files in the persistent folder

Skyline: Cleanup persistent folder before and after test runs

---

pwiz/data/vendor_readers/Shimadzu/SpectrumList_Shimadzu.cpp
pwiz_aux/msrc/utility/vendor_api/Shimadzu/ShimadzuReader.cpp

- added isolation width to Shimadzu spectra, if present; current Reader_Shimadzu_Test files do not have it, but I have manually tested on DIA files that do

- added isolation width to Shimadzu spectra, if present

---

pwiz_tools/Shared/Common/DataAnalysis/PValues.cs
pwiz_tools/Shared/PanoramaClient/PanoramaFolderBrowser.cs
pwiz_tools/Skyline/CommandLine.cs
pwiz_tools/Skyline/Controls/GroupComparison/FoldChangeVolcanoPlot.cs
pwiz_tools/Skyline/Menus/ViewMenu.cs
pwiz_tools/Skyline/Model/ProgressMonitor.cs
pwiz_tools/Skyline/Model/Results/ChromCacheMinimizer.cs
pwiz_tools/Skyline/Skyline.sln.DotSettings
pwiz_tools/Skyline/TestFunctional/ShareDocumentTest.cs
pwiz_tools/Skyline/TestRunner/UnusedPortFinder.cs

Note in particular the new "UsageOfDefaultStructEquality" warning has been reduced to a suggestion - it wants equality members for structs, because the ones generated automatically are probably inefficient. Worth thinking about when looking at performance issues but not worth a general change to many dozens of files.

Tweaks to quiet the latest ReSharper version's code inspection.

---

pwiz_tools/Skyline/Util/DataGridViewPasteHandler.cs

Fixed scrollbar thumb position after pasting into Document Grid (reported by Brendan)

Fix scrollbar display after paste into Document Grid

---

pwiz_aux/msrc/utility/vendor_api/Waters/WatersRawFile.hpp

per https://skyline.ms/announcements/home/support/thread.view?rowId=40366 it appears that the MassLynx reader DLL throws an exception when it encounters an empty chromatogram (or "channel", in API-speak). With this change we catch and ignore the exception, with the assumption that if there's an actual problem then attempts to get channel name etc with throw too, and we'll let that one pass through.
reported by user Warham

Handle empty chromatograms in Waters data

---

pwiz/analysis/chromatogram_processing/ChromatogramList_LockmassRefiner.cpp
pwiz/analysis/spectrum_processing/SpectrumList_LockmassRefiner.cpp

While chasing down memory issues, I noticed that there seemed to be some proximity to tests that involved asking for lockmass correction on data that isn't actual Waters raw. I'm not 100%% convinced that this is the issue, but it does seem just as well to simplify this code so that the data processing chain is left completely untouched when spurious requests are made. If nothing else it makes for a more accurate set of CVParams.

Simplified handling of bogus lockmass correction requests

---

pwiz_tools/Skyline/TestConnected/KoinaBuildLibraryTest.cs

* disabled TestKoinaBuildLibrary as it's too unreliable now (although I'm not sure it's actually the remote API causing the unreliability)

* disabled TestKoinaBuildLibrary as it's too unreliable now

---

pwiz_tools/Skyline/TestFunctional/ShareDocumentTest.cs

Change "ShowDialog" call to "RunLongDlg" so that the subsequent code does not execute until the method which brought up the dialog has returned. Subsequent test code had been trying to interact with .zip file while it was still locked.

Fix intermittent failure in TestShareDocument

---

pwiz_tools/Skyline/EditUI/EditLinkedPeptidesDlg.cs

Fixed unhandled error on Edit Linked Peptides dialog (reported by Caroline)

Fix unhandled error in Edit Linked Peptide dialog

---

pwiz_tools/Shared/CommonUtil/SystemUtil/FormUtil.cs
pwiz_tools/Skyline/Executables/DevTools/ImageComparer/ImageComparerWindow.cs
pwiz_tools/Skyline/SettingsUI/FullScanSettingsControl.cs
pwiz_tools/Skyline/TestTutorial/GroupedStudies1TutorialTest.cs
pwiz_tools/Skyline/TestTutorial/MethodRefinementTutorialTest.cs
pwiz_tools/Skyline/TestTutorial/Ms1FullScanFilteringTutorial.cs
pwiz_tools/Skyline/TestUtil/MultiFormActivator.cs
pwiz_tools/Skyline/TestUtil/ScreenshotManager.cs
pwiz_tools/Skyline/TestUtil/ScreenshotPreviewForm.Designer.cs
pwiz_tools/Skyline/TestUtil/ScreenshotPreviewForm.cs
pwiz_tools/Skyline/TestUtil/ScreenshotProcessingExtensions.cs
pwiz_tools/Skyline/TestUtil/TestFunctional.cs

- Hide blinking caret in ComboBoxes with an edit control
- Hide RTF control in ScreenshotPreviewForm and ImageComparerWindow as soon as it is not appropriate
- Fixed FullScanSettingsControl radio button layout from bug introduced with feature finding
- Fixed GroupedStudies1TutorialTest to not maximize the SkylineWindow which produces a monitor dependent screenshot
- Fixed GroupedStudies1TutorialTest to reliably AutoResize the FoldChangeResult column
- Tweaked MethodRefinementTutorialTest with FocusDocument and some sizing fixes
- Tweaked Ms1FullScanFilteringTutorial with FocusDocument and JiggleSelection
- Fixed MultiFormActivator to check for IsHandleCreated before Handle which can cause HWND creation, and clear MultiFormActivator before restarting a test.
- Connected Revert toolstrip …

Skyline: More screenshot automation improvements

---

pwiz_tools/Skyline/Executables/DevTools/ImageComparer/GitFileHelper.cs
pwiz_tools/Skyline/Executables/DevTools/ImageComparer/ImageComparerWindow.cs
pwiz_tools/Skyline/TestTutorial/Ms1FullScanFilteringTutorial.cs
pwiz_tools/Skyline/TestUtil/GitFileHelper.cs

- Made several MS1 graph screenshots slightly wider in Japanese
- Fixed detection of modified files in Git for new output format
- Fixed ImageComparerWindow behavior when no modified files are found

Skyline: Final fix for MS1 and ImageComparerWindow fixes

---

pwiz_tools/Skyline/Controls/Graphs/AllChromatogramsGraph.cs
pwiz_tools/Skyline/Controls/Graphs/FileProgressControl.cs
pwiz_tools/Skyline/TestTutorial/AuditLogTutorialTest.cs
pwiz_tools/Skyline/TestTutorial/CEOptimizationTutorialTest.cs
pwiz_tools/Skyline/TestTutorial/LibraryExplorerTutorialTest.cs
pwiz_tools/Skyline/TestTutorial/PeakPickingTutorialTest.cs
pwiz_tools/Skyline/TestTutorial/TargetedMSMSTutorialTest.cs
pwiz_tools/Skyline/TestUtil/TestFunctional.cs

- Fixed ability to use a screenshot of an error message in AllChromatogramsGraph (TargetedMsmsTutorialTest)
- Added short-circuit for auto-screenshot mode in non-en languages to untranslated tutorials
- Final tweaks to LibraryExplorerTutorialTest for auto-screenshot update

Skyline: Final improvements for phase 1 of screenshot updates

---

pwiz_tools/Skyline/Model/AuditLog/AuditLogEntry.cs
pwiz_tools/Skyline/Model/AuditLog/DiffNode.cs
pwiz_tools/Skyline/Model/AuditLog/ReflectorToString.cs
pwiz_tools/Skyline/TestRunnerLib/PInvoke/User32TestExtensions.cs
pwiz_tools/Skyline/TestTutorial/AuditLogTutorialTest.cs
pwiz_tools/Skyline/TestUtil/MultiFormActivator.cs
pwiz_tools/Skyline/TestUtil/ScreenshotPreviewForm.cs

- Fixed MultiFormActivator for ScreenshotPreviewForm

Skyline: Fixes to make TestAuditLogTutorial produce consistent screenshots

---

pwiz_tools/Skyline/SettingsUI/FullScanSettingsControl.cs

It's actually not possible to enter this state (inconsistent use of thousands separator) as a user, but automated testing and tutorial screen capture could do so.
vs

Fix inconsistent formatting of MS vs MS/MS resolution values in Transition Settings > Full Scan dialog

---

pwiz_tools/Skyline/Controls/SequenceTree.cs
pwiz_tools/Skyline/Controls/StatementCompletionTextBox.cs
pwiz_tools/Skyline/FileUI/PublishDocumentDlg.cs
pwiz_tools/Skyline/TestUtil/ScreenshotProcessingExtensions.cs

- Fixed ColorDepth on ImageLists to match the files they include.
- Fixed CleanupBorder to set corner radius to zero for interior docked DockableForms.

Skyline: Fixes for consistent screenshots on Windows 11

---

pwiz_tools/Skyline/SkylineTester/WindowThumbnail.cs
pwiz_tools/Skyline/TestRunnerLib/PInvoke/DwmapiTest.cs

Fix a naming issue in DwmapiTest that caused EntryPointNotFound exceptions and broke screenshots in SkylineTester's Quality tab.

Fix PInvoke's Dwmapi

---

pwiz_tools/Skyline/Model/Lib/BiblioSpecLite.cs

Fixed "Invalid Score Type" sharing minimized library when .blib file came from EncyclopeDIA conversion (reported by Rich)

Fix error when .blib file has unrecognized score type

---

pwiz_tools/Skyline/Controls/WizardPages.cs
pwiz_tools/Skyline/FileUI/PeptideSearch/ImportPeptideSearchDlg.cs
pwiz_tools/Skyline/FileUI/PeptideSearch/PeptideSearchResources.designer.cs
pwiz_tools/Skyline/FileUI/PeptideSearch/PeptideSearchResources.resx
pwiz_tools/Skyline/FileUI/PeptideSearch/SearchControl.cs
pwiz_tools/Skyline/TestFunctional/DdaSearchTest.cs

* changed Run Peptide Search to keep wizard form close button visible, but intercept it while search is running and display an explanation message to click cancel search button

* changed Run Peptide Search to keep wizard form close button visible

---

pwiz_tools/BiblioSpec/src/BuildParser.cpp

Fixed to allow BiblioSpec .ssl files to use .raw or .d folders (reported by Fengchao)

Allow .ssl files to use folders

---

pwiz_tools/Shared/PanoramaClient/PanoramaClient.cs
pwiz_tools/Shared/PanoramaClient/PanoramaFilePicker.cs
pwiz_tools/Shared/PanoramaClient/PanoramaFolderBrowser.cs
pwiz_tools/Shared/PanoramaClient/PanoramaUtil.cs
pwiz_tools/Shared/PanoramaClient/RequestHelper.cs
pwiz_tools/Skyline/Executables/AutoQC/AutoQC/PanoramaSettings.cs
pwiz_tools/Skyline/Executables/AutoQC/AutoQCTest/PanoramaTest.cs
pwiz_tools/Skyline/TestConnected/PanoramaClientDownloadTest.cs

Request with an "anonymous" Panorama server fails because an Authorization header, with blank username and password, is added to the request which fails on the server with a 401 Unauthorized response.  This worked with previous LabKey releases because requests that failed authentication continued as an unauthenticated user.  This is no longer the case with LK 24.11.  
- Renamed WebClientWithCredentials to LabkeySessionWebClient
- Add the Authorization header in LabkeySessionWebClient only if a username and password is provided.
- Added test in PanoramaClientDownloadTest.cs

Fix "Open from Panorama" with anonymous server

---

pwiz_tools/Skyline/Controls/Graphs/GraphFullScan.cs

bumped into this while working on something else
not reported by any user

Avoid a null reference in graph update in a race condition with an action that removes all chromatograms

---

pwiz_tools/Skyline/TestUtil/PauseAndContinueForm.cs

When tests are running, they use the "internal" clipboard instead of the system clipboard. There used to be code in PauseAndContinueForm to switch to using the system clipboard when the test is paused. That code got removed in PR #3153

Enable using the clipboard when paused in a test

---

pwiz_tools/Skyline/Alerts/AlertDlg.cs

Fixed unhandled error pressing copy button on message box when another application has the clipboard locked (reported by Brendan) AlertDlg now uses ClipboardHelper to catch clipboard locked exceptions. This got broken when CommonAlertDlg base class was created in CommonUtil. "CommonAlertDlg.CopyMessage" was supposed to be overridden for Skyline's extra error handling.

Catch exceptions copying from AlertDlg

---

pwiz_tools/Skyline/Model/Databinding/SkylineDataSchema.cs
pwiz_tools/Skyline/Model/Results/Spectra/SpectrumMetadatas.cs
pwiz_tools/Skyline/SettingsUI/PeptideSettingsUI.Designer.cs
pwiz_tools/Skyline/SettingsUI/PeptideSettingsUI.cs

Fixed "Max LOQ CV" text box incorrectly disabled when LOD calculation is "Bilinear turning point" (reported by Philip) The "Max LOQ CV" text box needed to be disabled when the limit of quantification was being calculated using bootstrap curves. Now that LOQ is no longer calculated with using bootstrap curves, the text box should always be enabled.
Also fix performance problem pasting a large number of values into Document Grid in very large document (not reported by anyone).
Also fix performance problem I introduced earlier this week reading ResultFileMetadata

Fix incorrectly disabled "Max LOQ CV" text box

---

pwiz_tools/Skyline/Controls/Graphs/GraphSpectrum.cs
pwiz_tools/Skyline/Controls/ImmediateWindow.Designer.cs
pwiz_tools/Skyline/Controls/ImmediateWindow.cs

- Fixed mirror plots resetting mirror combos with every selection change (also complained about at courses)
- Fixed ImmediateWindow to restore disabled cut-copy-paste-delete menu items when losing focus
- Fixed ImmediateWindow to set focus to Targets view when Esc is pressed

Skyline: Fix minor issues found testing APD changes

---

pwiz_tools/Skyline/Controls/Graphs/GraphSpectrum.cs

PR #3393 broke TestMethodEditTutorial because the wrong spectrum ends up being selected when the selected Precursor in the Targets tree changes to something that was found in a different library.

Fix TestMethodEditTutorial

---

pwiz_tools/Skyline/Documentation/Tutorials/AbsoluteQuant/en/index.html
pwiz_tools/Skyline/Documentation/Tutorials/AuditLog/en/index.html
pwiz_tools/Skyline/Documentation/Tutorials/CustomReports/en/index.html
pwiz_tools/Skyline/Documentation/Tutorials/DDASearch/en/index.html
pwiz_tools/Skyline/Documentation/Tutorials/DIA-PASEF/en/index.html
pwiz_tools/Skyline/Documentation/Tutorials/DIA-QE/en/index.html
pwiz_tools/Skyline/Documentation/Tutorials/DIA-TTOF/en/index.html
pwiz_tools/Skyline/Documentation/Tutorials/ExistingQuant/en/index.html
pwiz_tools/Skyline/Documentation/Tutorials/GroupedStudies/en/index.html
pwiz_tools/Skyline/Documentation/Tutorials/HiResMetabolomics/en/index.html
pwiz_tools/Skyline/Documentation/Tutorials/ImportingAssayLibraries/en/index.html
pwiz_tools/Skyline/Documentation/Tutorials/LibraryExplorer/en/index.html
pwiz_tools/Skyline/Documentation/Tutorials/MS1Filtering/en/index.html
pwiz_tools/Skyline/Documentation/Tutorials/MethodEdit/en/index.html
pwiz_tools/Skyline/Documentation/Tutorials/MethodRefine/en/index.html
pwiz_tools/Skyline/Documentation/Tutorials/PRMOrbitrap-PRBB/en/index.html
pwiz_tools/Skyline/Documentation/Tutorials/PRMOrbitrap/en/index.html
pwiz_tools/Skyline/Documentation/Tutorials/SmallMoleculeIMSLibraries/en/index.html
pwiz_tools/Skyline/Documentation/Tutorials/SmallMoleculeMethodDevCEOpt/en/index.html
pwiz_tools/Skyline/Documentation/Tutorials/SmallMoleculeQuantification/en/index.html

I found and fixed all the places in the "index.html" tutorial HTML files that mentioned menu items that have been moved to the "View > Live Reports" or "View > Libraries" sub-menus.
I also changed it so that they all mention the accelerator if it exists for example:
`On the <b>View</b> menu, choose <b>Live Reports</b>, and click <b>Document Grid</b> (Alt-3).`
I wonder why we have standardized on using a hyphen in "Alt-3" instead of a plus sign "Alt+3".
The text in the menus always has a "+".

Update "View > Live Reports" and "View > Libraries" references in English tutorial HTML files.

---

pwiz_tools/Skyline/Model/Irt/RCalcIrt.cs

Fixed nonsensical message about missing iRT standards (reported by Brian)
Here's what the message looks like now:

Fix confusing missing iRT standards message

---

pwiz_tools/Skyline/Controls/SequenceTree.cs
pwiz_tools/Skyline/Skyline.cs
pwiz_tools/Skyline/Skyline.resx

The tree did not collapse properly when only a protein node is selected.

Small fix for the sequence tree expand/collapse logic

---

pwiz_tools/Skyline/Controls/Graphs/GraphChromatogram.cs
pwiz_tools/Skyline/Controls/Graphs/GraphsResources.designer.cs
pwiz_tools/Skyline/Controls/Graphs/GraphsResources.resx

Changed to display "No quantitative chromatograms" instead of "Chromatogram information unavailable" when displaying only quantitative transitions and no chromatograms found (reported by Vicky).

Display "No quantitative chromatograms found" instead of "Chromatogram information unavailable" if only showing quantitative chromatograms

---

pwiz_tools/Skyline/Controls/Graphs/AreaRelativeAbundanceGraphPane.cs
pwiz_tools/Skyline/Controls/Graphs/SummaryRelativeAbundanceGraphPane.cs
pwiz_tools/Skyline/SkylineGraphs.cs

Added progress bar to Peak Area Relative Abundance plot (requested by Mike)
Fixed bug where "View > Transitions" would change to "Total" when Peak Area Relative Abundance plot is shown (reported by Mike)

Add progress bar to peak area relative abundance plot

---

pwiz_tools/Skyline/Alerts/KeyValueGridDlg.cs
pwiz_tools/Skyline/FileUI/PeptideSearch/ConverterSettingsControl.cs
pwiz_tools/Skyline/FileUI/PeptideSearch/EncyclopeDiaSearchDlg.cs
pwiz_tools/Skyline/FileUI/PeptideSearch/ImportPeptideSearchDlg.cs
pwiz_tools/Skyline/FileUI/PeptideSearch/SearchSettingsControl.cs
pwiz_tools/Skyline/FileUI/PeptideSearch/TransitionSettingsControl.cs
pwiz_tools/Skyline/FileUI/PeptideSearch/TransitionSettingsControl.resx
pwiz_tools/Skyline/Model/AbstractDdaSearchEngine.cs
pwiz_tools/Skyline/Model/DdaSearch/CometSearchEngine.cs
pwiz_tools/Skyline/TestFunctional/DdaSearchTest.cs
pwiz_tools/Skyline/TestPerf/DdaTutorialTest.cs

- changed Comet's default precursor_tolerance_type to 1 (m/z tolerance) and made tolerance units name responsive to that setting (m/z vs. Da)
- fixed Comet search with a single file
- fixed Additional Settings dialog not working properly if value set contains true or false string
- relabeled first tab of Run Peptide Search
* removed Comet's `use_*_ions` and `variable_mod*` parameters from Additional Settings (they are controlled by fragment ions and document mods)
* removed parentless KeyValueGridDlg overload
* fixed spectrum filter Edit button location and mnemonics

Fixes for Comet search issues (reported by Mike)

---

pwiz_tools/Skyline/Model/AbstractMassListExporter.cs
pwiz_tools/Skyline/Model/Export.cs

TestThermoNegativeFAIMS is expecting that the compound name will be a quoted value in the CSV file with a comma in it.

Fix "TestThermoNegativeFAIMS"

---

pwiz_tools/Skyline/Controls/Graphs/GraphChromatogram.cs

Fixed chromatogram x-axis zoom incorrectly includes zero when peak is missing (not reported by anyone)

Fix chromatogram zoom problem

---

pwiz_tools/Shared/zedgraph/ZedGraph/FontSpec.cs
pwiz_tools/Skyline/Test/Test.csproj
pwiz_tools/Skyline/Test/ZedGraphTest.cs
pwiz_tools/Skyline/TestFunctional/ReplicatePivotGridTest.cs

Fixed error sometimes trying to draw text on graphs.
There was a bug in the implementation of the setter for FontSpec.Size where "_scaledSize" would be a nonsensical number which grew larger every time the size was changed and would eventually overflow.

Fix exception in AxisLabelScaler (#3435)

---

pwiz_tools/Skyline/Test/ZedGraphTest.cs

Newly added test "ZedGraphTest" was causing warnings in TestRunner because it did not inherit from AbstractUnitTest

Change ZedGraphTest to inherit from AbstractUnitTest

---

pwiz_tools/Skyline/EditUI/AssociateProteinsDlg.cs

A "ClearSelection" call was incorrectly removed in PR #3401

Hide the selection in the grid in AssociateProteinsDlg

---

pwiz_tools/Skyline/EditUI/AssociateProteinsDlg.cs

A "ClearSelection" call was incorrectly removed in PR #3401

Hide the selection in the grid in AssociateProteinsDlg (#3442)

---

pwiz_tools/Skyline/EditUI/PasteDlg.cs
pwiz_tools/Skyline/Model/Import.cs
pwiz_tools/Skyline/Model/ModificationMatcher.cs

Fixed bug where "+10" was incorrectly interpreted as "Label:13C(6)15N(4) (R)" regardless of which amino acid it was applied to (reported by Philip)
Changed "SimplifyUnimodSequence" to ignore mismatches between unimod modification symbols and the amino acid they could be applied to. Changed to catch exceptions in MassListImporter.DoImport and display an error with line number.

Fix bug with modified sequence containing "F[+10]"

---

pwiz_tools/Skyline/Controls/Graphs/GraphFullScan.cs

- GraphFullScan.FireSelectedScanChanged has reported IndexOutOfRangeExceptions since it was released
- This change should get rid of those exceptions with the possible downside that the user will not get a selected scan in the Full-Scan view when they expect one.
- They can always click again. It has been a very long time without any progress on this issue.

Skyline: Fix a common IndexOutOfRangeException

---

pwiz/analysis/spectrum_processing/SpectrumList_DiaUmpire.hpp
pwiz/data/msdata/SpectrumListWrapper.hpp
pwiz_aux/msrc/utility/vendor_api/Bruker/TsfData.cpp

* fixed underlying SpectrumList::find() overrides not being used for SpectrumListWrapper, so accessing profile vendor spectra would use the vendor's find() override, but accessing centroid vendor spectra would use the fallback linear search of SpectrumList::find()
- fixed incorrect find() result for Bruker TSF data with skipped frames (reported by Agnes)

Fix find() for Bruker TSF

---

pwiz_tools/Skyline/FileUI/PeptideSearch/TransitionSettingsControl.cs

Fixed "Ion match tolerance" sometimes multiplied or divided by 1000 in Import Peptide Search wizard (reported by Mike)

Fix invalid Ion Match Tolerance in Import Peptide Search wizard

---

pwiz_tools/Skyline/Model/Koina/KoinaResources.ja.resx
pwiz_tools/Skyline/Model/ModelResources.ja.resx
pwiz_tools/Skyline/SkylineResources.ja.resx
pwiz_tools/Skyline/TestData/LocalizedResourcesTest.cs
pwiz_tools/Skyline/TestData/TestData.csproj
pwiz_tools/Skyline/TestFunctional/TestFunctional.csproj
pwiz_tools/Skyline/ToolsUI/ToolsUIResources.ja.resx
pwiz_tools/Skyline/Util/Extensions/ExtensionsResources.zh-CHS.resx

Move "LocalizedResourcesTest" from "TestFunctional" into "TestData" so that it can use "ErrorChecker.cs". Add assert to LocalizedResourcesTest that if English text starts with "Error:", localized text starts with localized version of that.

Fix Japanese ConsoleImportPeptideSearchTest and TestCommandLineExportThermoMethod

---

pwiz_tools/Skyline/Model/Koina/KoinaResources.ja.resx
pwiz_tools/Skyline/Model/ModelResources.ja.resx
pwiz_tools/Skyline/SkylineResources.ja.resx
pwiz_tools/Skyline/TestData/LocalizedResourcesTest.cs
pwiz_tools/Skyline/TestData/TestData.csproj
pwiz_tools/Skyline/TestFunctional/TestFunctional.csproj
pwiz_tools/Skyline/ToolsUI/ToolsUIResources.ja.resx
pwiz_tools/Skyline/Util/Extensions/ExtensionsResources.zh-CHS.resx

Move "LocalizedResourcesTest" from "TestFunctional" into "TestData" so that it can use "ErrorChecker.cs". Add assert to LocalizedResourcesTest that if English text starts with "Error:", localized text starts with localized version of that.
Change Chinese colon used by "TextUtil.AppendColon" and "TextUtil.ColonSeparate".

Fix Japanese ConsoleImportPeptideSearchTest and TestCommandLineExportThermoMethod (#3468)

---

pwiz_tools/Skyline/Alerts/AlertsResources.designer.cs
pwiz_tools/Skyline/Alerts/AlertsResources.resx
pwiz_tools/Skyline/Alerts/MsFraggerDownloadDlg.Designer.cs
pwiz_tools/Skyline/Alerts/MsFraggerDownloadDlg.cs
pwiz_tools/Skyline/Alerts/MsFraggerDownloadDlg.ja.resx
pwiz_tools/Skyline/Alerts/MsFraggerDownloadDlg.resx
pwiz_tools/Skyline/Alerts/MsFraggerDownloadDlg.zh-CHS.resx
pwiz_tools/Skyline/FileUI/PeptideSearch/ImportPeptideSearchDlg.cs
pwiz_tools/Skyline/Model/DdaSearch/MsFraggerSearchEngine.cs
pwiz_tools/Skyline/Program.cs
pwiz_tools/Skyline/Properties/Settings.Designer.cs
pwiz_tools/Skyline/Properties/Settings.settings
pwiz_tools/Skyline/TestFunctional/DdaSearchTest.cs
pwiz_tools/Skyline/TestFunctional/DiaSearchTest.cs
pwiz_tools/Skyline/TestPerf/DdaTutorialTest.cs
pwiz_tools/Skyline/TestPerf/DiaSearchTutorialTest.cs
pwiz_tools/Skyline/TestUtil/TestFunctional.cs
pwiz_tools/Skyline/app.config

- fixed MSFragger download to use new verification code scheme
* fixed "Do you want to cancel search?" popup in peptide search wizard from preventing forms cleanup
* removed Expect100Continue manipulation since new scheme doesn't need it, and moved TextChanged handlers to designer code
* added message box to check email after clicking Request Verification Code
* fixed reporting of error message if download MSFragger fails (e.g. expired/invalid verification code)

- fixed MSFragger download to use new verification code scheme (#3469)

---

pwiz/data/msdata/MSData.cpp
pwiz/data/msdata/MSData.hpp
pwiz/data/vendor_readers/Waters/Reader_Waters_Test.data/QC_LCMS2-2_23_268-1-1.mzML
pwiz/data/vendor_readers/Waters/SpectrumList_Waters.cpp

The spectrum list was already determining that the unit should be 'nanometre' in some cases, but this wasn't reflected in the array in the mzML
#3479

Write correct units into mz array when writing Waters spectra

---

pwiz_tools/Shared/CommonUtil/SystemUtil/FileLockingProcessFinder.cs
pwiz_tools/Skyline/Test/UtilTest.cs
pwiz_tools/Skyline/TestRunner/Program.cs

- existing code failed when IOException text contained an extra apostrophe due to RegEx bug
- fixed "Run indefinitely" in parallel test mode with non-parallel tests to keep them from running on Docker agents

Skyline: Fix FilesDirTest FileLockingProcessFinder test on French language system

---

pwiz_tools/Skyline/README.md

I did find it odd that we didn't have one, but I'm mainly doing this to test my fix for cherry picking since that fix PR itself couldn't be cherry picked because it modified workflow files and apparently that's a no-no (which makes sense, you generally don't want automated workflows to be able to modify themselves!). I could fix that by changing the actions to use a personal token with more permission, but I don't think the security risk is justified.

* added README.md at Skyline source root

---

pwiz/utility/misc/Filesystem.cpp
pwiz/utility/misc/Filesystem.hpp
pwiz_aux/msrc/utility/vendor_api/ABI/WiffFile2.ipp
pwiz_tools/BiblioSpec/src/BuildParser.cpp
pwiz_tools/BiblioSpec/src/MaxQuantReader.cpp

* wrapped std::filesystem::canonical in a pwiz::util function that returns bfs::path
* switched BiblioSpec usage of bfs::canonical to pwiz::util

* switched BiblioSpec usage of bfs::canonical to pwiz::util

---

pwiz_tools/Shared/CommonMsData/CommonMsData.csproj
pwiz_tools/Shared/CommonMsData/RemoteApi/Ardia/ArdiaAccount.cs
pwiz_tools/Shared/CommonMsData/RemoteApi/Ardia/ArdiaClient.cs
pwiz_tools/Shared/CommonMsData/RemoteApi/Ardia/ArdiaCredentialHelper.cs
pwiz_tools/Shared/CommonMsData/RemoteApi/Ardia/EncryptedToken.cs
pwiz_tools/Skyline/Alerts/ArdiaLoginDlg.cs
pwiz_tools/Skyline/Test/ArdiaMarshalingTest.cs
pwiz_tools/Skyline/Test/EncryptedTokenTest.cs
pwiz_tools/Skyline/Test/Test.csproj
pwiz_tools/Skyline/TestConnected/ArdiaFileUploadTest.cs
pwiz_tools/Skyline/ToolsUI/EditRemoteAccountDlg.cs

ArdiaAccount now stores encrypted Token. SetToken method encrypts token. ArdiaClient now stores private encrypted token, Token property returns decrypted token when accessed.

Keep cookie token encrypted while stored, only decrypt when accessed for API call

---

pwiz_aux/msrc/utility/vendor_api/Bruker/TimsData.cpp

- fixed crash when creating chromatograms for timsTOF data that have empty spectra (reported by Chris)
It's amazing it took this long to trigger. It must be very rare for a timsTOF frame to have 0 peaks.

- fixed crash for timsTOF data that have empty spectra

---

pwiz_tools/Skyline/Model/RetentionTimes/KdeAligner.cs
pwiz_tools/Skyline/TestFunctional/NonLinearRegressionTest.cs
pwiz_tools/Skyline/TestPerf/DiaNnPeakImputationTest.cs

The Peak Imputation commit (PR #3428) included some changes to KdeAligner which did not need to be made.
Revert those changes to KdeAligner.

Fix TestFeatureDetectionTutorialFuture

---

pwiz_tools/Skyline/TestPerf/PerfDecoysMatchTest.cs

PerfDecoysMatchTest got changed with the initial Peak Imputation commit in PR #3428 on Aug 26. Later, on Sept 17, with PR #3594, the way that unaligned retention times was fixed, and PerfDecoysMatchTest should have been reverted back to its earlier version. This change reverts PerfDecoysMatchTest back to its old version from earlier this summer.

Fix DecoysMatchTest

---

pwiz_tools/Skyline/Model/Databinding/Entities/PrecursorResult.cs

Fixed LcPeakIonMetricsMS1 in Document Grid is #N/A when MS1 spectra scan window width is less than 500 m/z (reported by Chris)

Fix LcPeakIonMetricsMS1 for SIM scans

---

pwiz_tools/Skyline/Model/Lib/BiblioSpecLite.cs
pwiz_tools/Skyline/Program.cs
pwiz_tools/Skyline/TestUtil/TestFunctional.cs
pwiz_tools/Skyline/Util/PooledSqliteConnection.cs
pwiz_tools/Skyline/Util/UtilIO.cs

Add logging statements to track down intermittent failures in TestDocumentSharing and TestInternationalFilenames

Add some different logging statements to track down .blib locking problem

---

pwiz_tools/Shared/CommonMsData/MsDataFilePath.cs
pwiz_tools/Shared/CommonMsData/RemoteApi/RemoteUrl.cs
pwiz_tools/Shared/CommonMsData/SampleHelp.cs
pwiz_tools/Shared/ProteowizardWrapper/LockMassParameters.cs
pwiz_tools/Skyline/CommandArgs.cs
pwiz_tools/Skyline/FileUI/ImportResultsLockMassDlg.cs
pwiz_tools/Skyline/Model/ImportPeakBoundaries.cs
pwiz_tools/Skyline/Properties/Settings.cs
pwiz_tools/Skyline/TestData/Results/SmallWiffTest.cs
pwiz_tools/Skyline/TestData/XmlValidationTest.cs
pwiz_tools/Skyline/TestPerf/PerfDetectLockmassFunctionTest.cs
pwiz_tools/Skyline/TestPerf/PerfLockmassTest.cs

1. Make LockMassParameters constructor private and replace calls with LockMassParameters.Create which returns constant "Empty" instead of creating new one which makes "Equals" faster
2. Short circuit parsing parameters in MsDataFilePath constructor if there are no parameters.

MsDataFilePath performance improvements

---

pwiz_tools/Skyline/Model/Lib/Library.cs

If a Library was loaded while a new Document was being opened, the library's ReadStream would not get closed.

Fix intermittent failure in TestInternationalFilenames

---

pwiz_tools/Skyline/Model/DocSettings/SrmSettings.cs
pwiz_tools/Skyline/Model/RetentionTimes/DocumentRetentionTimes.cs
pwiz_tools/Skyline/Model/RetentionTimes/LibraryAlignment.cs
pwiz_tools/Skyline/Model/RetentionTimes/PeakImputation/PeakBoundaryImputer.cs
pwiz_tools/Skyline/Model/RetentionTimes/RetentionTimeManager.cs
pwiz_tools/Skyline/Skyline.cs
pwiz_tools/Skyline/SkylineFiles.cs
pwiz_tools/Skyline/Test/PeakShapeStatisticsTest.cs

Fixed performance problem with peak imputation and large documents (not reported by anyone)
Fixed problem where Skyline would update results for entire tree even when the retention time alignment had not changed.

Fix retention time alignment performance problem
