ProteoWizard/pwiz

- Jamroot.jam
- pwiz_tools/Bumbershoot/directag/Jamfile.jam
- pwiz_tools/Bumbershoot/greazy/Jamfile.jam
- pwiz_tools/Bumbershoot/greazy/greazyVersion.hpp
- pwiz_tools/Bumbershoot/idpicker/Qonverter/CoreVersion.hpp
- pwiz_tools/Bumbershoot/idpicker/Qonverter/Jamfile.jam
- pwiz_tools/Bumbershoot/idpicker/Qonverter/idpAssembleVersion.hpp
- pwiz_tools/Bumbershoot/idpicker/Qonverter/idpQonvertVersion.hpp
- pwiz_tools/Bumbershoot/idpicker/Qonverter/idpQueryVersion.hpp
- pwiz_tools/Bumbershoot/myrimatch/Jamfile.jam
- pwiz_tools/Bumbershoot/myrimatch/myrimatchVersion.hpp
- pwiz_tools/Bumbershoot/pepitome/Jamfile.jam
- pwiz_tools/Bumbershoot/pepitome/pepitomeVersion.hpp
- pwiz_tools/Bumbershoot/quameter/Jamfile.jam
- pwiz_tools/Bumbershoot/quameter/quameterVersion.hpp
- pwiz_tools/Bumbershoot/tagrecon/Jamfile.jam
- pwiz_tools/Bumbershoot/tagrecon/tagreconVersion.hpp
caused by addition of Branch method to generate-version.cpp
> * fixed Bumbershoot build errors

- scripts/misc/skipNonCoreChanges.py
to allow core build configs to report success to pull requests when only non-core files have been changes (e.g. Bumbershoot, Skyline)
> * added skipNonCoreChanges.py script 

- pwiz_aux/msrc/utility/vendor_api/Agilent/MidacData.cpp
> Agilent CCS<->DT conversion only wants to deal with postive values

- pwiz.vcxproj
- pwiz.vcxproj.filters
- pwiz/data/vendor_readers/UNIFI/SpectrumList_UNIFI.cpp
- pwiz_aux/msrc/utility/vendor_api/UNIFI/UnifiData.cpp
- pwiz_aux/msrc/utility/vendor_api/UNIFI/UnifiData.hpp
- pwiz_tools/MSConvertGUI/MSConvertGUI.csproj
- pwiz_tools/MSConvertGUI/MSConvertGUI.sln
- pwiz_tools/MSConvertGUI/MainForm.cs
- pwiz_tools/MSConvertGUI/Properties/Settings.Designer.cs
- pwiz_tools/MSConvertGUI/Properties/Settings.settings
- pwiz_tools/MSConvertGUI/UnifiBrowserForm.cs
- pwiz_tools/MSConvertGUI/app.config
- pwiz_tools/Shared/Common/CommonUtil.csproj
- pwiz_tools/Shared/Common/SystemUtil/CenterWinDialog.cs
Add persistence for UNIFI credentials; clicking the Disconnect button…will forget the credentials for the current URL
Add 'preset scan configuration' CV param to UNIFI MS^e spectra: 1 is low energy, 2 is high energy
Improve error handling for UNIFI calls
Add CenterWinDialog class to allow MessageBox dialogs to be centered in their parent window
> Add persistence for UNIFI credentials

- pwiz_tools/Shared/Common/DataBinding/Controls/ColumnListEditor.zh-CHS.resx
- pwiz_tools/Shared/Common/DataBinding/Controls/ManageLayoutsForm.zh-CHS.resx
- pwiz_tools/Shared/Common/DataBinding/Controls/NameLayoutForm.zh-CHS.resx
- pwiz_tools/Shared/Common/DataBinding/Controls/PivotEditor.zh-CHS.resx
- pwiz_tools/Skyline/Alerts/DetailedReportErrorDlg.zh-CHS.resx
- pwiz_tools/Skyline/Alerts/PathChooserDlg.zh-CHS.resx
- pwiz_tools/Skyline/Alerts/PeptidesPerProteinDlg.zh-CHS.resx
- pwiz_tools/Skyline/Controls/Graphs/AreaCVToolbarProperties.zh-CHS.resx
- pwiz_tools/Skyline/Controls/Graphs/Calibration/CalibrationForm.zh-CHS.resx
- pwiz_tools/Skyline/Controls/GroupComparison/CreateMatchExpressionDlg.zh-CHS.resx
- pwiz_tools/Skyline/Controls/GroupComparison/VolcanoPlotPropertiesDlg.zh-CHS.resx
- pwiz_tools/Skyline/EditUI/UniquePeptidesDlg.zh-CHS.resx
- pwiz_tools/Skyline/FileUI/ImportResultsNameDlg.zh-CHS.resx
- pwiz_tools/Skyline/FileUI/PeptideSearch/ImportFastaControl.zh-CHS.resx
- pwiz_tools/Skyline/FileUI/PeptideSearch/TransitionSettingsControl.zh-CHS.resx
- pwiz_tools/Skyline/Model/Databinding/Entities/ColumnCaptions.zh-CHS.resx
- pwiz_tools/Skyline/Model/Databinding/Entities/ColumnToolTips.zh-CHS.resx
- pwiz_tools/Skyline/Model/GroupComparison/GroupComparisonStrings.zh-CHS.resx
- pwiz_tools/Skyline/Properties/Resources.zh-CHS.resx
- pwiz_tools/Skyline/SettingsUI/EditCustomMoleculeDlg.zh-CHS.resx
- pwiz_tools/Skyline/SettingsUI/IonMobility/EditDriftTimePredictorDlg.zh-CHS.resx
- pwiz_tools/Skyline/SettingsUI/StartPageSettingsUI.zh-CHS.resx
- pwiz_tools/Skyline/SettingsUI/TransitionSettingsUI.zh-CHS.resx
- pwiz_tools/Skyline/Skyline.zh-CHS.resx
Merging RESX changes from Chinese reviewers
> Skyline (4.1): Final zh-CHS translation changes

- pwiz_tools/SeeMS/Dialogs/HeatmapForm.cs
- fixed SeeMS IMS heatmap control chromatograms including rows with ion mobility == 0
> - fixed SeeMS IMS heatmap control chromatograms

- pwiz_tools/Skyline/FileUI/ImportResultsNameDlg.ja.resx
- pwiz_tools/Skyline/FileUI/PeptideSearch/ImportFastaControl.ja.resx
- pwiz_tools/Skyline/FileUI/PeptideSearch/TransitionSettingsControl.ja.resx
- pwiz_tools/Skyline/Model/Databinding/Entities/ColumnCaptions.ja.resx
- pwiz_tools/Skyline/Model/Databinding/Entities/ColumnToolTips.ja.resx
- pwiz_tools/Skyline/Model/GroupComparison/GroupComparisonStrings.ja.resx
- pwiz_tools/Skyline/Properties/Resources.ja.resx
- pwiz_tools/Skyline/SettingsUI/EditCustomMoleculeDlg.ja.resx
- pwiz_tools/Skyline/SettingsUI/IonMobility/EditDriftTimePredictorDlg.ja.resx
- pwiz_tools/Skyline/SettingsUI/PeptideSettingsUI.ja.resx
- pwiz_tools/Skyline/SettingsUI/TransitionSettingsUI.ja.resx
- pwiz_tools/Skyline/Skyline.ja.resx
Skyline (4.1): Merge final reviewer revisions to Japanese translation
> Skyline (4.1): Final reviewer revisions for Japanese translation

- pwiz_tools/Skyline/Model/Lib/Midas/MidasLibrary.cs
* Skyline 4.1 bug fix for viewing spectra in MIDAS library.
> Skyline/work/20180618 midas fixes (#99)

- pwiz_tools/BiblioSpec/src/MaxQuantReader.cpp
- pwiz_tools/BiblioSpec/src/modifications.xml
Also, when looking for "modifications.xml" alongside msms.txt file, also look for "modifications.local.xml", and merge the two together.
> New "modifications.xml" file from MaxQuant 1.6.2.10

- scripts/misc/smartBuildTrigger.py
- scripts/wix/pwiz-setup.wxs.template
* changed smartBuildTrigger.py to trigger only Core Windows builds with wxs.template changes
> Restored PASEF preset to pwiz installer

- pwiz_tools/Skyline/Controls/Lists/ListDesigner.Designer.cs
- pwiz_tools/Skyline/Controls/Lists/ListDesigner.resx
- pwiz_tools/Skyline/Model/AuditLog/PropertyNames.Designer.cs
- pwiz_tools/Skyline/Model/AuditLog/PropertyNames.resx
- pwiz_tools/Skyline/Model/DocSettings/AnnotationDef.cs
- pwiz_tools/Skyline/Model/DocSettings/DataSettings.cs
- pwiz_tools/Skyline/Model/Lists/ListData.cs
- pwiz_tools/Skyline/Model/Lists/ListDef.cs
- pwiz_tools/Skyline/Skyline.Designer.cs
- pwiz_tools/Skyline/Skyline.cs
- pwiz_tools/Skyline/Skyline.resx
- Make ListDesigner localizable, give it mnemonics, turn off minimize, maximize and taskbar, etc.
- Make View > Other Grids > Lists > Define New List actually work
- Rationalize mnemonics on the View menu to support the new options
- Make adding a new List to a document add audit log entries (needs more work)
> Skyline: Some initial fixes to Nick's new Lists feature

- Jamroot.jam
- pwiz_aux/msrc/utility/vendor_api/Shimadzu/Jamfile.jam
- pwiz_aux/msrc/utility/vendor_api/Shimadzu/ShimadzuReader.cpp
- scripts/wix/vendor-dlls.wxs-fragment
- updated Shimadzu QTOF DLLs which no longer need the platform-specific subdirectories
> - updated Shimadzu QTOF DLLs

- pwiz_tools/Skyline/Alerts/ReportErrorDlg.cs
* Add CSRF token to exception report POST request.
> Skyline/work/20181212 exception report csrf (#374)

- pwiz_tools/Skyline/SkylineTester/CommandShell.cs
- pwiz_tools/Skyline/TestRunner/Program.cs
- The coloring of lines in the SkylineTester log caused
SkylineTester to run extremely slow (Each line was colored separately
using a RunUI for each line)
- Now deleting minidumps before running tests
> Skyline - improved log performance of SkylineTester

- Jamroot.jam
Just noticed this was wrong. Which is one day too late to test with CI.
> Fix day_of_year function for days 1-9

- pwiz_tools/commandline/msconvert.cpp
- added stripLocationFromSourceFiles option to make it possible to generate mzML files that don't change when the input location changes (which also preserves the overall file checksum)
> - added stripLocationFromSourceFiles option

- pwiz_tools/Skyline/Executables/Installer/SkylineInstaller/Product.wxs
- pwiz_tools/Skyline/Executables/Installer/SkylineInstaller/ProductVersion.wxi
- pwiz_tools/Skyline/Skyline.csproj
Also, remove change some bitmaps in "Resources" folder to be embedded resources.
> Update Skyline Administrator Installer files.

- pwiz_tools/BiblioSpec/tests/reference/mse-mobility-no-silac.check
This is why it's a good idea to let TC build after updating from master rather than admin overriding the merge. :)
> * fixed BiblioSpec test file

- pwiz_tools/Skyline/Executables/Installer/SkylineInstaller/Product.wxs
- pwiz_tools/Skyline/Executables/Installer/SkylineInstaller/ProductVersion.wxi
- pwiz_tools/Skyline/Skyline.csproj
Also fix image files that were incorrectly marked as "Content". Changed to "None".
> Update files in the Administrator Installer.

- pwiz_aux/msrc/utility/vendor_api/thermo/RawFileTypes.h
Due to mixed line endings this has `121 additions and 121 deletions.`,
although really only one line (line 168) was changed. 
Feel free to reject and edit locally with fewer changes. 
Yours, Steffen
closes #529
> [Reader_Thermo::fillInMetadata] Update instrumentModel for ISQ

- pwiz_tools/BiblioSpec/src/MzIdentMLReader.cpp
- pwiz_tools/BiblioSpec/src/MzIdentMLReader.h
- pwiz_tools/BiblioSpec/tests/Jamfile.jam
- pwiz_tools/BiblioSpec/tests/inputs/ProtPilotTest.mzid
- pwiz_tools/BiblioSpec/tests/inputs/ProtPilotTest1.mzML
- pwiz_tools/BiblioSpec/tests/inputs/ProtPilotTest2.mzML
- pwiz_tools/BiblioSpec/tests/reference/pilot-mzid.check
- added support for ProteinPilot mzIdentML to BiblioSpec
* fixed scoreType for PEAKS_ANALYSIS (due to missing break statement)
> Add support for ProteinPilot mzIdentML to BiblioSpec

- pwiz_tools/Skyline/TestUtil/ExtensionTestContext.cs
I really wish GitHub made it easier to use the same changeset on more than one base branch...
> Disarm WIFF2 timebomb

- pwiz_tools/Shared/Common/Collections/CollectionUtil.cs
- pwiz_tools/Skyline/Controls/Graphs/SummaryReplicateGraphPane.cs
> Fix exception choosing "Order By > Sample Type".

- pwiz_tools/Skyline/Model/PeptideDocNode.cs
- pwiz_tools/Skyline/Model/Serialization/DocumentReader.cs
- pwiz_tools/Skyline/Model/Serialization/DocumentSerializer.cs
- pwiz_tools/Skyline/Model/Serialization/DocumentWriter.cs
- pwiz_tools/Skyline/TestFunctional/ModifiedAreaProportionTest.cs
- pwiz_tools/Skyline/TestUtil/Schemas/Skyline_19.11.xsd
> Fix serialization of PeptideDocNode.AttributeGroupId

- pwiz_tools/Skyline/CommandArgs.cs
- pwiz_tools/Skyline/TestData/CommandLineTest.cs
Add basic test for SkylineCmd share-zip (should fail without fix which I will be adding after tests kick off)
> Fix SkylineCmd share-zip

- pwiz_tools/Skyline/Model/AuditLog/PropertyNames.Designer.cs
- pwiz_tools/Skyline/Model/AuditLog/PropertyNames.resx
- pwiz_tools/Skyline/Model/TransitionGroupDocNode.cs
It was getting blanked out whenever the Peptide Settings changed.
(Reported by Josh)
> Fix Precursor Concentration

- pwiz_tools/Shared/ProteowizardWrapper/MsDataFileImpl.cs
- pwiz_tools/Skyline/Model/Results/AbstractDemultiplexer.cs
- pwiz_tools/Skyline/Model/Results/FastOverlapDemultiplexer.cs
- pwiz_tools/Skyline/Model/Results/SpectraChromDataProvider.cs
- pwiz_tools/Skyline/Model/Results/SpectrumFilter.cs
> Fix demultiplexing algorithms that were broken by the MS3 support.

- pwiz/data/vendor_readers/Bruker/Reader_Bruker_Test.data/Hela_QC_PASEF_Slot1-first-6-frames-combineIMS-ms2.mzML
- pwiz/data/vendor_readers/Bruker/Reader_Bruker_Test.data/Hela_QC_PASEF_Slot1-first-6-frames-combineIMS.mzML
- pwiz/data/vendor_readers/Bruker/Reader_Bruker_Test.data/Hela_QC_PASEF_Slot1-first-6-frames-ms2-noMsMsWithoutPrecursor.mzML
- pwiz/data/vendor_readers/Bruker/Reader_Bruker_Test.data/diaPASEF-ms2-noMsMsWithoutPrecursor-mzMobilityFilter.mzML
- pwiz/data/vendor_readers/Bruker/SpectrumList_Bruker.cpp
- pwiz_aux/msrc/utility/vendor_api/Bruker/Baf2Sql.cpp
- pwiz_aux/msrc/utility/vendor_api/Bruker/Baf2Sql.hpp
- pwiz_aux/msrc/utility/vendor_api/Bruker/CompassData.cpp
- pwiz_aux/msrc/utility/vendor_api/Bruker/CompassData.hpp
- pwiz_aux/msrc/utility/vendor_api/Bruker/TimsData.cpp
- pwiz_aux/msrc/utility/vendor_api/Bruker/TimsData.hpp
* fixed prmPASEF being treated as DIA (it has empty DiaFrame* tables)
* optimized AIF PASEF logic
> prmPASEF fixes and aifPASEF optimization

- pwiz_aux/msrc/utility/vendor_api/thermo/RawFile.cpp
* fixed subscript out of range error showing up for MSX in debug mode (and causing UB in release mode)
> Subscript out of range error for MSX in debug mode

- pwiz_tools/Skyline/Controls/LongWaitDlg.cs
> Fix intermittent exception in LongWaitDlg.

- pwiz_tools/Skyline/FileUI/ImportTransitionListErrorDlg.Designer.cs
> Fix to speed up showing ImportTransitionListErrorDlg

- pwiz_tools/Skyline/UpgradeManager.cs
(Reported on exception web)
I don't actually know how to test this code, but this is almost the identical code change that I recently made to LongWaitDlg to prevent an ObjectDisposedException just like this.
> Fix ObjectDisposedException in UpgradeManager.update_Complete

- pwiz/data/vendor_readers/Bruker/Reader_Bruker_Test.data/diaPASEF-ms2-noMsMsWithoutPrecursor-mzMobilityFilter.mzML
- pwiz_aux/msrc/utility/vendor_api/Bruker/TimsData.cpp
- fixed diaPASEF's scanEnd treated as inclusive; it's actually exclusive and there's a skipped scan between diaPASEF windows (#772)
> - fixed diaPASEF's scanEnd treated as inclusive

- pwiz/data/vendor_readers/Thermo/SpectrumList_Thermo.cpp
- pwiz/utility/misc/Exception.hpp
- fixed stack overflow in Reader_Agilent_Test built under debug mode (caused by an assert in automation_vector destructor throwing in CrtReportHook which caused another assert, and so on)
* fixed a thread safety issue with Thermo precursorCache_
> - fixed stack overflow in Reader_Agilent_Test built under debug mode

- pwiz_tools/Skyline/TestUtil/TestFunctional.cs
It looks like some of the tutorial tests can't handle "ForceMzml".
> Fix tutorial tests including TestExistingExperimentsTutorial.

- pwiz_tools/Skyline/Model/Irt/RCalcIrt.cs
This reverts commit ae39f388448af5f9ff74421c33ce1e62a34268f1.
> Revert "Allow iRT peptides to match heavy or light"

- pwiz_tools/BiblioSpec/src/MaxQuantReader.cpp
Fixes issue [712](https://skyline.ms/issues/home/issues/details.view?issueId=712)
> * added support for MaxQuant's NotNTerm and NotCTerm fixed mods

- pwiz_tools/MSConvertGUI/MainForm.Designer.cs
- pwiz_tools/MSConvertGUI/MainForm.cs
- pwiz_tools/MSConvertGUI/MainForm.resx
- pwiz_tools/MSConvertGUI/MainLogic.cs
- pwiz_tools/MSConvertGUI/ProgressForm.cs
- pwiz_tools/MSConvertGUI/Properties/Settings.Designer.cs
- pwiz_tools/MSConvertGUI/Properties/Settings.settings
- pwiz_tools/MSConvertGUI/app.config
- pwiz_tools/SeeMS/DataSource.cs
- pwiz_tools/SeeMS/Dialogs/OpenDataSourceDialog.cs
- pwiz_tools/SeeMS/Program.cs
- pwiz_tools/SeeMS/Properties/Settings.Designer.cs
- pwiz_tools/SeeMS/Properties/Settings.settings
- pwiz_tools/SeeMS/app.config
- pwiz_tools/SeeMS/seems.Designer.cs
- pwiz_tools/SeeMS/seems.cs
- added "Files to convert in parallel" setting to MSConvertGUI to reduce problems with converting multiple Thermo files hanging
- added SIM/SRMAsSpectra options to SeeMS' view menu
> - added "Files to convert in parallel" setting to MSConvertGUI

- pwiz_tools/Skyline/SettingsUI/Irt/CalibrateIrtDlg.cs
- pwiz_tools/Skyline/SettingsUI/PeptideGridViewDriver.cs
https://skyline.ms/announcements/home/issues/exceptions/thread.view?rowId=43951
> Fix exception in CalibrateIrtDlg

- pwiz/analysis/spectrum_processing/SpectrumList_LockmassRefiner.cpp
- pwiz/data/vendor_readers/Waters/SpectrumList_Waters.cpp
* correction is still only applied if binary data is requested
> * reverted to removing lockmass correction even if only metadata is requested

- pwiz_tools/Skyline/Model/Prosit/Models/PrositModel.cs
- pwiz_tools/Skyline/Model/Prosit/PrositConstants.cs
- Requested by Benoit
https://skyline.ms/announcements/home/support/thread.view?rowId=44151
> Skyline: Add Propionamide (C) support to Prosit

- pwiz_tools/Skyline/SettingsUI/DocumentSettingsDlg.Designer.cs
- pwiz_tools/Skyline/SettingsUI/DocumentSettingsDlg.cs
- pwiz_tools/Skyline/SettingsUI/DocumentSettingsDlg.resx
- pwiz_tools/Skyline/Skyline.cs
- pwiz_tools/Skyline/TestFunctional/DocumentReportTest.cs
> Add "Add" and "Edit List" buttons to Reports tab of DocumentSettingsDlg

- pwiz_tools/Skyline/Controls/LongWaitDlg.ja.resx
- pwiz_tools/Skyline/Controls/LongWaitDlg.zh-CHS.resx
> Fix resizing of LongWaitDlg in Japanese and Chinese.

- pwiz_tools/Skyline/Model/Results/MsDataFileScanHelper.cs
> Fix IndexOutOfRangeException in MsDataFileScanHelper.

- pwiz_tools/Bumbershoot/idpicker/Forms/GroupingControlForm.cs
- pwiz_tools/Bumbershoot/idpicker/Forms/IDPickerForm.cs
- pwiz_tools/Bumbershoot/idpicker/Forms/ReportErrorDlg.Designer.cs
- pwiz_tools/Bumbershoot/idpicker/Forms/ReportErrorDlg.resx
- pwiz_tools/SeeMS/Manager.cs
- fixed opening idpDBs with lowercase extension
- fixed Source Grouping control to be able to handle and fix somewhat corrupted groups and fixed handling of trailing slashes in assembly.txt
- removed "Report" options from error dialog
- fixed empty spectrumList passed to SeeMS causing an error
> Fix IDPicker issues

- pwiz_tools/Bumbershoot/idpicker/Forms/ExportLibrarySettings.cs
- pwiz_tools/Bumbershoot/idpicker/Forms/ReportErrorDlg.cs
- pwiz_tools/Bumbershoot/idpicker/Program.cs
- pwiz_tools/Bumbershoot/idpicker/Util/Util.csproj
- pwiz_tools/Bumbershoot/idpicker/Util/Version.cs
- IDPicker: fixed ReportErrorDlg crashing on some systems due to ActiveDirectory error
- IDPicker: fixed checking for new version
> - IDPicker: fixed ReportErrorDlg crashing on some systems

- pwiz_tools/Bumbershoot/idpicker/Forms/BaseTableForm.cs
- pwiz_tools/Bumbershoot/idpicker/Forms/EmbedderForm.Designer.cs
- pwiz_tools/Bumbershoot/idpicker/Forms/EmbedderForm.cs
- pwiz_tools/Bumbershoot/idpicker/Forms/EmbedderForm.resx
- pwiz_tools/Bumbershoot/idpicker/Forms/PeptideTableForm.cs
- pwiz_tools/Bumbershoot/idpicker/Forms/ProteinTableForm.cs
- pwiz_tools/Bumbershoot/idpicker/Forms/SpectrumTableForm.cs
- pwiz_tools/Bumbershoot/idpicker/Model/DataModel.cs
- pwiz_tools/Bumbershoot/idpicker/Qonverter/CLI/Embedder.cpp
- pwiz_tools/Bumbershoot/idpicker/Qonverter/CLI/Embedder.hpp
- pwiz_tools/Bumbershoot/idpicker/Qonverter/Embedder.cpp
- pwiz_tools/Bumbershoot/idpicker/Qonverter/Embedder.hpp
- pwiz_tools/Bumbershoot/idpicker/Qonverter/EmbedderTest.cpp
* refactored common isobaric column code to common BaseTableForm
> - IDPicker: added support for TMT11plex and TMTpro16plex

- Jamroot.jam
- pwiz_tools/BiblioSpec/Jamfile.jam
- pwiz_tools/Bumbershoot/Jamfile.jam
- pwiz_tools/Bumbershoot/idpicker/Test/packages.config
- pwiz_tools/Bumbershoot/idpicker/packages.config
* removed obsolete SharpSvn Nuget package from IDPicker packages
> * fixed source tarball issues caused by Boost.Build upgrade

- pwiz_tools/Bumbershoot/idpicker/Forms/SpectrumTableForm.cs
- pwiz_tools/Bumbershoot/idpicker/LayoutManager.cs
- pwiz_tools/Bumbershoot/idpicker/Model/Settings.cs
- IDPicker: fixed "XmlException: Unexpected end of file" error when opening idpDB after last update
- IDPicker: fixed another issue with spectrum view PSM rows
> - IDPicker: fixed "XmlException: Unexpected end of file" error

- pwiz_aux/msrc/utility/vendor_api/UNIFI/UnifiData.cpp
- fixed support for UNIFI servers with request throttling giving "429 Too Many Requests" error (reported by Susan Slade)
* changed UnifiData to use ResponseContentRead and fixed setting of "top" parameter to avoid getting unnecessarily large batches of spectra and only parsing a few of them (performance penalty from this logic bug was not too bad with ResponseHeadersRead but huge with ResponseContentRead)
> - fixed support for UNIFI servers with request throttling

- libraries/boost_aux/boost/enum/macros.hpp
- pwiz_tools/Bumbershoot/idpicker/Qonverter/CLI/QonverterCLI.vcxproj
- pwiz_tools/Bumbershoot/idpicker/Qonverter/CommandlineTest.cpp
- pwiz_tools/Bumbershoot/idpicker/Qonverter/Embedder.cpp
- pwiz_tools/Bumbershoot/idpicker/Qonverter/Embedder.hpp
- pwiz_tools/Bumbershoot/idpicker/Qonverter/Qonverter.vcxproj
- pwiz_tools/Bumbershoot/idpicker/Qonverter/idpQuery.cpp
* added get_by_name_case_insensitive() to BOOST_ENUM
* updated IDPicker CommandlineTest to fix compile error and test all available QuantitationMethods
> - IDPicker: added TMT11/16 options to idpQuery and made its options case insensitive

- pwiz_tools/Skyline/Model/Import.cs
- remove quoting underscores before and after sequence
- move n-terminal mods to after first AA character
> Skyline: Fixes to normalizing sequence columns in Biognosys Assay Libraries

- pwiz_tools/Skyline/Skyline.Designer.cs
- pwiz_tools/Skyline/Skyline.resx
Revert changes that had been made to Skyline.resx that came from a high resolution monitor. (#1208)
> CherryPick from 20.2 Skyline.Resx changes 

- pwiz/analysis/dia_umpire/DiaUmpire.hpp
- pwiz/analysis/dia_umpire/InstrumentParameter.hpp
- pwiz/data/vendor_readers/Thermo/SpectrumList_Thermo.cpp
- pwiz/utility/bindings/CLI/analysis/spectrum_processing.cpp
- pwiz/utility/bindings/CLI/analysis/spectrum_processing.hpp
- fixed Thermo precursors not having spectrumRef when hasMultiplePrecursors() is true
* added CLI bindings for SpectrumList_DiaUmpire
> Fixed SPS/MSX Thermo precursors not having spectrumRef

- pwiz_aux/msrc/utility/vendor_api/thermo/RawFile.cpp
It really includes reference peaks now.
> - fixed reference peak inclusion for Thermo

- pwiz_tools/Skyline/Executables/Installer/SetupDeployProject.cs
- pwiz_tools/Skyline/Jamfile.jam
* fixed SetupDeployProject.cs not instantiating ___VENDOR_DLLS___ correctly for Debug builds
> Fix SetupDeployProject.cs for Debug builds

- pwiz_tools/BiblioSpec/src/DiaNNSpecLibReader.cpp
* added support for not-yet-officially-released version 2 of DIA-NN's speclib format speclib format, but DIA-NN dev has assured me that if speclib changes again before release it will have a new version
* added error if speclib version is newer than BiblioSpec's supported version
> * added support for version 2 of DIA-NN's speclib format

- pwiz_tools/Skyline/SettingsUI/ViewLibraryPepMatching.cs
Library Explorer - Add All button
Reported by: Clarisse
> Skyline: Fix to include PeptideSettings - Filter tab settings in Add All

- pwiz_tools/Skyline/Model/Databinding/Entities/ColumnCaptions.Designer.cs
- pwiz_tools/Skyline/Model/Databinding/Entities/ColumnCaptions.resx
- pwiz_tools/Skyline/Model/Databinding/Entities/ColumnToolTips.Designer.cs
- pwiz_tools/Skyline/Model/Databinding/Entities/ColumnToolTips.resx
- pwiz_tools/Skyline/Model/Databinding/Entities/TransitionResult.cs
From https://skyline.ms/announcements/home/support/thread.view?rowId=49861
> Add average cycle time

- pwiz_tools/Skyline/Model/Import.cs
- pwiz_tools/Skyline/Model/SmallMoleculeTransitionListReader.cs
- pwiz_tools/Skyline/Test/MassListInputsTest.cs
- pwiz_tools/Skyline/Test/Test.csproj
- detect international formats regardless of the current culture
> Skyline: Improve transition list format detection

- pwiz_tools/Skyline/Model/SrmDocumentSharing.cs
> Remove duplicate AddFile

- pwiz_tools/Skyline/TestFunctional/DiaSearchTest.cs
* changed DiaSearchTests to use only 1 thread for DiaUmpire to check whether that eliminates failures
> * changed DiaSearchTests to use only 1 thread for DiaUmpire

- pwiz_tools/Skyline/Model/Serialization/DocumentFormat.cs
- pwiz_tools/Skyline/TestUtil/Schemas/Skyline_21_1.xsd
- pwiz_tools/Skyline/TestUtil/TestUtil.csproj
Update version number in DocumentFormat.cs to 21.1 to match value in 21.1 Release Branch.
> Update DocumentFormat version number in master branch to 21.1

- pwiz_tools/Shared/Common/Properties/Resources.ja.resx
- pwiz_tools/Skyline/CommandArgUsage.ja.resx
- pwiz_tools/Skyline/Controls/Graphs/AreaCVToolbarProperties.zh-CHS.resx
- pwiz_tools/Skyline/Controls/Graphs/DetectionToolbarProperties.zh-CHS.resx
- pwiz_tools/Skyline/Controls/Graphs/DetectionsToolbar.ja.resx
- pwiz_tools/Skyline/EditUI/PermuteIsotopeModificationsDlg.ja.resx
- pwiz_tools/Skyline/FileUI/PeptideSearch/ConverterSettingsControl.ja.resx
- pwiz_tools/Skyline/Menus/ChromatogramContextMenu.ja.resx
- pwiz_tools/Skyline/Model/AuditLog/EnumNames.ja.resx
- pwiz_tools/Skyline/Model/Databinding/Entities/ColumnCaptions.ja.resx
- pwiz_tools/Skyline/Model/Databinding/Entities/ColumnToolTips.zh-CHS.resx
- pwiz_tools/Skyline/Properties/Resources.ja.resx
- pwiz_tools/Skyline/SettingsUI/PeptideSettingsUI.ja.resx
* Skyline (21.1): Reviewer changes to Japanese translation
* Skyline (21.1): Reviewer changes to Chinese translation
> Skyline/work/20210606 review resx translation (#1630)

- Jamroot.jam
- pwiz/analysis/dia_umpire/DiaUmpire.cpp
- pwiz/analysis/dia_umpire/DiaUmpire.hpp
- pwiz/analysis/dia_umpire/InstrumentParameter.hpp
- pwiz/analysis/dia_umpire/PeakCluster.hpp
- pwiz/analysis/dia_umpire/PeakCurve.hpp
- pwiz/analysis/dia_umpire/ScanData.hpp
- fixed occasional AddPeak failures due to unsorted result returned from ScanCollection.GetScanNoArray()
* fixed various questionably initialized variables, thread safety issues, and compiler warnings
* enabled .NET projects to build on VS2019
> Cherry pick 1637 to release (DiaUmpire fix)

- libraries/ext-boost.jam
- pwiz/utility/bindings/CLI/example/Jamfile.jam
* fixed dangling svnrev reference
> * fixed compile errors in a few build configs after Boost 1.76 update

- pwiz/analysis/dia_umpire/DiaUmpire.cpp
- pwiz/analysis/dia_umpire/PeakCluster.hpp
* rearranged DiaUmpire scan processing code and added some locks to prevent data races, one or the other will hopefully avoid some mysterious crashes
> Fix DiaUmpire crashes (hopefully)

- .github/workflows/build_and_test.yml
- pwiz_tools/Skyline/Executables/Installer/Jamfile.jam
* fixed GitHub Actions ignore path to ignore more than the root of each ignored path
> * fixed GitHub Actions ignore path

- pwiz_tools/Skyline/Model/Serialization/DocumentWriter.cs
- pwiz_tools/Skyline/Model/TransitionDocNode.cs
For this Panorama support request: https://panoramaweb.org/home/support/announcements-thread.view?rowId=6233
> Write transition CE and DP to the protobuf

- pwiz/analysis/dia_umpire/DiaUmpire.cpp
- pwiz/analysis/dia_umpire/PeakCluster.hpp
* rearranged DiaUmpire scan processing code and added some locks to prevent data races, which seems to avoid crashes based on a week of testing in master
> Cherry pick 1664 to release

- pwiz_tools/Skyline/Model/Serialization/DocumentWriter.cs
- pwiz_tools/Skyline/Model/TransitionDocNode.cs
(cherry picked from commit 4014cf6fb8ce2f7748f59207cdfbd7d62026a532)
> Write transition CE and DP to the protobuf (#1688)

- pwiz_tools/Skyline/FileUI/ExportMethodDlg.cs
- pwiz_tools/Skyline/Model/Export.cs
https://skyline.ms/announcements/home/support/thread.view?rowId=52128
> Enable writing CoV values for Thermo Fusion

- pwiz_tools/Skyline/Model/Results/SpectrumFilterPair.cs
Replace two Nullable<double> with two double and two boolean. This reduces memory footprint of SpectrumFilterPair class, and might speed up "ContainsRetentionTime".
This makes things appear closer to what they were before. It's hard to say whether it actually makes things faster.
It definitely makes it so that "ContainsRetentionTime" does not show up in the profile:
compared to what it was after my most recent commit:
```
public bool ContainsRetentionTime(double retentionTime)
{
return !(MinTime > retentionTime) && !(MaxTime < retentionTime);
}
```
It's hard to say how this compares to what it was before I committed:
```
public bool ContainsRetentionTime(double retentionTime)
{
return !_filterByTime || (_minTime <= retentionTime && retentionTime <= _maxTime);
}
```
> Perf improvement on SpectrumFilterPair.ContainsRetentionTime

- pwiz_aux/msrc/utility/vendor_api/Bruker/TimsData.cpp
- added workaround for timsTOF data which has erroneous (?) DiaFrameMsMsWindows.ScanNumEnd > Frame.NumScans
> Workaround out of range timsTOF ScanNumEnd

- pwiz/analysis/spectrum_processing/SpectrumListFactory.cpp
- pwiz/analysis/spectrum_processing/SpectrumList_PeakPicker.cpp
- pwiz_tools/commandline/msconvert.cpp
- fixed msconvert --singleThreaded option
> - improved peakPicking performance at low detail levels

- pwiz_tools/Skyline/Model/TransitionGroupDocNode.cs
(Small change to trigger new builds on TeamCity)
> Fix a few spelling mistakes.

- pwiz_tools/Skyline/Skyline.csproj
> Fix file associations that were broken by PR#1697.

- pwiz_tools/Skyline/Controls/Clustering/HeatMapGraph.cs
> Fix NullReferenceException in HeatMapGraph.UpdateSelection

- pwiz_tools/Skyline/Alerts/MsFraggerDownloadDlg.cs
- pwiz_tools/Skyline/Alerts/SimpleFileDownloaderDlg.cs
- pwiz_tools/Skyline/Program.cs
- pwiz_tools/Skyline/TestRunner/Program.cs
- pwiz_tools/Skyline/TestRunnerLib/RunTests.cs
- pwiz_tools/Skyline/Util/UtilInstall.cs
* fixed wrong JRE download URL
* added Skyline.Program.UseOriginalURLs property for testing real URLs
> Fix JRE URL and add property for testing original URLs

- pwiz_tools/commandline/msconvert.cpp
- fixed an iteration progress message issue in msconvert
- fixed failed runs in msconvert not being reported as failed files
> Fix iteration progress and failed runs not being reported as failed files in msconvert

- pwiz_tools/Skyline/Alerts/KeyValueGridDlg.cs
- pwiz_tools/Skyline/FileUI/PeptideSearch/ImportPeptideSearchDlg.cs
- pwiz_tools/Skyline/FileUI/PeptideSearch/SearchSettingsControl.cs
- pwiz_tools/Skyline/Model/AbstractDdaConverter.cs
- pwiz_tools/Skyline/Model/AbstractDdaSearchEngine.cs
- pwiz_tools/Skyline/Model/DdaSearch/MSAmandaSearchWrapper.cs
- pwiz_tools/Skyline/Model/DdaSearch/MsFraggerSearchEngine.cs
- pwiz_tools/Skyline/Model/DdaSearch/MsconvertDdaConverter.cs
- pwiz_tools/Skyline/Model/DdaSearch/MsgfPlusSearchEngine.cs
- pwiz_tools/Skyline/Model/DiaUmpireDdaConverter.cs
- pwiz_tools/Skyline/TestFunctional/DiaSearchTest.cs
* fixed some format issues with KeyValueGridDlg and added space before first row
> - fixed Import Peptide Search for DIA files and MSFragger

- pwiz/data/vendor_readers/ABI/ChromatogramList_ABI.cpp
- pwiz_aux/msrc/utility/vendor_api/ABI/WiffFile.cpp
- pwiz_aux/msrc/utility/vendor_api/ABI/WiffFile.hpp
- pwiz_aux/msrc/utility/vendor_api/ABI/WiffFile2.ipp
> - added total wavelength chromatogram for WIFF files with UV (DAD) detector

- pwiz/data/vendor_readers/Shimadzu/ChromatogramList_Shimadzu.cpp
- pwiz_aux/msrc/utility/vendor_api/Shimadzu/ShimadzuReader.cpp
- fixed Shimdazu error when running on Wine/Docker with a file that throws a TIC chromatogram exception (reported by Sam Thompson)
> - fixed Shimdazu error when running on Wine/Docker

- pwiz_tools/SeeMS/Dialogs/HeatmapForm.cs
- pwiz_tools/SeeMS/Dialogs/SpectrumListForm.cs
- pwiz_tools/SeeMS/Manager.cs
- pwiz_tools/SeeMS/Misc/SpectrumDataSet.cs
* added FAIMS support to SeeMS (CV is put in the ion mobility column but ion mobility heatmaps are not generated)
> * added FAIMS support to SeeMS

- pwiz_tools/Skyline/Model/GroupComparison/GroupComparisonStrings.Designer.cs
- pwiz_tools/Skyline/Model/GroupComparison/GroupComparisonStrings.resx
- pwiz_tools/Skyline/Model/GroupComparison/NormalizationMethod.cs
Fixed localization of "Ratio to Global Standards" etc. label on the Y-axis of peak area graph. (Reported by Brendan)
> Fix NormalizationMethod localization

- pwiz/data/msdata/SpectrumWorkerThreads.cpp
- pwiz_aux/msrc/utility/vendor_api/Bruker/Baf2Sql.cpp
- pwiz_aux/msrc/utility/vendor_api/Bruker/Baf2Sql.hpp
- increased maximum worker thread count for msconvert to 16
- added support for getting CE from Bruker BAF format
Closes #2087
> Get CE from Bruker BAF format

- pwiz_tools/Skyline/Model/Serialization/DocumentFormat.cs
- pwiz_tools/Skyline/Test/DocumentSerializerTest.cs
to enforce correct format incrementing between major versions
> Skyline: Add detail to the comment in DocumentFormat and a test... 

- pwiz_tools/Skyline/FileUI/ImportTransitionListColumnSelectDlg.cs
- pwiz_tools/Skyline/TestFunctional/PasteMoleculesTest.cs
Reported anonymously via exception web.
> Improved handling of transition list imports when the number of columns varies from line to line.

- pwiz_tools/Skyline/TestPerf/DiaSwathTutorialTest.cs
- pwiz_tools/Skyline/TestTutorial/TutorialAuditLogs/en/TestDiaQeFullSearchTutorial.log
- pwiz_tools/Skyline/TestTutorial/TutorialAuditLogs/en/TestDiaTtofFullSearchTutorial.log
- pwiz_tools/Skyline/TestTutorial/TutorialAuditLogs/fr/TestDiaQeFullSearchTutorial.log
- pwiz_tools/Skyline/TestTutorial/TutorialAuditLogs/fr/TestDiaTtofFullSearchTutorial.log
- pwiz_tools/Skyline/TestTutorial/TutorialAuditLogs/ja/TestDiaQeFullSearchTutorial.log
- pwiz_tools/Skyline/TestTutorial/TutorialAuditLogs/ja/TestDiaTtofFullSearchTutorial.log
- pwiz_tools/Skyline/TestTutorial/TutorialAuditLogs/tr/TestDiaQeFullSearchTutorial.log
- pwiz_tools/Skyline/TestTutorial/TutorialAuditLogs/tr/TestDiaTtofFullSearchTutorial.log
- pwiz_tools/Skyline/TestTutorial/TutorialAuditLogs/zh/TestDiaQeFullSearchTutorial.log
- pwiz_tools/Skyline/TestTutorial/TutorialAuditLogs/zh/TestDiaTtofFullSearchTutorial.log
* removed attempt to calculate and test PeptidesPerProteinDlg-style pre-filtering target counts
* updated audit logs
> Fix Qe/Ttof DIA perf tests

- pwiz_tools/MSConvertGUI/MainForm.Designer.cs
- pwiz_tools/MSConvertGUI/MainForm.cs
- added "Show commandline" button to MSConvertGUI to make it easy to get the equivalent msconvert.exe command
> Add "Show commandline" button to MSConvertGUI

- pwiz_tools/Skyline/Controls/Databinding/CandidatePeakForm.resx
- pwiz_tools/Skyline/Controls/Graphs/GraphSpectrum.resx
- pwiz_tools/Skyline/EditUI/AreaChartPropertyDlg.resx
- pwiz_tools/Skyline/EditUI/AssociateProteinsDlg.resx
- pwiz_tools/Skyline/EditUI/FindNodeDlg.resx
- pwiz_tools/Skyline/FileUI/ImportTransitionListColumnSelectDlg.resx
- pwiz_tools/Skyline/FileUI/PeptideSearch/BuildPeptideSearchLibraryControl.ja.resx
- pwiz_tools/Skyline/FileUI/PeptideSearch/BuildPeptideSearchLibraryControl.resx
- pwiz_tools/Skyline/FileUI/PeptideSearch/BuildPeptideSearchLibraryControl.zh-CHS.resx
- pwiz_tools/Skyline/Jamfile.jam
- pwiz_tools/Skyline/Menus/ViewMenu.resx
- pwiz_tools/Skyline/SettingsUI/BuildLibraryDlg.resx
- pwiz_tools/Skyline/SettingsUI/Irt/EditIrtCalcDlg.resx
- pwiz_tools/Skyline/SettingsUI/ViewLibraryDlg.resx
- pwiz_tools/Skyline/Skyline.csproj
- pwiz_tools/Skyline/TestUtil/TestUtil.csproj
- Remove Skyline-daily from RESX files before sending to localization
- Add Skyline_22.13.xsd to TestUtil.csproj
> Skyline: Update version number for 22.2 branch

- pwiz/analysis/spectrum_processing/SpectrumListFactory.cpp
- pwiz/analysis/spectrum_processing/SpectrumList_Filter.cpp
- pwiz/analysis/spectrum_processing/SpectrumList_Filter.hpp
- pwiz/analysis/spectrum_processing/SpectrumList_FilterTest.cpp
- pwiz/data/vendor_readers/UNIFI/Reader_UNIFI.cpp
- pwiz/utility/bindings/CLI/analysis/spectrum_processing.cpp
- pwiz/utility/bindings/CLI/analysis/spectrum_processing.hpp
- added ms level filter option to analyzer filter (so different ms levels can be filtered different ways)
- added defaultDataProcessingRef for ChromatogramList_UNIFI
> Analyzer ms level filter and UNIFI defaultDataProcessingRef

- pwiz_tools/Skyline/Test/SrmSettingsTest.cs
* fixed SerializeProteinAssociationSettingsTest for localized error strings
> * fixed SerializeProteinAssociationSettingsTest

- pwiz_tools/Skyline/TestData/PwizFileInfoTest.cs
- pwiz_tools/Skyline/TestData/Results/SmallWiffTest.cs
- pwiz_tools/Skyline/TestFunctional/MultiSampleImportPeakBoundariesTest.cs
- pwiz_tools/Skyline/TestTutorial/ExistingExperimentsTutorialTest.cs
- Fix potential race conditions in TestMultiSampleImportPeakBoundaries and TestExistingExperimentsTutorial
> Skyline: Make WIFF2 tests NoParallelTesting

- pwiz/utility/misc/cpp_cli_utilities.hpp
- pwiz_aux/msrc/utility/vendor_api/thermo/RawFile.cpp
- fixed possible crash reading large Thermo instrument methods into unmanaged memory (reported by Nathaniel)
> - fixed possible crash reading large Thermo instrument methods

- pwiz_tools/Skyline/TestFunctional/InsertTest.cs
- with some cleanup of the test code
> Skyline: Another attempt at fixing intermittent failures in InsertTest

- pwiz_tools/Skyline/Util/Install.cs
- pwiz_tools/Skyline/Util/Util.cs
- added suffix to version string when running Skyline on Wine
> Add suffix to version string when running Skyline on Wine

- pwiz_tools/Skyline/Controls/Graphs/GraphFullScan.cs
- pwiz_tools/Skyline/SkylineGraphs.cs
This updates the Full Spectrum and Library Match menus to this look. Let me know if any other changes are required in this patch.
> Minimal changes to fix the spectrum context menus

- pwiz_tools/sld/sld.cpp
> allow sldout to read files that were modified during runs

- pwiz/analysis/spectrum_processing/SpectrumList_Filter.cpp
- pwiz/analysis/spectrum_processing/SpectrumList_FilterTest.cpp
Reported by Michelle.
Closes #2408
> - fixed scanNumber filter not working for Thermo

- pwiz.vcxproj
- pwiz.vcxproj.filters
- pwiz/data/msdata/SpectrumList_MGF.cpp
- pwiz_tools/BiblioSpec/Navigation_only_will_not_build.vcxproj
- pwiz_tools/Bumbershoot/idpicker/QuasiTel.R
- pwiz_tools/commandline/msdir.cpp
- added startTimeStamp to msdir
* fixed SpectrumList_MGF tabs
* other small fixes
> Small pwiz fixes

- pwiz_tools/MSConvertGUI/MainForm.Designer.cs
- pwiz_tools/MSConvertGUI/MainForm.cs
- pwiz_tools/MSConvertGUI/MainLogic.cs
- added Waters RAW DDA processing filter
- fixed Add/Remove buttons for filter panel
> MSConvertGUI: Waters RAW DDA processing filter and Add/Remove fix

- pwiz_tools/SeeMS/DataSource.cs
- pwiz_tools/SeeMS/Dialogs/GraphForm.cs
- pwiz_tools/SeeMS/Manager.cs
- pwiz_tools/SeeMS/Types.cs
- fixed SeeMS not adding filename to graph tabs and legends when multiple files with the same run name are open
> SeeMS filename on graph tabs

- pwiz_tools/BiblioSpec/src/PepXMLreader.cpp
- fixed BiblioSpec reading newer MSFragger output from timsTOF (reported by Fengchao)
> - fixed BiblioSpec reading newer MSFragger output from timsTOF

- pwiz_tools/Skyline/Controls/Graphs/GraphChromatogram.cs
Fix error clicking on transition with missing chromatogram (reported on Exception Web)
> Fix NRE in GraphChromatogram.ShadeGraph

- pwiz_tools/Skyline/SkylineTester/CreateZipInstallerWindow.cs
* commented out inclusion of zip files in SkylineTester.zip to decrease its size from 600MB to 100MB
> No zip files in SkylineTester.zip

- pwiz_tools/Skyline/Model/Lib/Library.cs
Change the code so that it passes a SettingsChangeMonitor into the call to "ChangeMeasuredResults".
The SettingsChangeMonitor notices when the SrmDocument in the IDocumentContainer changes, and will cancel the operation. This prevents the settings update code from trying to read from a scale .skyd file.
> Fix intermittent failure in TestMidas test.

- pwiz_tools/Skyline/Jamfile.jam
- pwiz_tools/Skyline/SkylineTester/Program.cs
* added explicit SkylineTesterWithTestData.zip target; will add a manually triggered build config on TeamCity to build and provide this artifact
> Add SkylineTesterWithTestData.zip target

- pwiz/data/msdata/IO.cpp
- pwiz/data/msdata/Serializer_mzML.cpp
* fixed wrong mzML index when spectra/chromatograms are skipped due to errors
> Wrong mzML index when spectra/chromatograms are skipped

- pwiz_tools/Skyline/Controls/Graphs/GraphFullScan.cs
Original issue: https://skyline.ms/announcements/home/support/thread.view?rowId=60276
> Fix for ion mobility view does not work anymore

- pwiz_tools/Skyline/Model/Import.cs
- pwiz_tools/Skyline/Model/SrmDocument.cs
I haven't come up with a repro but the problem is pretty obvious.
This has been popping up a fair amount in ExceptionWeb, as seen in https://skyline.ms/announcements/home/issues/exceptions/thread.view?entityId=e3314598-bf38-103b-a2f7-22f5355603be&_anchor=60600#row:60600
> Deal with an unhandled exception in peptide transition list import. 

- pwiz_tools/Skyline/Skyline.csproj
- pwiz_tools/Skyline/TestPerf/DiaSwathTutorialTest.cs
* fixed hardcoded reference to Release configuration for placeholder SkylineCmd file
> Fix Skyline TC debug build

- pwiz_tools/Skyline/EditUI/UniquePeptidesDlg.Designer.cs
- pwiz_tools/Skyline/EditUI/UniquePeptidesDlg.resx
Added a splitter to the Unique Peptides dialog
Issue 945: Add a splitter to Unique Peptides form
> Issue 945: Add a splitter to Unique Peptides form

- pwiz_tools/Skyline/Model/Lib/EncyclopeDiaHelpers.cs
- pwiz_tools/Skyline/Util/UtilInstall.cs
* fixed overlong path to Java8 binary causing DirectoryNotFound errors on some machines
> * fixed overlong path to Java8 binary

- pwiz_aux/msrc/utility/vendor_api/thermo/RawFile.cpp
- pwiz_aux/msrc/utility/vendor_api/thermo/RawFileTypes.h
- pwiz_tools/commandline/msconvert.cpp
- fixed reading instrument model for very old Thermo RAW files which may store instrument model only in status log
- added commandline parameters for msconvert to output file
Closes #2625
> - fixed reading instrument model for very old Thermo RAW files

- pwiz_tools/commandline/msconvert.cpp
* retry adding msconvert command-line parameters with part commented out to check for DiaUmpire failure
> * retry adding msconvert command-line parameters

- pwiz/analysis/dia_umpire/DiaUmpire.cpp
- pwiz/analysis/dia_umpire/DiaUmpireMath.hpp
- pwiz/analysis/dia_umpire/Jamfile.jam
- pwiz/analysis/dia_umpire/PeakCluster.hpp
- pwiz/analysis/dia_umpire/PeakCurve.hpp
- pwiz/utility/misc/sort_together.hpp
Since updating Boost didn't fix this error, I looked again and found another possible cause for it.
> * fixed latest GCC compile error with DiaUmpire

- .github/workflows/build_and_test.yml
* trying to fix intermittent GitHub actions error with BiblioSpec tarball creation
> Fix intermittent GitHub actions error with tar

- pwiz_tools/Skyline/TestTutorial/TutorialAuditLogs/en/TestGroupedStudies1Tutorial.log
- pwiz_tools/Skyline/TestTutorial/TutorialAuditLogs/fr/TestGroupedStudies1Tutorial.log
- pwiz_tools/Skyline/TestTutorial/TutorialAuditLogs/ja/TestGroupedStudies1Tutorial.log
- pwiz_tools/Skyline/TestTutorial/TutorialAuditLogs/tr/TestGroupedStudies1Tutorial.log
- pwiz_tools/Skyline/TestTutorial/TutorialAuditLogs/zh/TestGroupedStudies1Tutorial.log
- Match Annotations1.xlsx fix made on skyline.ms tutorial files
> Skyline: Fix audit logs for TestGroupedStudies1Tutorial

- pwiz.vcxproj
- pwiz.vcxproj.filters
- pwiz/analysis/spectrum_processing/Jamfile.jam
- pwiz/analysis/spectrum_processing/MzShiftFilter.cpp
- pwiz/analysis/spectrum_processing/MzShiftFilter.hpp
- pwiz/analysis/spectrum_processing/SpectrumListFactory.cpp
- pwiz/analysis/spectrum_processing/SpectrumList_FilterTest.cpp
- pwiz/analysis/spectrum_processing/SpectrumList_PeakFilter.cpp
- pwiz/analysis/spectrum_processing/SpectrumList_PeakFilterTest.cpp
- pwiz/analysis/spectrum_processing/SpectrumList_ZeroSamplesFilter.cpp
- pwiz/utility/misc/IntegerSet.cpp
- pwiz/utility/misc/IntegerSetTest.cpp
- added mzShift filter for shifting all m/z values by a given m/z tolerance (PPM or Da)
* fixed bug in IntegerSet with parsing intervals into an existing set
> - added mzShift filter for shifting all m/z values

- pwiz_tools/Skyline/TestFunctional/MultiInjectRescoreTest.cs
Include text of current document in exception message when test fails.
> Trying to track down intermittent TestMultiInjectRescore failure

- pwiz_tools/Skyline/Executables/SkylineBatch/SkylineBatch/MainForm.cs
Fixed error starting Skyline Batch on some computers (reported by Chi)
> Fix Skyline Batch error

- pwiz_tools/Skyline/Model/Lib/BlibData/BlibDb.cs
Dispose SQLiteCommand objects created by "SpectrumInserter".
> Try to fix TestAssayLibraryImport

- pwiz_tools/Skyline/SkylineFiles.cs
- ModifyDocument is a loop and should never contain UI code
It seems that this was the cause of the failure in the HeavyNickNames test. My prior attempt at a fix just moved the problem.
> Skyline: Remove MultiButtonMsgDlg introduced inside a ModifyDocument method

- pwiz_tools/Skyline/Controls/Clustering/DebugZedGraphControl.cs
- pwiz_tools/Skyline/Controls/Clustering/PcaPlot.Designer.cs
- pwiz_tools/Skyline/Skyline.csproj
Add class "DebugZedGraphControl" which will report any weirdness in "CreateHandle" and "Dispose" methods. This is similar to what was done to track down similar failures involving AllChromatogramsGraph.
> Trying to track down TestClusteredHeatMapFailure

- pwiz_tools/Skyline/TestConnected/PrositConnectionTest.cs
> Fix code inspection

- pwiz_tools/Skyline/Model/Koina/Models/KoinaModel.cs
- pwiz_tools/Skyline/Model/Koina/Models/KoinaRetentionTimeModel.cs
- pwiz_tools/Skyline/ToolsUI/ToolOptionsUI.cs
* commented out problematic Deeplc_hela_hf model
* removed Console.WriteLine left in Koina code by mistake
* fixed GrpcChannel leak (but not unmanaged code leak, still tracking that down)
> Koina fixes

- pwiz_tools/Shared/CommonUtil/SystemUtil/CommonFormEx.cs
This should prevent the cascade of test failures beginning with "TestLibraryBuild" that happened last night.
> Synchronize access to "CommonFormEx._undisposedForms"

- pwiz_tools/Skyline/Model/Koina/Models/KoinaModel.cs
- pwiz_tools/Skyline/TestConnected/KoinaBuildLibraryTest.cs
* fixed errors building Koina library with modified sequences (reported by Phil)
> * fixed errors building Koina library with modified sequences

- pwiz/analysis/spectrum_processing/SpectrumListFactory.cpp
- pwiz/analysis/spectrum_processing/SpectrumListFactoryTest.cpp
- added mode=include/exclude for `--filter "activation"` (requested by Amol)
> - added mode=include/exclude for `--filter "activation"`

- pwiz/data/identdata/Pep2MzIdent.cpp
- pwiz/data/identdata/Serializer_pepXML.cpp
- pwiz/data/proteome/Digestion.cpp
- pwiz/data/tradata/DefaultReaderList.cpp
- pwiz/data/vendor_readers/UNIFI/ChromatogramList_UNIFI.cpp
- pwiz/utility/minimxml/SAXParser.cpp
* changed all static xpressive regexes to const due to "invalid string binding" crash
> * changed all static xpressive regexes to const

- pwiz_tools/Skyline/Model/TransitionGroupDocNode.cs
- pwiz_tools/Skyline/Test/DecoysTest.cs
Fixed error adding decoys to a document with high resolution MS1 and sulfur containing amino acids (reported on exception web)
> Fix add decoy exception

- pwiz_tools/Skyline/Properties/Settings.Designer.cs
- pwiz_tools/Skyline/Properties/Settings.settings
"Settings.Designer.cs" had been manually edited and "Settings.settings" was not up to date with the Prosit -> Koina rename.
> Fix "Settings.settings".

- pwiz_tools/Skyline/TestFunctional/ExportIsolationListTest.cs
When the document has mixed polarity, csv files get created with names ending in "_negative_0001.csv" and "_positive_0001.csv" so those files need to be verified instead.
> Fix TestExportIsolationListAsSmallMoleculesMixedPolarity

- pwiz_tools/Skyline/Alerts/AlertLinkDlg.ja.resx
- pwiz_tools/Skyline/Alerts/AlertLinkDlg.resx
- pwiz_tools/Skyline/Alerts/AlertLinkDlg.zh-CHS.resx
- pwiz_tools/Skyline/Alerts/DetailedReportErrorDlg.ja.resx
- pwiz_tools/Skyline/Alerts/DetailedReportErrorDlg.resx
- pwiz_tools/Skyline/Alerts/DetailedReportErrorDlg.zh-CHS.resx
- pwiz_tools/Skyline/Controls/Graphs/AllChromatogramsGraph.ja.resx
- pwiz_tools/Skyline/Controls/Graphs/AllChromatogramsGraph.resx
- pwiz_tools/Skyline/Controls/Graphs/AllChromatogramsGraph.zh-CHS.resx
- pwiz_tools/Skyline/EditUI/AssociateProteinsDlg.ja.resx
- pwiz_tools/Skyline/EditUI/AssociateProteinsDlg.resx
- pwiz_tools/Skyline/EditUI/AssociateProteinsDlg.zh-CHS.resx
- pwiz_tools/Skyline/EditUI/EditLinkedPeptidesDlg.ja.resx
- pwiz_tools/Skyline/EditUI/EditLinkedPeptidesDlg.resx
- pwiz_tools/Skyline/EditUI/EditLinkedPeptidesDlg.zh-CHS.resx
- pwiz_tools/Skyline/EditUI/UniquePeptidesDlg.ja.resx
- pwiz_tools/Skyline/EditUI/UniquePeptidesDlg.resx
- pwiz_tools/Skyline/EditUI/UniquePeptidesDlg.zh-CHS.resx
- pwiz_tools/Skyline/ToolsUI/EditCustomThemeDlg.ja.resx
- pwiz_tools/Skyline/ToolsUI/EditCustomThemeDlg.resx
- pwiz_tools/Skyline/ToolsUI/EditCustomThemeDlg.zh-CHS.resx
Use "`<value></value>`" instead of "`<value />`" for empty values in .resx files
> Replace "<value />" with "<value></value>" in resx files

- pwiz_tools/Skyline/Model/Proteome/ProteinMetadataManager.cs
Fixed potential hang extracting chromatograms when some protein groups have proteins with nonstandard accession numbers (reported by Mike)
The problem is that when some protein groups have invented accession numbers, a partially-searched ProteinGroupMetadata might be put into ProteinMetadataManager._processedNodes. When that happens, then incompletely searched protein groups in the document never get searched to completion, and ProteinMetadataManager keeps saying it has more work to do but just calls the very expensive method "SrmDocument.ChangeChildrenChecked" with nothing new.
This change makes it so it checks whether the thing in "_processedNodes" is only partially completed, and, if so, makes sure to queue up requests for the unsearched parts of the group.
(This diff is more simple if …
> Fix hang in ProteinMetadataManager

- pwiz_tools/Skyline/Controls/Graphs/AllChromatogramsGraph.cs
Fixed to gracefully handle network error during chromatogram exception (reported on exception web)
> Fix exception in All Chromatograms Graph

- pwiz_tools/Skyline/Controls/Graphs/AllChromatogramsGraph.cs
Fixed to gracefully handle network error during chromatogram exception (reported on exception web)
> Fix exception in All Chromatograms Graph (#3059)

- pwiz_tools/Skyline/TestUtil/AbstractUnitTestEx.cs
* fixed GetSystemResourceString() to reset _systemResources when CurrentUICulture changes
> * fixed GetSystemResourceString()

- pwiz_tools/Skyline/Model/DocSettings/PeptideSettings.cs
- pwiz_tools/Skyline/Model/Koina/KoinaExceptions.cs
- pwiz_tools/Skyline/Model/Koina/KoinaResources.Designer.cs
- pwiz_tools/Skyline/Model/Koina/KoinaResources.ja.resx
- pwiz_tools/Skyline/Model/Koina/KoinaResources.resx
- pwiz_tools/Skyline/Model/Koina/KoinaResources.zh-CHS.resx
- pwiz_tools/Skyline/TestTutorial/LibraryExplorerTutorialTest.cs
Fix all the places where "modification" was incorrectly written as "modifcation".
> Fix "modifcation" typo

- pwiz_tools/Skyline/FileUI/PeptideSearch/SearchSettingsControl.cs
TestFeatureDetectionTutorialFuture caught the problem.
> Recent changes (commit 0a7a9390c) to peptide search UI broke the feature detection UI

- pwiz_tools/Skyline/TestFunctional/AssayLibraryImportTest.cs
- pwiz_tools/Skyline/TestUtil/TestFunctional.cs
Also adds WaitForMultiButtonMsgDlg(string messageFormat, int millis = WAIT_TIME) to wait for a MultiButtonMsgDlg to be shown with a message that could have been created with the given messageFormat
> Deals with a race condition in TestAssayLibraryImport and TestAssayLibraryImportAsSmallMolecules

- pwiz_tools/Skyline/TestTutorial/Ms1FullScanFilteringTutorial.cs
- pwiz_tools/Skyline/TestUtil/AbstractFunctionalTestEx.cs
- Fixed Full Scan graph click and added check that the graphs shown match the expected times in the title
- Several other minor fixes to graph sizing and label placement
> Skyline: Fixes for fully automated screenshots in TestMs1Tutorial

- scripts/misc/vcs_trigger_and_paths_config.py
* fixed changes to root scripts not triggering builds (.bat changes should trigger Windows, .sh changes should trigger Linux)
> * fixed changes to root scripts not triggering builds

- pwiz_tools/Shared/PanoramaClient/PanoramaClient.cs
- pwiz_tools/Shared/PanoramaClient/PanoramaFolderBrowser.cs
- pwiz_tools/Shared/PanoramaClient/PanoramaUtil.cs
- pwiz_tools/Skyline/CommandArgs.cs
- pwiz_tools/Skyline/Executables/SkylineBatch/SkylineBatchTest/RemoteFileSourceFunctionalTest.cs
- pwiz_tools/Skyline/FileUI/PublishDocumentDlg.cs
- pwiz_tools/Skyline/SkylineFiles.cs
- pwiz_tools/Skyline/Test/PublishDocAddSubfolderTest.cs
- pwiz_tools/Skyline/TestData/CommandLineTest.cs
- pwiz_tools/Skyline/TestFunctional/AccessServerTest.cs
- pwiz_tools/Skyline/TestFunctional/PanoramaClientPublishTest.cs
- pwiz_tools/Skyline/TestFunctional/TestPanoramaClient.cs
- pwiz_tools/Skyline/TestTutorial/AuditLogTutorialTest.cs
Merge changes from PR #3288 (Switch to using "effectivePermissions" property for checking LabKey folder permissions)
Related PR: https://github.com/ProteoWizard/pwiz/pull/3288
> Merge changes from PR #3288 to release 24.1 branch

- pwiz_tools/Skyline/Test/ImmutableListTest.cs
- pwiz_tools/Skyline/Test/UtilTest.cs
Also, fix warning about test method "TestNoDiffIgnoringPathDifferences" not allowed to be a static method.
> Some more tests for "ImmutableList"

- pwiz_tools/Skyline/Controls/Startup/StartPage.cs
- pwiz_tools/Skyline/Controls/Startup/TutorialImageResources.Designer.cs
- pwiz_tools/Skyline/Controls/Startup/TutorialImageResources.resx
- pwiz_tools/Skyline/Controls/Startup/TutorialLinkResources.Designer.cs
- pwiz_tools/Skyline/Controls/Startup/TutorialLinkResources.resx
- pwiz_tools/Skyline/Controls/Startup/TutorialTextResources.Designer.cs
- pwiz_tools/Skyline/Controls/Startup/TutorialTextResources.resx
- pwiz_tools/Skyline/Skyline.csproj
- Add PRMOrbitrap and DIA-Umpire-TTOF to the StartPage
> Skyline: Add new tutorials to the Start Page

- pwiz_tools/Skyline/Documentation/Tutorials/PRMOrbitrap/en/index.html
Also fix whitespace around some <b> tags.
> Update instructions for View > Live Reports and View > Libraries menu items.

- pwiz_tools/Skyline/Util/DataGridViewPasteHandler.cs
Fixed unhandled error pasting rows with duplicate IDs into List (reported by Emma)
> Fix unhandled error pasting into List

- pwiz_tools/Skyline/Model/DdaSearch/MSAmandaSearchWrapper.cs
- pwiz_tools/Skyline/Model/DdaSearch/MsgfPlusSearchEngine.cs
- pwiz_tools/Skyline/TestFunctional/DdaSearchTest.cs
> Cherry pick to release: - fixed MSGF+ and MSAmanda for mods with multiple specificities (K,R)

- pwiz_tools/Skyline/Alerts/AlertsResources.designer.cs
- pwiz_tools/Skyline/Alerts/AlertsResources.resx
- pwiz_tools/Skyline/Alerts/MsFraggerDownloadDlg.cs
- pwiz_tools/Skyline/Program.cs
* fixed verification of result from MSFragger verification code button (#3488)
> Cherry pick 3488 to release

- pwiz_tools/Skyline/FileUI/PeptideSearch/EncyclopeDiaSearchDlg.cs
Fixed error running EncyclopeDIA search (reported anonymously)
> Fix AssumptionException EncyclopeDiaSearchDlg

- Jamroot.jam
- pwiz/data/msdata/IO.cpp
- pwiz_tools/BiblioSpec/src/BlibMaker.cpp
- fixed merging of blib files with null idFilename or cutoffScore
* fixed compiling with --without-binary-msdata flag
Closes #3523
> Fix compiling --without-binary-msdata

- pwiz_tools/Skyline/Controls/Graphs/GraphChromatogram.cs
- pwiz_tools/Skyline/Model/Lib/Library.cs
Fix two NullReferenceExceptions reported on the exception web
> Fix two NullReferenceExceptions
